//! Converts `<in-dir>/*.tmLanguage.json` into `<out-dir>/<name>.sublime-syntax`.
//! Usage: cargo run --manifest-path tools/grammars/Cargo.toml -- <in-dir> <out-dir>

use std::{fs, path::PathBuf};

fn main() {
    let mut args = std::env::args().skip(1).map(PathBuf::from);
    let (Some(input), Some(output)) = (args.next(), args.next()) else {
        eprintln!("usage: t3-highlight-grammars <in-dir> <out-dir>");
        std::process::exit(2);
    };
    fs::create_dir_all(&output).expect("create output dir");
    let mut paths: Vec<_> = fs::read_dir(&input)
        .expect("read input dir")
        .map(|entry| entry.expect("dir entry").path())
        .filter(|path| path.to_string_lossy().ends_with(".tmLanguage.json"))
        .collect();
    paths.sort();
    for path in paths {
        let name = path
            .file_name()
            .unwrap()
            .to_string_lossy()
            .trim_end_matches(".tmLanguage.json")
            .to_string();
        let source = fs::read_to_string(&path).expect("read grammar");
        let grammar = syntect_tmlanguage::RawGrammar::from_json(&source).expect("parse grammar");
        // Validate with syntect's own loader before writing, so a bad grammar fails here.
        syntect_tmlanguage::translate(&grammar).unwrap_or_else(|error| panic!("{name}: {error}"));
        let yaml = syntect_tmlanguage::translate::to_sublime_syntax_yaml(&grammar)
            .unwrap_or_else(|error| panic!("{name}: {error}"));
        let header = format!(
            "# Generated by crates/t3-highlight/tools/export-assets.mjs from Shiki's {name} grammar. Do not edit.\n"
        );
        fs::write(output.join(format!("{name}.sublime-syntax")), header + &yaml)
            .expect("write syntax");
        println!("{name}.sublime-syntax");
    }
}
