//! The snapshot fixtures in `crates/t3-snapshots/fixtures` (written by
//! `examples/dump_fixtures.rs`) load into the client's state types without loss.
//!
//! Failure modes:
//! 1. A fixture no longer deserializes after a type change (scenes would fail to load).
//! 2. Serialization is lossy: re-serializing the loaded value differs from the file, so
//!    fixtures regenerated by an older or newer build drift silently.
//! 3. The manifest points at a missing file, or a thread fixture holds no thread.

use std::path::{Path, PathBuf};

use serde::{Serialize, de::DeserializeOwned};
use serde_json::Value;
use t3_client::{ShellState, SyncStatus, ThreadState};
use t3_protocol::{orchestration::OrchestrationShellSnapshot, server::ServerConfig};

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../t3-snapshots/fixtures")
}

/// Loads `name` as `T` and checks that serializing it again yields the same JSON.
fn round_trip<T: DeserializeOwned + Serialize>(name: &str) -> T {
    let text =
        std::fs::read_to_string(fixtures().join(name)).unwrap_or_else(|e| panic!("{name}: {e}"));
    let value: T = serde_json::from_str(&text).unwrap_or_else(|e| panic!("{name}: {e}"));
    let original: Value = serde_json::from_str(&text).unwrap();
    assert_eq!(
        serde_json::to_value(&value).unwrap(),
        original,
        "{name} changed on a round trip"
    );
    value
}

#[test]
fn every_fixture_loads_into_its_type() {
    let manifest: Value =
        serde_json::from_str(&std::fs::read_to_string(fixtures().join("manifest.json")).unwrap())
            .unwrap();

    let config: ServerConfig = round_trip(manifest["serverConfig"].as_str().unwrap());
    assert!(!config.providers.is_empty());

    let shell: ShellState = round_trip(manifest["shell"].as_str().unwrap());
    assert_eq!(shell.status, SyncStatus::Live);
    assert_eq!(
        shell.projects.len(),
        manifest["projects"].as_array().unwrap().len()
    );

    let _archived: OrchestrationShellSnapshot =
        round_trip(manifest["archivedShell"].as_str().unwrap());

    let threads = manifest["threads"].as_array().unwrap();
    assert!(!threads.is_empty());
    for entry in threads {
        let Some(file) = entry["file"].as_str() else {
            assert_eq!(
                entry["archived"], true,
                "only archived threads lack a fixture"
            );
            continue;
        };
        let state: ThreadState = round_trip(file);
        let thread = state
            .thread
            .as_ref()
            .unwrap_or_else(|| panic!("{file} has no thread"));
        assert_eq!(thread.id.as_str(), entry["id"].as_str().unwrap());
        assert!(
            shell.thread(&thread.id).is_some(),
            "{file} is not in the shell"
        );
    }
}
