// @generated by crates/t3-ui/tools/gen_icons.py from assets/icons. Do not edit.
// Regenerate: python3 crates/t3-ui/tools/gen_icons.py

use gpui_kit::Hsla;

use crate::tokens::hex;

/// Single-color UI icons. Lucide icons keep their 24px grid and stroke 2 (scaled with the
/// icon size, like lucide without `absoluteStrokeWidth`). Doc comments list the
/// `lucide-react` import names used by the web UI.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum IconName {
    /// lucide `archive-x` (`ArchiveX`)
    ArchiveX,
    /// lucide `archive` (`ArchiveIcon`)
    Archive,
    /// lucide `arrow-down` (`ArrowDownIcon`)
    ArrowDown,
    /// lucide `arrow-left` (`ArrowLeft`, `ArrowLeftIcon`)
    ArrowLeft,
    /// lucide `arrow-right` (`ArrowRight`, `ArrowRightIcon`)
    ArrowRight,
    /// lucide `arrow-up-down` (`ArrowUpDownIcon`)
    ArrowUpDown,
    /// lucide `arrow-up` (`ArrowUpIcon`)
    ArrowUp,
    /// lucide `bot` (`BotIcon`)
    Bot,
    /// lucide `bug` (`BugIcon`)
    Bug,
    /// lucide `camera` (`Camera`)
    Camera,
    /// lucide `chart-no-axes-column` ()
    ChartNoAxesColumn,
    /// lucide `check` (`CheckIcon`)
    Check,
    /// lucide `chevron-down` (`ChevronDownIcon`)
    ChevronDown,
    /// lucide `chevron-left` (`ChevronLeftIcon`)
    ChevronLeft,
    /// lucide `chevron-right` (`ChevronRight`, `ChevronRightIcon`)
    ChevronRight,
    /// lucide `chevron-up` (`ChevronUpIcon`)
    ChevronUp,
    /// lucide `chevrons-left-right-ellipsis` (`ChevronsLeftRightEllipsisIcon`)
    ChevronsLeftRightEllipsis,
    /// lucide `chevrons-up-down` (`ChevronsUpDownIcon`)
    ChevronsUpDown,
    /// lucide `circle-alert` (`CircleAlertIcon`)
    CircleAlert,
    /// lucide `circle-arrow-up` (`ArrowUpCircleIcon`)
    CircleArrowUp,
    /// lucide `circle-check` (`CircleCheckIcon`)
    CircleCheck,
    /// lucide `circle-dashed` ()
    CircleDashed,
    /// lucide `circle-x` (`CircleXIcon`)
    CircleX,
    /// lucide `clipboard-list` (`ClipboardList`)
    ClipboardList,
    /// lucide `cloud-upload` (`CloudUploadIcon`)
    CloudUpload,
    /// lucide `cloud` (`CloudIcon`)
    Cloud,
    /// lucide `code-xml` (`Code2`)
    CodeXml,
    /// lucide `columns-2` (`Columns2Icon`)
    Columns2,
    /// lucide `container` (`ContainerIcon`)
    Container,
    /// lucide `copy` (`CopyIcon`)
    Copy,
    /// lucide `corner-left-up` (`CornerLeftUpIcon`)
    CornerLeftUp,
    /// lucide `download` (`DownloadIcon`)
    Download,
    /// lucide `earth` (`Globe2`, `Globe2Icon`)
    Earth,
    /// lucide `ellipsis-vertical` (`MoreVertical`)
    EllipsisVertical,
    /// lucide `ellipsis` (`EllipsisIcon`)
    Ellipsis,
    /// lucide `external-link` (`ExternalLink`, `ExternalLinkIcon`)
    ExternalLink,
    /// lucide `eye-off` (`EyeOffIcon`)
    EyeOff,
    /// lucide `eye` (`Eye`, `EyeIcon`)
    Eye,
    /// lucide `file-braces` (`FileJsonIcon`)
    FileBraces,
    /// lucide `file-diff` (`FileDiff`)
    FileDiff,
    /// lucide `file` (`FileIcon`)
    File,
    /// lucide `files` (`Files`)
    Files,
    /// lucide `flask-conical` (`FlaskConicalIcon`)
    FlaskConical,
    /// lucide `folder-closed` (`FolderClosedIcon`)
    FolderClosed,
    /// lucide `folder-git-2` (`FolderGit2Icon`)
    FolderGit2,
    /// lucide `folder-git` (`FolderGitIcon`)
    FolderGit,
    /// lucide `folder-open` (`FolderOpenIcon`)
    FolderOpen,
    /// lucide `folder-plus` (`FolderPlusIcon`)
    FolderPlus,
    /// lucide `folder-tree` (`FolderTree`)
    FolderTree,
    /// lucide `folder` (`FolderIcon`)
    Folder,
    /// lucide `frame` (`Frame`)
    Frame,
    /// lucide `gauge` ()
    Gauge,
    /// lucide `git-branch-plus` (`GitBranchPlusIcon`)
    GitBranchPlus,
    /// lucide `git-branch` (`GitBranchIcon`)
    GitBranch,
    /// lucide `git-commit-horizontal` (`GitCommitIcon`)
    GitCommitHorizontal,
    /// lucide `git-pull-request` (`GitPullRequestIcon`)
    GitPullRequest,
    /// lucide `globe` (`Globe`, `GlobeIcon`)
    Globe,
    /// lucide `hammer` (`HammerIcon`)
    Hammer,
    /// lucide `info` (`InfoIcon`)
    Info,
    /// lucide `keyboard` (`KeyboardIcon`)
    Keyboard,
    /// lucide `link-2` (`Link2`, `Link2Icon`)
    Link2,
    /// lucide `link` (`LinkIcon`)
    Link,
    /// lucide `list-checks` (`ListChecksIcon`)
    ListChecks,
    /// lucide `list-todo` (`ListTodoIcon`)
    ListTodo,
    /// lucide `loader-circle` (`Loader2Icon`, `LoaderCircle`, `LoaderCircleIcon`)
    LoaderCircle,
    /// lucide `loader` (`LoaderIcon`)
    Loader,
    /// lucide `lock` (`LockIcon`)
    Lock,
    /// lucide `log-in` (`LogInIcon`)
    LogIn,
    /// lucide `maximize-2` (`Maximize2Icon`)
    Maximize2,
    /// lucide `message-circle` (`MessageCircle`, `MessageCircleIcon`)
    MessageCircle,
    /// lucide `message-square-dashed` ()
    MessageSquareDashed,
    /// lucide `message-square` (`MessageSquareIcon`)
    MessageSquare,
    /// lucide `minimize-2` (`Minimize2Icon`)
    Minimize2,
    /// lucide `minus` (`Minus`, `MinusIcon`)
    Minus,
    /// lucide `monitor` (`MonitorIcon`)
    Monitor,
    /// lucide `mouse-pointer-2` (`MousePointer2`)
    MousePointer2,
    /// lucide `mouse-pointer-click` (`MousePointerClick`, `MousePointerClickIcon`)
    MousePointerClick,
    /// lucide `paintbrush` (`Paintbrush`, `PaintbrushIcon`)
    Paintbrush,
    /// lucide `panel-bottom-close` (`PanelBottomCloseIcon`)
    PanelBottomClose,
    /// lucide `panel-bottom-open` (`PanelBottomOpenIcon`)
    PanelBottomOpen,
    /// lucide `panel-left-close` (`PanelLeftCloseIcon`)
    PanelLeftClose,
    /// lucide `panel-left-open` (`PanelLeftOpenIcon`)
    PanelLeftOpen,
    /// lucide `panel-right-close` (`PanelRightCloseIcon`)
    PanelRightClose,
    /// lucide `panel-right-open` (`PanelRightOpenIcon`)
    PanelRightOpen,
    /// lucide `pen-line` (`PenLine`)
    PenLine,
    /// lucide `pilcrow` (`PilcrowIcon`)
    Pilcrow,
    /// lucide `pipette` (`PipetteIcon`)
    Pipette,
    /// lucide `play` (`PlayIcon`)
    Play,
    /// lucide `plus` (`Plus`, `PlusIcon`)
    Plus,
    /// lucide `qr-code` (`QrCodeIcon`)
    QrCode,
    /// lucide `radio-tower` (`RadioTower`)
    RadioTower,
    /// lucide `refresh-cw` (`RefreshCw`, `RefreshCwIcon`)
    RefreshCw,
    /// lucide `rotate-ccw` (`RotateCcw`, `RotateCcwIcon`)
    RotateCcw,
    /// lucide `rotate-cw` (`RotateCw`, `RotateCwIcon`)
    RotateCw,
    /// lucide `rows-3` (`Rows3Icon`)
    Rows3,
    /// lucide `search` (`Search`, `SearchIcon`)
    Search,
    /// lucide `settings-2` (`Settings2Icon`)
    Settings2,
    /// lucide `settings` (`SettingsIcon`)
    Settings,
    /// lucide `sliders-horizontal` ()
    SlidersHorizontal,
    /// lucide `smartphone` (`SmartphoneIcon`)
    Smartphone,
    /// lucide `sparkles` (`SparklesIcon`)
    Sparkles,
    /// lucide `square-pen` (`SquarePenIcon`)
    SquarePen,
    /// lucide `square-split-horizontal` (`SquareSplitHorizontal`)
    SquareSplitHorizontal,
    /// lucide `square-split-vertical` (`SquareSplitVertical`)
    SquareSplitVertical,
    /// lucide `square-terminal` (`TerminalSquare`)
    SquareTerminal,
    /// lucide `star` (`StarIcon`)
    Star,
    /// lucide `terminal` (`TerminalIcon`)
    Terminal,
    /// lucide `text-wrap` (`TextWrapIcon`, `WrapTextIcon`)
    TextWrap,
    /// lucide `ticket` ()
    Ticket,
    /// lucide `trash-2` (`Trash2`, `Trash2Icon`)
    Trash2,
    /// lucide `trending-down` ()
    TrendingDown,
    /// lucide `trending-up` ()
    TrendingUp,
    /// lucide `triangle-alert` (`AlertTriangleIcon`, `TriangleAlertIcon`)
    TriangleAlert,
    /// lucide `undo-2` (`Undo2Icon`)
    Undo2,
    /// lucide `wifi-off` (`WifiOffIcon`)
    WifiOff,
    /// lucide `wrench` (`WrenchIcon`)
    Wrench,
    /// lucide `x` (`X`, `XIcon`)
    X,
    /// lucide `zap` (`ZapIcon`)
    Zap,
    /// hand-drawn `check-indicator-bold`
    CheckIndicatorBold,
    /// hand-drawn `check-indicator`
    CheckIndicator,
    /// hand-drawn `indeterminate-bold`
    IndeterminateBold,
    /// hand-drawn `x-bold`
    XBold,
}

impl IconName {
    /// Every icon, in file-name order.
    pub const ALL: &[IconName] = &[
        Self::ArchiveX,
        Self::Archive,
        Self::ArrowDown,
        Self::ArrowLeft,
        Self::ArrowRight,
        Self::ArrowUpDown,
        Self::ArrowUp,
        Self::Bot,
        Self::Bug,
        Self::Camera,
        Self::ChartNoAxesColumn,
        Self::Check,
        Self::ChevronDown,
        Self::ChevronLeft,
        Self::ChevronRight,
        Self::ChevronUp,
        Self::ChevronsLeftRightEllipsis,
        Self::ChevronsUpDown,
        Self::CircleAlert,
        Self::CircleArrowUp,
        Self::CircleCheck,
        Self::CircleDashed,
        Self::CircleX,
        Self::ClipboardList,
        Self::CloudUpload,
        Self::Cloud,
        Self::CodeXml,
        Self::Columns2,
        Self::Container,
        Self::Copy,
        Self::CornerLeftUp,
        Self::Download,
        Self::Earth,
        Self::EllipsisVertical,
        Self::Ellipsis,
        Self::ExternalLink,
        Self::EyeOff,
        Self::Eye,
        Self::FileBraces,
        Self::FileDiff,
        Self::File,
        Self::Files,
        Self::FlaskConical,
        Self::FolderClosed,
        Self::FolderGit2,
        Self::FolderGit,
        Self::FolderOpen,
        Self::FolderPlus,
        Self::FolderTree,
        Self::Folder,
        Self::Frame,
        Self::Gauge,
        Self::GitBranchPlus,
        Self::GitBranch,
        Self::GitCommitHorizontal,
        Self::GitPullRequest,
        Self::Globe,
        Self::Hammer,
        Self::Info,
        Self::Keyboard,
        Self::Link2,
        Self::Link,
        Self::ListChecks,
        Self::ListTodo,
        Self::LoaderCircle,
        Self::Loader,
        Self::Lock,
        Self::LogIn,
        Self::Maximize2,
        Self::MessageCircle,
        Self::MessageSquareDashed,
        Self::MessageSquare,
        Self::Minimize2,
        Self::Minus,
        Self::Monitor,
        Self::MousePointer2,
        Self::MousePointerClick,
        Self::Paintbrush,
        Self::PanelBottomClose,
        Self::PanelBottomOpen,
        Self::PanelLeftClose,
        Self::PanelLeftOpen,
        Self::PanelRightClose,
        Self::PanelRightOpen,
        Self::PenLine,
        Self::Pilcrow,
        Self::Pipette,
        Self::Play,
        Self::Plus,
        Self::QrCode,
        Self::RadioTower,
        Self::RefreshCw,
        Self::RotateCcw,
        Self::RotateCw,
        Self::Rows3,
        Self::Search,
        Self::Settings2,
        Self::Settings,
        Self::SlidersHorizontal,
        Self::Smartphone,
        Self::Sparkles,
        Self::SquarePen,
        Self::SquareSplitHorizontal,
        Self::SquareSplitVertical,
        Self::SquareTerminal,
        Self::Star,
        Self::Terminal,
        Self::TextWrap,
        Self::Ticket,
        Self::Trash2,
        Self::TrendingDown,
        Self::TrendingUp,
        Self::TriangleAlert,
        Self::Undo2,
        Self::WifiOff,
        Self::Wrench,
        Self::X,
        Self::Zap,
        Self::CheckIndicatorBold,
        Self::CheckIndicator,
        Self::IndeterminateBold,
        Self::XBold,
    ];

    /// Asset path served by [`crate::Assets`].
    pub const fn path(self) -> &'static str {
        match self {
            Self::ArchiveX => "icons/lucide/archive-x.svg",
            Self::Archive => "icons/lucide/archive.svg",
            Self::ArrowDown => "icons/lucide/arrow-down.svg",
            Self::ArrowLeft => "icons/lucide/arrow-left.svg",
            Self::ArrowRight => "icons/lucide/arrow-right.svg",
            Self::ArrowUpDown => "icons/lucide/arrow-up-down.svg",
            Self::ArrowUp => "icons/lucide/arrow-up.svg",
            Self::Bot => "icons/lucide/bot.svg",
            Self::Bug => "icons/lucide/bug.svg",
            Self::Camera => "icons/lucide/camera.svg",
            Self::ChartNoAxesColumn => "icons/lucide/chart-no-axes-column.svg",
            Self::Check => "icons/lucide/check.svg",
            Self::ChevronDown => "icons/lucide/chevron-down.svg",
            Self::ChevronLeft => "icons/lucide/chevron-left.svg",
            Self::ChevronRight => "icons/lucide/chevron-right.svg",
            Self::ChevronUp => "icons/lucide/chevron-up.svg",
            Self::ChevronsLeftRightEllipsis => "icons/lucide/chevrons-left-right-ellipsis.svg",
            Self::ChevronsUpDown => "icons/lucide/chevrons-up-down.svg",
            Self::CircleAlert => "icons/lucide/circle-alert.svg",
            Self::CircleArrowUp => "icons/lucide/circle-arrow-up.svg",
            Self::CircleCheck => "icons/lucide/circle-check.svg",
            Self::CircleDashed => "icons/lucide/circle-dashed.svg",
            Self::CircleX => "icons/lucide/circle-x.svg",
            Self::ClipboardList => "icons/lucide/clipboard-list.svg",
            Self::CloudUpload => "icons/lucide/cloud-upload.svg",
            Self::Cloud => "icons/lucide/cloud.svg",
            Self::CodeXml => "icons/lucide/code-xml.svg",
            Self::Columns2 => "icons/lucide/columns-2.svg",
            Self::Container => "icons/lucide/container.svg",
            Self::Copy => "icons/lucide/copy.svg",
            Self::CornerLeftUp => "icons/lucide/corner-left-up.svg",
            Self::Download => "icons/lucide/download.svg",
            Self::Earth => "icons/lucide/earth.svg",
            Self::EllipsisVertical => "icons/lucide/ellipsis-vertical.svg",
            Self::Ellipsis => "icons/lucide/ellipsis.svg",
            Self::ExternalLink => "icons/lucide/external-link.svg",
            Self::EyeOff => "icons/lucide/eye-off.svg",
            Self::Eye => "icons/lucide/eye.svg",
            Self::FileBraces => "icons/lucide/file-braces.svg",
            Self::FileDiff => "icons/lucide/file-diff.svg",
            Self::File => "icons/lucide/file.svg",
            Self::Files => "icons/lucide/files.svg",
            Self::FlaskConical => "icons/lucide/flask-conical.svg",
            Self::FolderClosed => "icons/lucide/folder-closed.svg",
            Self::FolderGit2 => "icons/lucide/folder-git-2.svg",
            Self::FolderGit => "icons/lucide/folder-git.svg",
            Self::FolderOpen => "icons/lucide/folder-open.svg",
            Self::FolderPlus => "icons/lucide/folder-plus.svg",
            Self::FolderTree => "icons/lucide/folder-tree.svg",
            Self::Folder => "icons/lucide/folder.svg",
            Self::Frame => "icons/lucide/frame.svg",
            Self::Gauge => "icons/lucide/gauge.svg",
            Self::GitBranchPlus => "icons/lucide/git-branch-plus.svg",
            Self::GitBranch => "icons/lucide/git-branch.svg",
            Self::GitCommitHorizontal => "icons/lucide/git-commit-horizontal.svg",
            Self::GitPullRequest => "icons/lucide/git-pull-request.svg",
            Self::Globe => "icons/lucide/globe.svg",
            Self::Hammer => "icons/lucide/hammer.svg",
            Self::Info => "icons/lucide/info.svg",
            Self::Keyboard => "icons/lucide/keyboard.svg",
            Self::Link2 => "icons/lucide/link-2.svg",
            Self::Link => "icons/lucide/link.svg",
            Self::ListChecks => "icons/lucide/list-checks.svg",
            Self::ListTodo => "icons/lucide/list-todo.svg",
            Self::LoaderCircle => "icons/lucide/loader-circle.svg",
            Self::Loader => "icons/lucide/loader.svg",
            Self::Lock => "icons/lucide/lock.svg",
            Self::LogIn => "icons/lucide/log-in.svg",
            Self::Maximize2 => "icons/lucide/maximize-2.svg",
            Self::MessageCircle => "icons/lucide/message-circle.svg",
            Self::MessageSquareDashed => "icons/lucide/message-square-dashed.svg",
            Self::MessageSquare => "icons/lucide/message-square.svg",
            Self::Minimize2 => "icons/lucide/minimize-2.svg",
            Self::Minus => "icons/lucide/minus.svg",
            Self::Monitor => "icons/lucide/monitor.svg",
            Self::MousePointer2 => "icons/lucide/mouse-pointer-2.svg",
            Self::MousePointerClick => "icons/lucide/mouse-pointer-click.svg",
            Self::Paintbrush => "icons/lucide/paintbrush.svg",
            Self::PanelBottomClose => "icons/lucide/panel-bottom-close.svg",
            Self::PanelBottomOpen => "icons/lucide/panel-bottom-open.svg",
            Self::PanelLeftClose => "icons/lucide/panel-left-close.svg",
            Self::PanelLeftOpen => "icons/lucide/panel-left-open.svg",
            Self::PanelRightClose => "icons/lucide/panel-right-close.svg",
            Self::PanelRightOpen => "icons/lucide/panel-right-open.svg",
            Self::PenLine => "icons/lucide/pen-line.svg",
            Self::Pilcrow => "icons/lucide/pilcrow.svg",
            Self::Pipette => "icons/lucide/pipette.svg",
            Self::Play => "icons/lucide/play.svg",
            Self::Plus => "icons/lucide/plus.svg",
            Self::QrCode => "icons/lucide/qr-code.svg",
            Self::RadioTower => "icons/lucide/radio-tower.svg",
            Self::RefreshCw => "icons/lucide/refresh-cw.svg",
            Self::RotateCcw => "icons/lucide/rotate-ccw.svg",
            Self::RotateCw => "icons/lucide/rotate-cw.svg",
            Self::Rows3 => "icons/lucide/rows-3.svg",
            Self::Search => "icons/lucide/search.svg",
            Self::Settings2 => "icons/lucide/settings-2.svg",
            Self::Settings => "icons/lucide/settings.svg",
            Self::SlidersHorizontal => "icons/lucide/sliders-horizontal.svg",
            Self::Smartphone => "icons/lucide/smartphone.svg",
            Self::Sparkles => "icons/lucide/sparkles.svg",
            Self::SquarePen => "icons/lucide/square-pen.svg",
            Self::SquareSplitHorizontal => "icons/lucide/square-split-horizontal.svg",
            Self::SquareSplitVertical => "icons/lucide/square-split-vertical.svg",
            Self::SquareTerminal => "icons/lucide/square-terminal.svg",
            Self::Star => "icons/lucide/star.svg",
            Self::Terminal => "icons/lucide/terminal.svg",
            Self::TextWrap => "icons/lucide/text-wrap.svg",
            Self::Ticket => "icons/lucide/ticket.svg",
            Self::Trash2 => "icons/lucide/trash-2.svg",
            Self::TrendingDown => "icons/lucide/trending-down.svg",
            Self::TrendingUp => "icons/lucide/trending-up.svg",
            Self::TriangleAlert => "icons/lucide/triangle-alert.svg",
            Self::Undo2 => "icons/lucide/undo-2.svg",
            Self::WifiOff => "icons/lucide/wifi-off.svg",
            Self::Wrench => "icons/lucide/wrench.svg",
            Self::X => "icons/lucide/x.svg",
            Self::Zap => "icons/lucide/zap.svg",
            Self::CheckIndicatorBold => "icons/ui/check-indicator-bold.svg",
            Self::CheckIndicator => "icons/ui/check-indicator.svg",
            Self::IndeterminateBold => "icons/ui/indeterminate-bold.svg",
            Self::XBold => "icons/ui/x-bold.svg",
        }
    }
}

/// Multi-color brand, provider and editor logos (`Icons.tsx`, `JetBrainsIcons.tsx`).
/// Render with [`crate::logo`], which picks the light or dark file.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Logo {
    /// `ACPRegistryIcon`
    ACPRegistryIcon,
    /// `AntigravityIcon`
    AntigravityIcon,
    /// `AquaIcon`
    AquaIcon,
    /// `AzureDevOpsIcon`
    AzureDevOpsIcon,
    /// `BitbucketIcon`
    BitbucketIcon,
    /// `CLionIcon`
    CLionIcon,
    /// `ClaudeAI`
    ClaudeAI,
    /// `CursorIcon`
    CursorIcon,
    /// `DataGripIcon`
    DataGripIcon,
    /// `DataSpellIcon`
    DataSpellIcon,
    /// `Gemini`
    Gemini,
    /// `GitHubIcon`
    GitHubIcon,
    /// `GitIcon`
    GitIcon,
    /// `GitLabIcon`
    GitLabIcon,
    /// `GithubCopilotIcon`
    GithubCopilotIcon,
    /// `GoLandIcon`
    GoLandIcon,
    /// `GrokIcon`
    GrokIcon,
    /// `IntelliJIdeaIcon`
    IntelliJIdeaIcon,
    /// `JujutsuIcon`
    JujutsuIcon,
    /// `KiroIcon`
    KiroIcon,
    /// `OpenAI`
    OpenAI,
    /// `OpenCodeIcon`
    OpenCodeIcon,
    /// `PhpStormIcon`
    PhpStormIcon,
    /// `PiAgentIcon`
    PiAgentIcon,
    /// `PyCharmIcon`
    PyCharmIcon,
    /// `RiderIcon`
    RiderIcon,
    /// `RubyMineIcon`
    RubyMineIcon,
    /// `RustRoverIcon`
    RustRoverIcon,
    /// `TraeIcon`
    TraeIcon,
    /// `VSCodium`
    VSCodium,
    /// `VisualStudioCode`
    VisualStudioCode,
    /// `VisualStudioCodeInsiders`
    VisualStudioCodeInsiders,
    /// `WebStormIcon`
    WebStormIcon,
    /// `Zed`
    Zed,
}

impl Logo {
    /// Every logo, in file-name order.
    pub const ALL: &[Logo] = &[
        Self::ACPRegistryIcon,
        Self::AntigravityIcon,
        Self::AquaIcon,
        Self::AzureDevOpsIcon,
        Self::BitbucketIcon,
        Self::CLionIcon,
        Self::ClaudeAI,
        Self::CursorIcon,
        Self::DataGripIcon,
        Self::DataSpellIcon,
        Self::Gemini,
        Self::GitHubIcon,
        Self::GitIcon,
        Self::GitLabIcon,
        Self::GithubCopilotIcon,
        Self::GoLandIcon,
        Self::GrokIcon,
        Self::IntelliJIdeaIcon,
        Self::JujutsuIcon,
        Self::KiroIcon,
        Self::OpenAI,
        Self::OpenCodeIcon,
        Self::PhpStormIcon,
        Self::PiAgentIcon,
        Self::PyCharmIcon,
        Self::RiderIcon,
        Self::RubyMineIcon,
        Self::RustRoverIcon,
        Self::TraeIcon,
        Self::VSCodium,
        Self::VisualStudioCode,
        Self::VisualStudioCodeInsiders,
        Self::WebStormIcon,
        Self::Zed,
    ];

    /// Asset path for the given appearance.
    pub const fn path(self, dark: bool) -> &'static str {
        match self {
            Self::ACPRegistryIcon => {
                if dark {
                    "icons/logos/ACPRegistryIcon.dark.svg"
                } else {
                    "icons/logos/ACPRegistryIcon.light.svg"
                }
            }
            Self::AntigravityIcon => "icons/logos/AntigravityIcon.svg",
            Self::AquaIcon => "icons/logos/AquaIcon.svg",
            Self::AzureDevOpsIcon => "icons/logos/AzureDevOpsIcon.svg",
            Self::BitbucketIcon => "icons/logos/BitbucketIcon.svg",
            Self::CLionIcon => "icons/logos/CLionIcon.svg",
            Self::ClaudeAI => "icons/logos/ClaudeAI.svg",
            Self::CursorIcon => {
                if dark {
                    "icons/logos/CursorIcon.dark.svg"
                } else {
                    "icons/logos/CursorIcon.light.svg"
                }
            }
            Self::DataGripIcon => "icons/logos/DataGripIcon.svg",
            Self::DataSpellIcon => "icons/logos/DataSpellIcon.svg",
            Self::Gemini => "icons/logos/Gemini.svg",
            Self::GitHubIcon => "icons/logos/GitHubIcon.svg",
            Self::GitIcon => "icons/logos/GitIcon.svg",
            Self::GitLabIcon => "icons/logos/GitLabIcon.svg",
            Self::GithubCopilotIcon => {
                if dark {
                    "icons/logos/GithubCopilotIcon.dark.svg"
                } else {
                    "icons/logos/GithubCopilotIcon.light.svg"
                }
            }
            Self::GoLandIcon => "icons/logos/GoLandIcon.svg",
            Self::GrokIcon => {
                if dark {
                    "icons/logos/GrokIcon.dark.svg"
                } else {
                    "icons/logos/GrokIcon.light.svg"
                }
            }
            Self::IntelliJIdeaIcon => "icons/logos/IntelliJIdeaIcon.svg",
            Self::JujutsuIcon => "icons/logos/JujutsuIcon.svg",
            Self::KiroIcon => "icons/logos/KiroIcon.svg",
            Self::OpenAI => {
                if dark {
                    "icons/logos/OpenAI.dark.svg"
                } else {
                    "icons/logos/OpenAI.light.svg"
                }
            }
            Self::OpenCodeIcon => {
                if dark {
                    "icons/logos/OpenCodeIcon.dark.svg"
                } else {
                    "icons/logos/OpenCodeIcon.light.svg"
                }
            }
            Self::PhpStormIcon => "icons/logos/PhpStormIcon.svg",
            Self::PiAgentIcon => "icons/logos/PiAgentIcon.svg",
            Self::PyCharmIcon => "icons/logos/PyCharmIcon.svg",
            Self::RiderIcon => "icons/logos/RiderIcon.svg",
            Self::RubyMineIcon => "icons/logos/RubyMineIcon.svg",
            Self::RustRoverIcon => "icons/logos/RustRoverIcon.svg",
            Self::TraeIcon => "icons/logos/TraeIcon.svg",
            Self::VSCodium => "icons/logos/VSCodium.svg",
            Self::VisualStudioCode => "icons/logos/VisualStudioCode.svg",
            Self::VisualStudioCodeInsiders => "icons/logos/VisualStudioCodeInsiders.svg",
            Self::WebStormIcon => "icons/logos/WebStormIcon.svg",
            Self::Zed => "icons/logos/Zed.svg",
        }
    }
}

/// Pierre token by lowercase file name. Sorted for binary search.
pub(crate) const FILE_NAME_TOKENS: &[(&str, &str)] = &[
    (".babelrc", "babel"),
    (".babelrc.json", "babel"),
    (".bash_profile", "bash"),
    (".bashrc", "bash"),
    (".browserslistrc", "browserslist"),
    (".dockerignore", "docker"),
    (".eslintignore", "eslint"),
    (".eslintrc", "eslint"),
    (".eslintrc.cjs", "eslint"),
    (".eslintrc.js", "eslint"),
    (".eslintrc.json", "eslint"),
    (".eslintrc.yaml", "eslint"),
    (".eslintrc.yml", "eslint"),
    (".gitattributes", "git"),
    (".gitignore", "git"),
    (".gitkeep", "git"),
    (".gitmodules", "git"),
    (".oxlintrc.json", "oxc"),
    (".postcssrc", "postcss"),
    (".postcssrc.json", "postcss"),
    (".postcssrc.yaml", "postcss"),
    (".postcssrc.yml", "postcss"),
    (".prettierignore", "prettier"),
    (".prettierrc", "prettier"),
    (".prettierrc.cjs", "prettier"),
    (".prettierrc.js", "prettier"),
    (".prettierrc.json", "prettier"),
    (".prettierrc.mjs", "prettier"),
    (".prettierrc.toml", "prettier"),
    (".prettierrc.yaml", "prettier"),
    (".prettierrc.yml", "prettier"),
    (".stylelintignore", "stylelint"),
    (".stylelintrc", "stylelint"),
    (".stylelintrc.cjs", "stylelint"),
    (".stylelintrc.js", "stylelint"),
    (".stylelintrc.json", "stylelint"),
    (".stylelintrc.mjs", "stylelint"),
    (".stylelintrc.yaml", "stylelint"),
    (".stylelintrc.yml", "stylelint"),
    (".terraform.lock.hcl", "terraform"),
    (".zprofile", "bash"),
    (".zshenv", "bash"),
    (".zshrc", "bash"),
    ("babel.config.cjs", "babel"),
    ("babel.config.js", "babel"),
    ("babel.config.json", "babel"),
    ("babel.config.mjs", "babel"),
    ("biome.json", "biome"),
    ("biome.jsonc", "biome"),
    ("bootstrap.bundle.js", "bootstrap"),
    ("bootstrap.bundle.min.js", "bootstrap"),
    ("bootstrap.css", "bootstrap"),
    ("bootstrap.js", "bootstrap"),
    ("bootstrap.min.css", "bootstrap"),
    ("bootstrap.min.js", "bootstrap"),
    ("bun.lock", "bun"),
    ("bun.lockb", "bun"),
    ("bunfig.toml", "bun"),
    ("claude.md", "claude"),
    ("compose.yaml", "docker"),
    ("compose.yml", "docker"),
    ("docker-compose.override.yml", "docker"),
    ("docker-compose.yaml", "docker"),
    ("docker-compose.yml", "docker"),
    ("dockerfile", "docker"),
    ("eslint.config.cjs", "eslint"),
    ("eslint.config.js", "eslint"),
    ("eslint.config.mjs", "eslint"),
    ("eslint.config.mts", "eslint"),
    ("eslint.config.ts", "eslint"),
    ("gemfile", "ruby"),
    ("next.config.js", "nextjs"),
    ("next.config.mjs", "nextjs"),
    ("next.config.mts", "nextjs"),
    ("next.config.ts", "nextjs"),
    ("postcss.config.cjs", "postcss"),
    ("postcss.config.js", "postcss"),
    ("postcss.config.mjs", "postcss"),
    ("postcss.config.ts", "postcss"),
    ("prettier.config.cjs", "prettier"),
    ("prettier.config.js", "prettier"),
    ("prettier.config.mjs", "prettier"),
    ("rakefile", "ruby"),
    ("readme.md", "markdown"),
    ("stylelint.config.cjs", "stylelint"),
    ("stylelint.config.js", "stylelint"),
    ("stylelint.config.mjs", "stylelint"),
    ("svgo.config.cjs", "svgo"),
    ("svgo.config.js", "svgo"),
    ("svgo.config.mjs", "svgo"),
    ("svgo.config.ts", "svgo"),
    ("tailwind.config.cjs", "tailwind"),
    ("tailwind.config.js", "tailwind"),
    ("tailwind.config.mjs", "tailwind"),
    ("tailwind.config.ts", "tailwind"),
    ("vite.config.js", "vite"),
    ("vite.config.mjs", "vite"),
    ("vite.config.mts", "vite"),
    ("vite.config.ts", "vite"),
    ("webpack.config.babel.js", "webpack"),
    ("webpack.config.cjs", "webpack"),
    ("webpack.config.js", "webpack"),
    ("webpack.config.mjs", "webpack"),
    ("webpack.config.ts", "webpack"),
];

/// Pierre token by lowercase extension (`d.ts`, `ts`). Sorted for binary search.
pub(crate) const EXTENSION_TOKENS: &[(&str, &str)] = &[
    ("7z", "zip"),
    ("AUTHORS", "text"),
    ("CHANGELOG", "text"),
    ("CONTRIBUTORS", "text"),
    ("LICENSE", "text"),
    ("astro", "astro"),
    ("avif", "image"),
    ("bash", "bash"),
    ("bmp", "image"),
    ("bz2", "zip"),
    ("c", "c"),
    ("cc", "cpp"),
    ("cfg", "text"),
    ("cjs", "javascript"),
    ("code-workspace", "vscode"),
    ("conf", "text"),
    ("cpp", "cpp"),
    ("csh", "bash"),
    ("css", "css"),
    ("csv", "table"),
    ("cts", "typescript"),
    ("cxx", "cpp"),
    ("db", "database"),
    ("editorconfig", "text"),
    ("env", "text"),
    ("env.development", "text"),
    ("env.local", "text"),
    ("env.production", "text"),
    ("eot", "font"),
    ("erb", "ruby"),
    ("fish", "bash"),
    ("gemspec", "ruby"),
    ("gif", "image"),
    ("go", "go"),
    ("gql", "graphql"),
    ("graphql", "graphql"),
    ("gz", "zip"),
    ("h", "c"),
    ("hh", "cpp"),
    ("hpp", "cpp"),
    ("htm", "html"),
    ("html", "html"),
    ("hxx", "cpp"),
    ("icns", "image"),
    ("ico", "image"),
    ("ini", "text"),
    ("inl", "cpp"),
    ("jar", "zip"),
    ("jpeg", "image"),
    ("jpg", "image"),
    ("js", "javascript"),
    ("json", "json"),
    ("json5", "json"),
    ("jsonc", "json"),
    ("jsonl", "json"),
    ("jsx", "javascript"),
    ("ksh", "bash"),
    ("less", "css"),
    ("log", "text"),
    ("markdown", "markdown"),
    ("mcp", "mcp"),
    ("md", "markdown"),
    ("mdx", "markdown"),
    ("mdx.tsx", "markdown"),
    ("mjs", "javascript"),
    ("mm", "cpp"),
    ("mts", "typescript"),
    ("ods", "table"),
    ("otf", "font"),
    ("png", "image"),
    ("postcss", "css"),
    ("py", "python"),
    ("pyi", "python"),
    ("pyw", "python"),
    ("pyx", "python"),
    ("rake", "ruby"),
    ("rar", "zip"),
    ("rb", "ruby"),
    ("rs", "rust"),
    ("rst", "text"),
    ("rtf", "text"),
    ("sass", "css"),
    ("scss", "css"),
    ("sh", "bash"),
    ("sql", "database"),
    ("sqlite", "database"),
    ("sqlite3", "database"),
    ("styl", "css"),
    ("svelte", "svelte"),
    ("svg", "svg"),
    ("swift", "swift"),
    ("tar", "zip"),
    ("tf", "terraform"),
    ("tfstate", "terraform"),
    ("tfvars", "terraform"),
    ("tgz", "zip"),
    ("tif", "image"),
    ("tiff", "image"),
    ("ts", "typescript"),
    ("tsv", "table"),
    ("tsx", "typescript"),
    ("ttf", "font"),
    ("txt", "text"),
    ("vue", "vue"),
    ("war", "zip"),
    ("wasm", "wasm"),
    ("wast", "wasm"),
    ("wat", "wasm"),
    ("webp", "image"),
    ("woff", "font"),
    ("woff2", "font"),
    ("xhtml", "html"),
    ("xls", "table"),
    ("xlsx", "table"),
    ("xz", "zip"),
    ("yaml", "yml"),
    ("yml", "yml"),
    ("zig", "zig"),
    ("zip", "zip"),
    ("zsh", "bash"),
];

/// Extensions the complete set re-maps. Sorted for binary search.
pub(crate) const COMPLETE_EXTENSION_OVERRIDES: &[(&str, &str)] = &[
    ("jsx", "react"),
    ("sass", "sass"),
    ("scss", "sass"),
    ("tsx", "react"),
];

/// `(token, light, dark)` icon color. Tokens missing here use the muted tree color.
pub(crate) const TOKEN_COLORS: &[(&str, Hsla, Hsla)] = &[
    ("astro", hex(0xA631BEFF), hex(0xD568EAFF)),
    ("babel", hex(0xD5A910FF), hex(0xFFD452FF)),
    ("bash", hex(0x199F43FF), hex(0x5ECC71FF)),
    ("biome", hex(0x1A85D4FF), hex(0x69B1FFFF)),
    ("bootstrap", hex(0x693ACFFF), hex(0x9D6AFBFF)),
    ("browserslist", hex(0xD5A910FF), hex(0xFFD452FF)),
    ("bun", hex(0x594C5BFF), hex(0x79697BFF)),
    ("c", hex(0x1A85D4FF), hex(0x69B1FFFF)),
    ("claude", hex(0xD47628FF), hex(0xFFA359FF)),
    ("cpp", hex(0x1A85D4FF), hex(0x69B1FFFF)),
    ("css", hex(0x693ACFFF), hex(0x9D6AFBFF)),
    ("database", hex(0xA631BEFF), hex(0xD568EAFF)),
    ("default", hex(0x84848AFF), hex(0xADADB1FF)),
    ("docker", hex(0x1A85D4FF), hex(0x69B1FFFF)),
    ("eslint", hex(0x693ACFFF), hex(0x9D6AFBFF)),
    ("git", hex(0xFF8C5BFF), hex(0xD5512FFF)),
    ("go", hex(0x1CA1C7FF), hex(0x68CDF2FF)),
    ("graphql", hex(0xD32A61FF), hex(0xFF678DFF)),
    ("html", hex(0xD47628FF), hex(0xFFA359FF)),
    ("image", hex(0xD32A61FF), hex(0xFF678DFF)),
    ("javascript", hex(0xD5A910FF), hex(0xFFD452FF)),
    ("json", hex(0xD47628FF), hex(0xFFA359FF)),
    ("markdown", hex(0x199F43FF), hex(0x5ECC71FF)),
    ("mcp", hex(0x17A5AFFF), hex(0x64D1DBFF)),
    ("npm", hex(0xD52C36FF), hex(0xFF6762FF)),
    ("oxc", hex(0x1CA1C7FF), hex(0x68CDF2FF)),
    ("postcss", hex(0xD52C36FF), hex(0xFF6762FF)),
    ("prettier", hex(0x17A5AFFF), hex(0x64D1DBFF)),
    ("python", hex(0x1A85D4FF), hex(0x69B1FFFF)),
    ("react", hex(0x1CA1C7FF), hex(0x68CDF2FF)),
    ("ruby", hex(0xD52C36FF), hex(0xFF6762FF)),
    ("rust", hex(0xD47628FF), hex(0xFFA359FF)),
    ("sass", hex(0xD32A61FF), hex(0xFF678DFF)),
    ("svelte", hex(0xD52C36FF), hex(0xFF6762FF)),
    ("svg", hex(0xD47628FF), hex(0xFFA359FF)),
    ("svgo", hex(0x199F43FF), hex(0x5ECC71FF)),
    ("swift", hex(0xD47628FF), hex(0xFFA359FF)),
    ("table", hex(0x17A5AFFF), hex(0x64D1DBFF)),
    ("tailwind", hex(0x1CA1C7FF), hex(0x68CDF2FF)),
    ("terraform", hex(0x693ACFFF), hex(0x9D6AFBFF)),
    ("text", hex(0x84848AFF), hex(0xADADB1FF)),
    ("typescript", hex(0x1A85D4FF), hex(0x69B1FFFF)),
    ("vite", hex(0xA631BEFF), hex(0xD568EAFF)),
    ("vscode", hex(0x1A85D4FF), hex(0x69B1FFFF)),
    ("vue", hex(0x199F43FF), hex(0x5ECC71FF)),
    ("wasm", hex(0x693ACFFF), hex(0x9D6AFBFF)),
    ("webpack", hex(0x1A85D4FF), hex(0x69B1FFFF)),
    ("yml", hex(0xD52C36FF), hex(0xFF6762FF)),
    ("zig", hex(0xD47628FF), hex(0xFFA359FF)),
    ("zip", hex(0xD47628FF), hex(0xFFA359FF)),
];

/// T3 overrides by lowercase file name: `(file name, icon stem, has light/dark files)`.
pub(crate) const T3_FILE_ICONS: &[(&str, &str, bool)] = &[
    ("agents.md", "t3-agents", true),
    ("claude.md", "t3-claude", false),
    ("package.json", "t3-package-json", false),
    ("pnpm-lock.yaml", "t3-pnpm", true),
    ("pnpm-workspace.yaml", "t3-pnpm", true),
    ("readme.md", "t3-readme", false),
    ("tsconfig.json", "t3-tsconfig", false),
];
