#!/usr/bin/env python3
"""Generate t3-ui's token constants from docs/spec/tokens.json.

Usage (from the repo root):
    python3 crates/t3-ui/tools/gen_tokens.py

Writes, and overwrites:
    crates/t3-ui/src/tokens/generated.rs        colors (light + dark), status, terminal,
                                                radius, shadows, type scale
    crates/t3-ui/src/theme/gpui_component.json  gpui-component ThemeSet (spec section 9)

Both outputs are checked in. Re-run after `docs/spec/tokens.json` changes and commit the result.
Python 3 stdlib only.
"""

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
TOKENS = ROOT / "docs/spec/tokens.json"
OUT_RS = ROOT / "crates/t3-ui/src/tokens/generated.rs"
OUT_THEME = ROOT / "crates/t3-ui/src/theme/gpui_component.json"

# colorDerived keys whose generic name would be unclear. Everything else is derived by
# `derived_name`: drop the parenthetical, `/NN` -> `_NN`, `@NN%` -> `_mix_NN`.
DERIVED_RENAMES = {
    "outline (ring/50, every element)": "outline",
    "border-ring/45 (composer focus border)": "ring_45",
    "composer glass bg (card 20% light / 45% dark, srgb)": "composer_glass",
    "codeblock bg (muted 78% + background, srgb)": "codeblock_bg",
    "diff panel viewport (background 94% + card)": "diff_viewport",
    "diff file surface (card 92% + background)": "diff_file_surface",
    "inset highlight white/16 (solid buttons)": "inset_highlight",
    "inset press black/8": "inset_press",
    "group-text before black/6": "group_text_bevel",
    "skeleton highlight (white/64 light, white/4 dark)": "skeleton_highlight",
}
# Bevel colors are mode-specific (light draws below, dark above), so they are emitted
# as `bevel` / `bevel_pressed` from `shadow.edgeBevel` instead.
DERIVED_SKIP = {
    "control top-edge shadow black/4 (light ::before)",
    "control top-edge highlight white/6 (dark ::before)",
    "control top-edge highlight white/2 (dark ::before, outline btn)",
}

STATUS_NAMES = {
    "working (sky)": "working",
    "pending-approval (amber)": "pending_approval",
    "awaiting-input (indigo)": "awaiting_input",
    "error (rose)": "error",
    "plan-ready (violet)": "plan_ready",
    "completed / pr-open (emerald)": "completed",
    "pr-closed (zinc)": "pr_closed",
    "pr-merged (violet)": "pr_merged",
    "terminal-running (teal)": "terminal_running",
}


def snake(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def derived_name(key: str) -> str:
    if key in DERIVED_RENAMES:
        return DERIVED_RENAMES[key]
    base = re.sub(r"\s*\(.*\)$", "", key)
    base = re.sub(r"@(\d+)%", r"_mix_\1", base)
    return snake(base.replace("/", "_"))


def hex_lit(color: str) -> str:
    value = color.lstrip("#").upper()
    if len(value) == 6:
        value += "FF"
    assert len(value) == 8, color
    return f"hex(0x{value})"


def comment_lines(text: str, indent: str) -> str:
    return "".join(f"{indent}/// {line}\n" for line in text.splitlines())


def main() -> None:
    tokens = json.loads(TOKENS.read_text())
    out = []
    w = out.append

    w("// @generated by crates/t3-ui/tools/gen_tokens.py from docs/spec/tokens.json. Do not edit.\n")
    w("// Regenerate: python3 crates/t3-ui/tools/gen_tokens.py\n\n")
    w("use gpui_kit::{BoxShadow, Hsla, Pixels, point, px};\n\n")
    w("use super::hex;\n\n")

    # ---------------------------------------------------------------- Colors
    core_keys = list(tokens["color"]["light"].keys())
    assert core_keys == list(tokens["color"]["dark"].keys())
    derived_keys = [k for k in tokens["colorDerived"]["light"].keys() if k not in DERIVED_SKIP]
    derived_fields = [(derived_name(k), k) for k in derived_keys]
    names = [snake(k) for k in core_keys] + [n for n, _ in derived_fields]
    assert len(names) == len(set(names)), "duplicate color field names"

    scroll = tokens["scrollbar"]
    bevel = tokens["shadow"]["edgeBevel"]
    extra = [
        ("bevel", "Edge bevel line (`::before` box-shadow): drawn below in light, above in dark.",
         bevel["light"]["color"], bevel["dark"]["color"]),
        ("bevel_pressed", "Edge bevel of a pressed outline control (light hides it).",
         "#00000000", bevel["darkOutlinePressed"]["color"]),
        ("scrollbar_thumb", "Native scrollbar thumb (6px, radius 3).",
         scroll["native"]["thumb"]["light"], scroll["native"]["thumb"]["dark"]),
        ("scrollbar_thumb_hover", "Native scrollbar thumb while hovered.",
         scroll["native"]["thumbHover"]["light"], scroll["native"]["thumbHover"]["dark"]),
        ("model_picker_thumb", "Model picker scrollbar thumb (4px, radius 2).",
         scroll["modelPicker"]["thumb"]["light"], scroll["modelPicker"]["thumb"]["dark"]),
        ("model_picker_thumb_hover", "Model picker scrollbar thumb while hovered.",
         scroll["modelPicker"]["thumbHover"]["light"], scroll["modelPicker"]["thumbHover"]["dark"]),
        ("code_scrollbar_thumb", "Code block horizontal scrollbar thumb (7px, rounded).",
         scroll["codeBlockHorizontal"]["thumb"]["light"], scroll["codeBlockHorizontal"]["thumb"]["dark"]),
        ("scroll_area_thumb", "Base UI ScrollArea overlay thumb (`foreground/20`).",
         scroll["scrollArea"]["thumb"]["light"], scroll["scrollArea"]["thumb"]["dark"]),
    ]

    w("/// Every color the UI paints, for one appearance. Read the active set with\n")
    w("/// `cx.colors()` ([`crate::ActiveColors`]); [`LIGHT`] and [`DARK`] are the two sets.\n")
    w("///\n")
    w("/// Alpha colors are not pre-composited: paint them over whatever surface is below.\n")
    w("/// `name_NN` is `name` with its alpha multiplied by NN% (Tailwind `name/NN`).\n")
    w("#[derive(Clone, Copy, Debug, PartialEq)]\n")
    w("#[non_exhaustive]\n")
    w("pub struct Colors {\n")
    w("    /// `true` for [`DARK`].\n")
    w("    pub is_dark: bool,\n")
    for key in core_keys:
        w(f"    /// `--{key}`\n")
        w(f"    pub {snake(key)}: Hsla,\n")
    for name, key in derived_fields:
        w(f"    /// `{key}`\n")
        w(f"    pub {name}: Hsla,\n")
    for name, doc, _, _ in extra:
        w(comment_lines(doc, "    "))
        w(f"    pub {name}: Hsla,\n")
    w("    /// Sidebar thread status and PR pill colors.\n")
    w("    pub status: StatusColors,\n")
    w("    /// xterm palette for the terminal drawer.\n")
    w("    pub terminal: TerminalColors,\n")
    w("}\n\n")

    for mode in ("light", "dark"):
        w(f"/// The {mode} appearance.\n")
        w(f"pub const {mode.upper()}: Colors = Colors {{\n")
        w(f"    is_dark: {'true' if mode == 'dark' else 'false'},\n")
        for key in core_keys:
            w(f"    {snake(key)}: {hex_lit(tokens['color'][mode][key])},\n")
        for name, key in derived_fields:
            w(f"    {name}: {hex_lit(tokens['colorDerived'][mode][key])},\n")
        for name, _, light, dark in extra:
            w(f"    {name}: {hex_lit(light if mode == 'light' else dark)},\n")
        w(f"    status: {mode.upper()}_STATUS,\n")
        w(f"    terminal: {mode.upper()}_TERMINAL,\n")
        w("};\n\n")

    # ---------------------------------------------------------------- Status
    w("/// Text and dot color of one sidebar status.\n")
    w("#[derive(Clone, Copy, Debug, PartialEq)]\n")
    w("pub struct StatusColor {\n    pub text: Hsla,\n    pub dot: Hsla,\n}\n\n")
    w("/// Sidebar thread status and PR pill palette (`Sidebar.logic.ts`, `ThreadStatusIndicators.tsx`).\n")
    w("#[derive(Clone, Copy, Debug, PartialEq)]\n")
    w("#[non_exhaustive]\n")
    w("pub struct StatusColors {\n")
    for key, name in STATUS_NAMES.items():
        w(f"    /// {key}\n    pub {name}: StatusColor,\n")
    w("}\n\n")
    for mode in ("light", "dark"):
        w(f"const {mode.upper()}_STATUS: StatusColors = StatusColors {{\n")
        for key, name in STATUS_NAMES.items():
            entry = tokens["status"][key]
            text = entry[f"{mode}.text"]
            dot = entry.get(f"{mode}.dot", text)
            w(f"    {name}: StatusColor {{ text: {hex_lit(text)}, dot: {hex_lit(dot)} }},\n")
        w("};\n\n")

    # -------------------------------------------------------------- Terminal
    ansi = tokens["terminal"]["ansi"]
    term_keys = list(ansi["light"].keys())
    w("/// xterm colors (`ThreadTerminalDrawer.tsx`). Background and foreground follow the\n")
    w("/// drawer's `background` / `foreground`.\n")
    w("#[derive(Clone, Copy, Debug, PartialEq)]\n")
    w("#[non_exhaustive]\n")
    w("pub struct TerminalColors {\n")
    for key in term_keys:
        w(f"    pub {snake(re.sub(r'([A-Z])', r'_\1', key))}: Hsla,\n")
    w("}\n\n")
    for mode in ("light", "dark"):
        w(f"const {mode.upper()}_TERMINAL: TerminalColors = TerminalColors {{\n")
        for key in term_keys:
            w(f"    {snake(re.sub(r'([A-Z])', r'_\1', key))}: {hex_lit(ansi[mode][key])},\n")
        w("};\n\n")

    # ------------------------------------------------------- Provider accents
    w("/// User-pickable provider accent swatches (`ProviderAccentColorPicker.tsx`).\n")
    w("pub const PROVIDER_ACCENTS: [Hsla; %d] = [\n" % len(tokens["providerAccentSwatches"]))
    for color in tokens["providerAccentSwatches"]:
        w(f"    {hex_lit(color)},\n")
    w("];\n\n")

    # ---------------------------------------------------------------- Radius
    w("/// Corner radii (`index.css:83-89`). `rounded-lg` (10px) is the control default.\n")
    w("pub mod radius {\n    use super::{Pixels, px};\n\n")
    radius_names = {"2xl": "XL2", "3xl": "XL3", "4xl": "XL4", "rounded": "ROUNDED",
                    "composerOuter": "COMPOSER_OUTER", "composerSurface": "COMPOSER_SURFACE"}
    for key, value in tokens["radius"].items():
        name = radius_names.get(key, snake(key).upper())
        w(f"    /// `{key}`\n    pub const {name}: Pixels = px({float(value)});\n")
    w("}\n\n")

    # ---------------------------------------------------------------- Shadows
    def shadow_lit(s: dict, inset: bool = False) -> str:
        return (
            "BoxShadow { "
            f"color: {hex_lit(s['color'])}, "
            f"offset: point(px({float(s.get('x', 0))}), px({float(s['y'])})), "
            f"blur_radius: px({float(s.get('blur', 0))}), "
            f"spread_radius: px({float(s.get('spread', 0))}), "
            f"inset: {'true' if inset else 'false'} }}"
        )

    w("/// Box shadows, exact compiled values (spec section 4.4). Pass with `.shadow(X.to_vec())`.\n")
    w("pub mod shadow {\n    use super::{BoxShadow, hex, point, px};\n\n")
    for key in ("xs/5", "sm/5", "md/5", "lg/5", "sm", "md", "lg"):
        layers = tokens["shadow"][key]
        name = key.replace("/", "_").upper()
        w(f"    /// `shadow-{key}`\n")
        w(f"    pub const {name}: [BoxShadow; {len(layers)}] = [\n")
        for layer in layers:
            w(f"        {shadow_lit(layer)},\n")
        w("    ];\n")
    for mode in ("light", "dark"):
        layers = tokens["shadow"]["buttonPrimary"][mode]
        w(f"    /// Solid button outer shadow, {mode} (`shadow-xs` in `primary/24`).\n")
        w(f"    pub const BUTTON_PRIMARY_{mode.upper()}: [BoxShadow; {len(layers)}] = [\n")
        for layer in layers:
            w(f"        {shadow_lit(layer)},\n")
        w("    ];\n")
    for mode in ("light", "dark"):
        layers = tokens["shadow"]["composerGlass"][mode]
        w(f"    /// Composer glass surface shadow, {mode}.\n")
        w(f"    pub const COMPOSER_{mode.upper()}: [BoxShadow; {len(layers)}] = [\n")
        for layer in layers:
            w(f"        {shadow_lit(layer)},\n")
        w("    ];\n")
    w("}\n\n")

    # ------------------------------------------------------------- Typography
    typo = tokens["typography"]
    w("/// Type scale: `(font size, line height)` in px for each Tailwind `text-*` class.\n")
    w("pub mod text {\n    use super::{Pixels, px};\n\n")
    for key, (size, line) in typo["sizes"].items():
        name = {"2xl": "XL2", "3xl": "XL3"}.get(key, key.upper())
        w(f"    /// `text-{key}`: {size}/{line}\n")
        w(f"    pub const {name}: (Pixels, Pixels) = (px({float(size)}), px({float(line)}));\n")
    w("}\n")

    OUT_RS.parent.mkdir(parents=True, exist_ok=True)
    OUT_RS.write_text("".join(out))
    subprocess.run(["rustfmt", "--edition", "2024", str(OUT_RS)], check=True)

    OUT_THEME.parent.mkdir(parents=True, exist_ok=True)
    OUT_THEME.write_text(json.dumps(tokens["gpuiComponentTheme"], indent=2) + "\n")
    print(f"wrote {OUT_RS.relative_to(ROOT)} and {OUT_THEME.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
