#!/usr/bin/env python3
"""Generate t3-ui's token constants from docs/spec/tokens.json.

Usage (from the repo root, after the spec tools in docs/spec/tools):
    node docs/spec/tools/compile.mjs        # compile the fork's index.css
    T3_LEGACY_FIELDS=... node docs/spec/tools/resolve-css.mjs   # see below
    node docs/spec/tools/tokens.mjs         # docs/spec/tokens.json
    python3 crates/t3-ui/tools/gen_tokens.py

`T3_LEGACY_FIELDS` is the comma-separated list of the previous `Colors` fields, so names other
crates still read keep resolving:
    grep -oE "pub [a-z_0-9]+: Hsla" crates/t3-ui/src/tokens/generated.rs | awk '{print $2}' | tr -d ':' | sort -u | tr '\\n' ,

Writes, and overwrites (both checked in, rustfmt'd):
    crates/t3-ui/src/tokens/generated.rs        colors (root + sidebar scope, light + dark), palette,
                                                status, terminal, radius, shadows, type scale
    crates/t3-ui/src/theme/gpui_component.json  gpui-component ThemeSet
"""

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
TOKENS = ROOT / "docs/spec/tokens.json"
OUT_RS = ROOT / "crates/t3-ui/src/tokens/generated.rs"
OUT_THEME = ROOT / "crates/t3-ui/src/theme/gpui_component.json"

STATUS_NAMES = {
    "working (sky)": "working",
    "pending-approval (amber)": "pending_approval",
    "awaiting-input (indigo)": "awaiting_input",
    "error (rose)": "error",
    "plan-ready (violet)": "plan_ready",
    "completed / pr-open (emerald)": "completed",
    "pr-closed (zinc)": "pr_closed",
    "pr-merged (violet)": "pr_merged",
    "terminal-running (teal)": "terminal_running",
}
SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"]


def snake(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", re.sub(r"([A-Z])", r"_\1", name).lower()).strip("_")


def hex_lit(color: str) -> str:
    value = color.lstrip("#").upper()
    if len(value) == 6:
        value += "FF"
    assert len(value) == 8, color
    return f"hex(0x{value})"


def color_fields(tokens: dict, mode: str) -> dict[str, tuple[str, str]]:
    """field name -> (hex, doc) for one mode, in declaration order: tokens, opacity, legacy."""
    fields: dict[str, tuple[str, str]] = {}
    for name, value in tokens["color"][mode].items():
        if name.startswith("color-"):
            continue  # palette tones: `palette::*`
        fields[snake(name)] = (value, f"`--{name}`")
    for key, value in tokens["colorAlpha"][mode].items():
        field = snake(key.replace("/", "_"))
        if field.startswith("color_") or field in fields:
            continue
        fields[field] = (value, f"Tailwind `{key}` (oklab alpha of the utility color)")
    for name, value in tokens["colorLegacy"][mode].items():
        fields.setdefault(name, (value, "Pre-refresh name kept for existing callers; prefer the token it maps to"))
    return fields


def main() -> None:
    tokens = json.loads(TOKENS.read_text())
    meta = tokens["$meta"]
    out = []
    w = out.append

    w("// @generated by crates/t3-ui/tools/gen_tokens.py from docs/spec/tokens.json. Do not edit.\n")
    w(f"// Source: {meta['source']}\n\n")
    w("use gpui_kit::{BoxShadow, Hsla, Pixels, point, px};\n\n")
    w("use super::hex;\n\n")

    # ---------------------------------------------------------------- Colors
    light = color_fields(tokens, "light")
    dark = color_fields(tokens, "dark")
    names = [n for n in light if n in dark]
    missing = sorted(set(light) ^ set(dark))
    assert not missing, f"fields only in one mode: {missing}"

    w("/// Every color the UI paints, for one appearance and scope. Read the active set with\n")
    w("/// `cx.colors()` ([`crate::ActiveColors`]); inside the sidebar use `cx.sidebar_colors()`.\n")
    w("///\n")
    w("/// Fields are the fork's CSS custom properties (`--muted-foreground` -> `muted_foreground`)\n")
    w("/// and the Tailwind opacity utilities the fork uses (`bg-foreground/8` -> `foreground_8`).\n")
    w("/// Alpha colors are not pre-composited: paint them over whatever surface is below.\n")
    w("#[derive(Clone, Copy, Debug, PartialEq)]\n")
    w("#[non_exhaustive]\n")
    w("pub struct Colors {\n")
    w("    /// `true` for the dark sets.\n")
    w("    pub is_dark: bool,\n")
    for name in names:
        w(f"    /// {light[name][1]}\n")
        w(f"    pub {name}: Hsla,\n")
    w("    /// Sidebar thread status and PR pill colors.\n")
    w("    pub status: StatusColors,\n")
    w("    /// Terminal colors.\n")
    w("    pub terminal: TerminalColors,\n")
    w("}\n\n")

    for mode, fields in (("light", light), ("dark", dark)):
        w(f"/// The {mode} appearance, `<html>` scope.\n")
        w(f"pub const {mode.upper()}: Colors = Colors {{\n")
        w(f"    is_dark: {'true' if mode == 'dark' else 'false'},\n")
        for name in names:
            w(f"    {name}: {hex_lit(fields[name][0])},\n")
        w(f"    status: {mode.upper()}_STATUS,\n")
        w(f"    terminal: {mode.upper()}_TERMINAL,\n")
        w("};\n\n")

    for mode in ("light", "dark"):
        overrides = tokens["colorSidebar"][mode]
        changed = {}
        for name, value in overrides["tokens"].items():
            changed[snake(name)] = value
        for key, value in overrides["alpha"].items():
            changed[snake(key.replace("/", "_"))] = value
        changed.update(overrides["legacy"])
        w(f"/// The {mode} appearance inside `[data-app-sidebar]`, which re-declares some tokens.\n")
        w(f"pub const SIDEBAR_{mode.upper()}: Colors = Colors {{\n")
        for name, value in changed.items():
            if name in light:
                w(f"    {name}: {hex_lit(value)},\n")
        w(f"    ..{mode.upper()}\n")
        w("};\n\n")

    # ---------------------------------------------------------------- Status
    w("/// Text and dot color of one sidebar status.\n")
    w("#[derive(Clone, Copy, Debug, PartialEq)]\n")
    w("pub struct StatusColor {\n    pub text: Hsla,\n    pub dot: Hsla,\n}\n\n")
    w("/// Sidebar thread status and PR pill palette (`Sidebar.logic.ts`, `ThreadStatusIndicators.tsx`).\n")
    w("#[derive(Clone, Copy, Debug, PartialEq)]\n")
    w("#[non_exhaustive]\n")
    w("pub struct StatusColors {\n")
    for key, name in STATUS_NAMES.items():
        w(f"    /// {key}\n    pub {name}: StatusColor,\n")
    w("}\n\n")
    for mode in ("light", "dark"):
        w(f"const {mode.upper()}_STATUS: StatusColors = StatusColors {{\n")
        for key, name in STATUS_NAMES.items():
            entry = tokens["status"][key]
            text = entry[f"{mode}.text"]
            dot = entry.get(f"{mode}.dot", text)
            w(f"    {name}: StatusColor {{ text: {hex_lit(text)}, dot: {hex_lit(dot)} }},\n")
        w("};\n\n")

    # -------------------------------------------------------------- Terminal
    ansi = tokens["terminal"]["ansi"]
    term_keys = list(ansi["light"].keys())
    w("/// Terminal colors. Background and foreground follow `terminal_background` /\n")
    w("/// `terminal_foreground`; cursor and selection come from `--terminal-*`.\n")
    w("#[derive(Clone, Copy, Debug, PartialEq)]\n")
    w("#[non_exhaustive]\n")
    w("pub struct TerminalColors {\n")
    for key in term_keys:
        w(f"    pub {snake(key)}: Hsla,\n")
    w("}\n\n")
    for mode in ("light", "dark"):
        w(f"const {mode.upper()}_TERMINAL: TerminalColors = TerminalColors {{\n")
        for key in term_keys:
            w(f"    {snake(key)}: {hex_lit(ansi[mode][key])},\n")
        w("};\n\n")

    # ---------------------------------------------------------------- Palette
    palette = tokens["palette"]
    w("/// The Tailwind v4 default palette (oklch, converted to sRGB) plus the fork's additions,\n")
    w("/// for components that use palette tones directly: `palette::AMBER.s600`,\n")
    w("/// `palette::SKY.s300.opacity(0.8)` (Tailwind `sky-300/80`).\n")
    w("pub mod palette {\n    use super::{Hsla, hex};\n\n")
    w("    /// One hue's shades, 50 (lightest) to 950 (darkest).\n")
    w("    #[derive(Clone, Copy, Debug, PartialEq)]\n")
    w("    pub struct Shades {\n")
    for s in SHADES:
        w(f"        pub s{s}: Hsla,\n")
    w("    }\n\n")
    for hue, shades in palette.items():
        w(f"    /// Tailwind `{hue}-*`.\n")
        w(f"    pub const {hue.upper()}: Shades = Shades {{\n")
        for s in SHADES:
            w(f"        s{s}: {hex_lit(shades[s])},\n")
        w("    };\n")
        for s, value in shades.items():
            if s not in SHADES:
                w(f"    /// `{hue}-{s}` (fork addition).\n")
                w(f"    pub const {hue.upper()}_{s}: Hsla = {hex_lit(value)};\n")
    w("}\n\n")

    # ---------------------------------------------------------------- Radius
    w("/// Corner radii. `--radius` is 10px; controls (buttons, inputs, toggles) use\n")
    w("/// `--control-radius`, 8px.\n")
    w("pub mod radius {\n    use super::{Pixels, px};\n\n")
    radius_names = {"2xl": "XL2", "3xl": "XL3", "base": "BASE"}
    for key, value in tokens["radius"].items():
        name = radius_names.get(key, snake(key).upper())
        w(f"    /// `{key}`\n    pub const {name}: Pixels = px({float(value)});\n")
    w("}\n\n")

    # ---------------------------------------------------------------- Shadows
    def shadow_lit(s: dict, inset: bool = False) -> str:
        return (
            "BoxShadow { "
            f"color: {hex_lit(s['color'])}, "
            f"offset: point(px({float(s.get('x', 0))}), px({float(s['y'])})), "
            f"blur_radius: px({float(s.get('blur', 0))}), "
            f"spread_radius: px({float(s.get('spread', 0))}), "
            f"inset: {'true' if inset else 'false'} }}"
        )

    def shadow_const(name: str, doc: str, layers: list) -> None:
        w(f"    /// {doc}\n")
        w(f"    pub const {name}: [BoxShadow; {len(layers)}] = [\n")
        for layer in layers:
            w(f"        {shadow_lit(layer)},\n")
        w("    ];\n")

    shadows = tokens["shadow"]
    w("/// Box shadows, exact compiled values. Pass with `.shadow(X.to_vec())`.\n")
    w("pub mod shadow {\n    use super::{BoxShadow, hex, point, px};\n\n")
    for key in ("xs/5", "sm/5", "md/5", "lg/5", "sm", "md", "lg"):
        shadow_const(key.replace("/", "_").upper(), f"`shadow-{key}`", shadows[key])
    for mode in ("light", "dark"):
        shadow_const(f"BUTTON_PRIMARY_{mode.upper()}", f"Solid button outer shadow, {mode} (`shadow-xs` in `primary/24`).", shadows["buttonPrimary"][mode])
        shadow_const(f"COMPOSER_{mode.upper()}", f"`--shadow-composer{'-dark' if mode == 'dark' else ''}`.", shadows["composer"][mode])
        shadow_const(f"DIALOG_GLASS_{mode.upper()}", f"`dialog-glass` outer shadow, {mode}.", shadows["dialogGlass"][mode])
    w("}\n\n")

    # ------------------------------------------------------------- Typography
    w("/// Type scale: `(font size, line height)` in px for each Tailwind `text-*` class.\n")
    w("pub mod text {\n    use super::{Pixels, px};\n\n")
    for key, (size, line) in tokens["typography"]["sizes"].items():
        m = re.match(r"^(\d)(xl|xs)$", key)
        name = f"{m.group(2).upper()}{m.group(1)}" if m else key.upper()
        w(f"    /// `text-{key}`: {size}/{line}\n")
        w(f"    pub const {name}: (Pixels, Pixels) = (px({float(size)}), px({float(line)}));\n")
    w("}\n")

    OUT_RS.parent.mkdir(parents=True, exist_ok=True)
    OUT_RS.write_text("".join(out))
    subprocess.run(["rustfmt", "--edition", "2024", str(OUT_RS)], check=True)

    OUT_THEME.parent.mkdir(parents=True, exist_ok=True)
    OUT_THEME.write_text(json.dumps(tokens["gpuiComponentTheme"], indent=2) + "\n")
    print(f"wrote {OUT_RS.relative_to(ROOT)} ({len(names)} color fields) and {OUT_THEME.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
