#!/usr/bin/env python3
"""Generate t3-ui's typed icon tables from the exported SVGs in assets/icons.

Usage (from the repo root), after running the exporters:
    node docs/spec/tools/export-icons.mjs ~/L-Projects/t3code-again assets/icons/lucide
    node docs/spec/tools/export-logos.mjs ~/L-Projects/t3code-again assets/icons/logos
    node crates/t3-ui/tools/export-file-icons.mjs ~/L-Projects/t3code-again assets/icons/files
    python3 crates/t3-ui/tools/gen_icons.py

Writes crates/t3-ui/src/icon/generated.rs (checked in):
    IconName   every lucide icon the web UI imports, plus the hand-drawn indicators in
               assets/icons/ui; single-color, rendered with `svg()`.
    Logo       brand/provider/editor logos; multi-color, rendered with `img()`.
    file icon  tables for `file_icon()`: Pierre tokens by file name / extension, token colors.
"""

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ICONS = ROOT / "assets/icons"
OUT = ROOT / "crates/t3-ui/src/icon/generated.rs"


def camel(stem: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[-_.\s]+", stem) if part)


def rust_str(value: str) -> str:
    return json.dumps(value)


def hex_lit(color: str) -> str:
    return f"hex(0x{color.lstrip('#').upper()}FF)"


def main() -> None:
    out = []
    w = out.append
    w("// @generated by crates/t3-ui/tools/gen_icons.py from assets/icons. Do not edit.\n")
    w("// Regenerate: python3 crates/t3-ui/tools/gen_icons.py\n\n")
    w("use gpui_kit::Hsla;\n\nuse crate::tokens::hex;\n\n")

    # ------------------------------------------------------------- IconName
    manifest = json.loads((ICONS / "lucide/manifest.json").read_text())
    aliases: dict[str, list[str]] = {}
    for import_name, entry in manifest.items():
        aliases.setdefault(entry["file"], []).append(import_name)
    lucide = sorted(p.name for p in (ICONS / "lucide").glob("*.svg"))
    ui = sorted(p.name for p in (ICONS / "ui").glob("*.svg"))

    variants = []
    for file in lucide:
        names = ", ".join(f"`{n}`" for n in sorted(aliases.get(file, [])))
        variants.append((camel(file[:-4]), f"icons/lucide/{file}", f"lucide `{file[:-4]}` ({names})"))
    for file in ui:
        variants.append((camel(file[:-4]), f"icons/ui/{file}", f"hand-drawn `{file[:-4]}`"))
    assert len({v for v, _, _ in variants}) == len(variants), "duplicate icon variant"

    w("/// Single-color UI icons. Lucide icons keep their 24px grid and stroke 2 (scaled with the\n")
    w("/// icon size, like lucide without `absoluteStrokeWidth`). Doc comments list the\n")
    w("/// `lucide-react` import names used by the web UI.\n")
    w("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n")
    w("pub enum IconName {\n")
    for variant, _, doc in variants:
        w(f"    /// {doc}\n    {variant},\n")
    w("}\n\n")
    w("impl IconName {\n")
    w("    /// Asset path served by [`crate::Assets`].\n")
    w("    pub const fn path(self) -> &'static str {\n        match self {\n")
    for variant, path, _ in variants:
        w(f"            Self::{variant} => {rust_str(path)},\n")
    w("        }\n    }\n}\n\n")

    # ----------------------------------------------------------------- Logo
    logos: dict[str, dict[str, str]] = {}
    for svg in sorted((ICONS / "logos").glob("*.svg")):
        parts = svg.name[:-4].split(".")
        base = parts[0]
        mode = parts[1] if len(parts) > 1 else "any"
        logos.setdefault(base, {})[mode] = f"icons/logos/{svg.name}"
    w("/// Multi-color brand, provider and editor logos (`Icons.tsx`, `JetBrainsIcons.tsx`).\n")
    w("/// Render with [`crate::logo`], which picks the light or dark file.\n")
    w("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n")
    w("pub enum Logo {\n")
    for base in logos:
        w(f"    /// `{base}`\n    {camel(base)},\n")
    w("}\n\n")
    w("impl Logo {\n")
    w("    /// Asset path for the given appearance.\n")
    w("    pub const fn path(self, dark: bool) -> &'static str {\n        match self {\n")
    for base, files in logos.items():
        if "any" in files:
            w(f"            Self::{camel(base)} => {rust_str(files['any'])},\n")
        else:
            w(f"            Self::{camel(base)} => if dark {{ {rust_str(files['dark'])} }} else {{ {rust_str(files['light'])} }},\n")
    w("        }\n    }\n}\n\n")

    # ----------------------------------------------------------- File icons
    files = json.loads((ICONS / "files/manifest.json").read_text())
    palette = files["palette"]

    def table(name: str, doc: str, mapping: dict[str, str]) -> None:
        w(f"/// {doc} Sorted for binary search.\n")
        w(f"pub(crate) const {name}: &[(&str, &str)] = &[\n")
        for key in sorted(mapping):
            w(f"    ({rust_str(key)}, {rust_str(mapping[key])}),\n")
        w("];\n\n")

    table("FILE_NAME_TOKENS", "Pierre token by lowercase file name.", files["fileNames"])
    table("EXTENSION_TOKENS", "Pierre token by lowercase extension (`d.ts`, `ts`).", files["extensions"])
    table("COMPLETE_EXTENSION_OVERRIDES", "Extensions the complete set re-maps.", files["completeExtensionOverrides"])

    w("/// `(token, light, dark)` icon color. Tokens missing here use the muted tree color.\n")
    w("pub(crate) const TOKEN_COLORS: &[(&str, Hsla, Hsla)] = &[\n")
    for token in sorted(files["tokenColors"]):
        light, dark = palette[files["tokenColors"][token]]
        w(f"    ({rust_str(token)}, {hex_lit(light)}, {hex_lit(dark)}),\n")
    w("];\n\n")

    w("/// T3 overrides by lowercase file name: `(file name, icon stem, has light/dark files)`.\n")
    w("pub(crate) const T3_FILE_ICONS: &[(&str, &str, bool)] = &[\n")
    for name in sorted(files["t3FileNames"]):
        entry = files["t3FileNames"][name]
        w(f"    ({rust_str(name)}, {rust_str(entry['name'])}, {'true' if entry['themed'] else 'false'}),\n")
    w("];\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(out))
    subprocess.run(["rustfmt", "--edition", "2024", str(OUT)], check=True)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(variants)} icons, {len(logos)} logos")


if __name__ == "__main__":
    main()
