// @generated by crates/t3-ui/tools/gen_tokens.py from docs/spec/tokens.json. Do not edit.
// Source: ~/L-Projects/t3UI-refs/t3code-fork @ fe7d3092c (apps/web/src/index.css, components/ui/*, apps/desktop/src/window/DesktopWindow.ts)

use gpui_kit::{BoxShadow, Hsla, Pixels, point, px};

use super::hex;

/// Every color the UI paints, for one appearance and scope. Read the active set with
/// `cx.colors()` ([`crate::ActiveColors`]); inside the sidebar use `cx.sidebar_colors()`.
///
/// Fields are the fork's CSS custom properties (`--muted-foreground` -> `muted_foreground`)
/// and the Tailwind opacity utilities the fork uses (`bg-foreground/8` -> `foreground_8`).
/// Alpha colors are not pre-composited: paint them over whatever surface is below.
#[derive(Clone, Copy, Debug, PartialEq)]
#[non_exhaustive]
pub struct Colors {
    /// `true` for the dark sets.
    pub is_dark: bool,
    /// `--accent`
    pub accent: Hsla,
    /// `--accent-foreground`
    pub accent_foreground: Hsla,
    /// `--app-chrome-background`
    pub app_chrome_background: Hsla,
    /// `--app-scrollbar-thumb`
    pub app_scrollbar_thumb: Hsla,
    /// `--app-scrollbar-thumb-hover`
    pub app_scrollbar_thumb_hover: Hsla,
    /// `--appearance-contrast-target`
    pub appearance_contrast_target: Hsla,
    /// `--background`
    pub background: Hsla,
    /// `--border`
    pub border: Hsla,
    /// `--card`
    pub card: Hsla,
    /// `--card-foreground`
    pub card_foreground: Hsla,
    /// `--code-background`
    pub code_background: Hsla,
    /// `--code-foreground`
    pub code_foreground: Hsla,
    /// `--contrast-accent-foreground`
    pub contrast_accent_foreground: Hsla,
    /// `--contrast-border`
    pub contrast_border: Hsla,
    /// `--contrast-card-foreground`
    pub contrast_card_foreground: Hsla,
    /// `--contrast-foreground`
    pub contrast_foreground: Hsla,
    /// `--contrast-icon-muted`
    pub contrast_icon_muted: Hsla,
    /// `--contrast-input`
    pub contrast_input: Hsla,
    /// `--contrast-message-foreground`
    pub contrast_message_foreground: Hsla,
    /// `--contrast-muted-foreground`
    pub contrast_muted_foreground: Hsla,
    /// `--contrast-placeholder`
    pub contrast_placeholder: Hsla,
    /// `--contrast-popover-foreground`
    pub contrast_popover_foreground: Hsla,
    /// `--contrast-secondary-foreground`
    pub contrast_secondary_foreground: Hsla,
    /// `--contrast-secondary-label`
    pub contrast_secondary_label: Hsla,
    /// `--contrast-sidebar-border`
    pub contrast_sidebar_border: Hsla,
    /// `--contrast-sidebar-foreground`
    pub contrast_sidebar_foreground: Hsla,
    /// `--contrast-sidebar-muted-foreground`
    pub contrast_sidebar_muted_foreground: Hsla,
    /// `--contrast-toolbar-border`
    pub contrast_toolbar_border: Hsla,
    /// `--contrast-toolbar-control-foreground`
    pub contrast_toolbar_control_foreground: Hsla,
    /// `--contrast-toolbar-foreground`
    pub contrast_toolbar_foreground: Hsla,
    /// `--destructive`
    pub destructive: Hsla,
    /// `--destructive-foreground`
    pub destructive_foreground: Hsla,
    /// `--diff-addition`
    pub diff_addition: Hsla,
    /// `--diff-deletion`
    pub diff_deletion: Hsla,
    /// `--error`
    pub error: Hsla,
    /// `--error-foreground`
    pub error_foreground: Hsla,
    /// `--error-surface`
    pub error_surface: Hsla,
    /// `--font-weight-bold`
    pub font_weight_bold: Hsla,
    /// `--font-weight-medium`
    pub font_weight_medium: Hsla,
    /// `--font-weight-normal`
    pub font_weight_normal: Hsla,
    /// `--font-weight-semibold`
    pub font_weight_semibold: Hsla,
    /// `--foreground`
    pub foreground: Hsla,
    /// `--icon-muted`
    pub icon_muted: Hsla,
    /// `--info`
    pub info: Hsla,
    /// `--info-foreground`
    pub info_foreground: Hsla,
    /// `--input`
    pub input: Hsla,
    /// `--message-action`
    pub message_action: Hsla,
    /// `--message-action-foreground`
    pub message_action_foreground: Hsla,
    /// `--message-action-hover`
    pub message_action_hover: Hsla,
    /// `--message-foreground`
    pub message_foreground: Hsla,
    /// `--message-surface`
    pub message_surface: Hsla,
    /// `--muted`
    pub muted: Hsla,
    /// `--muted-foreground`
    pub muted_foreground: Hsla,
    /// `--placeholder`
    pub placeholder: Hsla,
    /// `--popover`
    pub popover: Hsla,
    /// `--popover-foreground`
    pub popover_foreground: Hsla,
    /// `--primary`
    pub primary: Hsla,
    /// `--primary-foreground`
    pub primary_foreground: Hsla,
    /// `--ring`
    pub ring: Hsla,
    /// `--secondary`
    pub secondary: Hsla,
    /// `--secondary-foreground`
    pub secondary_foreground: Hsla,
    /// `--secondary-label`
    pub secondary_label: Hsla,
    /// `--sidebar`
    pub sidebar: Hsla,
    /// `--sidebar-border`
    pub sidebar_border: Hsla,
    /// `--sidebar-control-surface`
    pub sidebar_control_surface: Hsla,
    /// `--sidebar-foreground`
    pub sidebar_foreground: Hsla,
    /// `--sidebar-icon-color`
    pub sidebar_icon_color: Hsla,
    /// `--sidebar-muted-foreground`
    pub sidebar_muted_foreground: Hsla,
    /// `--sidebar-row-active`
    pub sidebar_row_active: Hsla,
    /// `--sidebar-row-hover`
    pub sidebar_row_hover: Hsla,
    /// `--sidebar-row-selected`
    pub sidebar_row_selected: Hsla,
    /// `--sidebar-stage-fade`
    pub sidebar_stage_fade: Hsla,
    /// `--stage-art-bottom`
    pub stage_art_bottom: Hsla,
    /// `--stage-art-celeste-highlight`
    pub stage_art_celeste_highlight: Hsla,
    /// `--stage-art-celeste-secondary`
    pub stage_art_celeste_secondary: Hsla,
    /// `--stage-art-grid-line`
    pub stage_art_grid_line: Hsla,
    /// `--stage-art-highlight`
    pub stage_art_highlight: Hsla,
    /// `--stage-art-line`
    pub stage_art_line: Hsla,
    /// `--stage-art-mid`
    pub stage_art_mid: Hsla,
    /// `--stage-art-secondary`
    pub stage_art_secondary: Hsla,
    /// `--stage-art-tertiary`
    pub stage_art_tertiary: Hsla,
    /// `--stage-art-top`
    pub stage_art_top: Hsla,
    /// `--stage-art-violet-highlight`
    pub stage_art_violet_highlight: Hsla,
    /// `--stage-night-base-bottom`
    pub stage_night_base_bottom: Hsla,
    /// `--stage-night-base-mid`
    pub stage_night_base_mid: Hsla,
    /// `--stage-night-base-top`
    pub stage_night_base_top: Hsla,
    /// `--stage-night-bottom`
    pub stage_night_bottom: Hsla,
    /// `--stage-night-glow-highlight`
    pub stage_night_glow_highlight: Hsla,
    /// `--stage-night-glow-secondary`
    pub stage_night_glow_secondary: Hsla,
    /// `--stage-night-highlight`
    pub stage_night_highlight: Hsla,
    /// `--stage-night-line`
    pub stage_night_line: Hsla,
    /// `--stage-night-mid`
    pub stage_night_mid: Hsla,
    /// `--stage-night-secondary`
    pub stage_night_secondary: Hsla,
    /// `--stage-night-sparkle`
    pub stage_night_sparkle: Hsla,
    /// `--stage-night-tertiary`
    pub stage_night_tertiary: Hsla,
    /// `--stage-night-top`
    pub stage_night_top: Hsla,
    /// `--success`
    pub success: Hsla,
    /// `--success-foreground`
    pub success_foreground: Hsla,
    /// `--surface-raised`
    pub surface_raised: Hsla,
    /// `--terminal-background`
    pub terminal_background: Hsla,
    /// `--terminal-cursor`
    pub terminal_cursor: Hsla,
    /// `--terminal-foreground`
    pub terminal_foreground: Hsla,
    /// `--terminal-selection-background`
    pub terminal_selection_background: Hsla,
    /// `--tool-error-icon`
    pub tool_error_icon: Hsla,
    /// `--toolbar-background`
    pub toolbar_background: Hsla,
    /// `--toolbar-border`
    pub toolbar_border: Hsla,
    /// `--toolbar-control`
    pub toolbar_control: Hsla,
    /// `--toolbar-control-foreground`
    pub toolbar_control_foreground: Hsla,
    /// `--toolbar-control-hover`
    pub toolbar_control_hover: Hsla,
    /// `--toolbar-foreground`
    pub toolbar_foreground: Hsla,
    /// `--update`
    pub update: Hsla,
    /// `--update-foreground`
    pub update_foreground: Hsla,
    /// `--update-surface`
    pub update_surface: Hsla,
    /// `--warning`
    pub warning: Hsla,
    /// `--warning-foreground`
    pub warning_foreground: Hsla,
    /// `--warning-surface`
    pub warning_surface: Hsla,
    /// Tailwind `accent/10` (oklab alpha of the utility color)
    pub accent_10: Hsla,
    /// Tailwind `accent/20` (oklab alpha of the utility color)
    pub accent_20: Hsla,
    /// Tailwind `accent/30` (oklab alpha of the utility color)
    pub accent_30: Hsla,
    /// Tailwind `accent/40` (oklab alpha of the utility color)
    pub accent_40: Hsla,
    /// Tailwind `accent/45` (oklab alpha of the utility color)
    pub accent_45: Hsla,
    /// Tailwind `accent/50` (oklab alpha of the utility color)
    pub accent_50: Hsla,
    /// Tailwind `accent/60` (oklab alpha of the utility color)
    pub accent_60: Hsla,
    /// Tailwind `accent/70` (oklab alpha of the utility color)
    pub accent_70: Hsla,
    /// Tailwind `accent/80` (oklab alpha of the utility color)
    pub accent_80: Hsla,
    /// Tailwind `amber-300/90` (oklab alpha of the utility color)
    pub amber_300_90: Hsla,
    /// Tailwind `amber-400/80` (oklab alpha of the utility color)
    pub amber_400_80: Hsla,
    /// Tailwind `amber-400/90` (oklab alpha of the utility color)
    pub amber_400_90: Hsla,
    /// Tailwind `amber-500/70` (oklab alpha of the utility color)
    pub amber_500_70: Hsla,
    /// Tailwind `amber-600/90` (oklab alpha of the utility color)
    pub amber_600_90: Hsla,
    /// Tailwind `background/40` (oklab alpha of the utility color)
    pub background_40: Hsla,
    /// Tailwind `background/50` (oklab alpha of the utility color)
    pub background_50: Hsla,
    /// Tailwind `background/55` (oklab alpha of the utility color)
    pub background_55: Hsla,
    /// Tailwind `background/60` (oklab alpha of the utility color)
    pub background_60: Hsla,
    /// Tailwind `background/70` (oklab alpha of the utility color)
    pub background_70: Hsla,
    /// Tailwind `background/75` (oklab alpha of the utility color)
    pub background_75: Hsla,
    /// Tailwind `background/80` (oklab alpha of the utility color)
    pub background_80: Hsla,
    /// Tailwind `background/85` (oklab alpha of the utility color)
    pub background_85: Hsla,
    /// Tailwind `background/90` (oklab alpha of the utility color)
    pub background_90: Hsla,
    /// Tailwind `background/95` (oklab alpha of the utility color)
    pub background_95: Hsla,
    /// Tailwind `black/10` (oklab alpha of the utility color)
    pub black_10: Hsla,
    /// Tailwind `black/5` (oklab alpha of the utility color)
    pub black_5: Hsla,
    /// Tailwind `black/50` (oklab alpha of the utility color)
    pub black_50: Hsla,
    /// Tailwind `black/55` (oklab alpha of the utility color)
    pub black_55: Hsla,
    /// Tailwind `black/65` (oklab alpha of the utility color)
    pub black_65: Hsla,
    /// Tailwind `black/70` (oklab alpha of the utility color)
    pub black_70: Hsla,
    /// Tailwind `black/75` (oklab alpha of the utility color)
    pub black_75: Hsla,
    /// Tailwind `black/80` (oklab alpha of the utility color)
    pub black_80: Hsla,
    /// Tailwind `black/85` (oklab alpha of the utility color)
    pub black_85: Hsla,
    /// Tailwind `black/90` (oklab alpha of the utility color)
    pub black_90: Hsla,
    /// Tailwind `blue-500/70` (oklab alpha of the utility color)
    pub blue_500_70: Hsla,
    /// Tailwind `border/15` (oklab alpha of the utility color)
    pub border_15: Hsla,
    /// Tailwind `border/30` (oklab alpha of the utility color)
    pub border_30: Hsla,
    /// Tailwind `border/40` (oklab alpha of the utility color)
    pub border_40: Hsla,
    /// Tailwind `border/45` (oklab alpha of the utility color)
    pub border_45: Hsla,
    /// Tailwind `border/50` (oklab alpha of the utility color)
    pub border_50: Hsla,
    /// Tailwind `border/55` (oklab alpha of the utility color)
    pub border_55: Hsla,
    /// Tailwind `border/60` (oklab alpha of the utility color)
    pub border_60: Hsla,
    /// Tailwind `border/70` (oklab alpha of the utility color)
    pub border_70: Hsla,
    /// Tailwind `border/78` (oklab alpha of the utility color)
    pub border_78: Hsla,
    /// Tailwind `border/80` (oklab alpha of the utility color)
    pub border_80: Hsla,
    /// Tailwind `card/20` (oklab alpha of the utility color)
    pub card_20: Hsla,
    /// Tailwind `card/40` (oklab alpha of the utility color)
    pub card_40: Hsla,
    /// Tailwind `card/60` (oklab alpha of the utility color)
    pub card_60: Hsla,
    /// Tailwind `card/70` (oklab alpha of the utility color)
    pub card_70: Hsla,
    /// Tailwind `card/80` (oklab alpha of the utility color)
    pub card_80: Hsla,
    /// Tailwind `card/90` (oklab alpha of the utility color)
    pub card_90: Hsla,
    /// Tailwind `card/94` (oklab alpha of the utility color)
    pub card_94: Hsla,
    /// Tailwind `card/95` (oklab alpha of the utility color)
    pub card_95: Hsla,
    /// Tailwind `destructive/10` (oklab alpha of the utility color)
    pub destructive_10: Hsla,
    /// Tailwind `destructive/12` (oklab alpha of the utility color)
    pub destructive_12: Hsla,
    /// Tailwind `destructive/14` (oklab alpha of the utility color)
    pub destructive_14: Hsla,
    /// Tailwind `destructive/16` (oklab alpha of the utility color)
    pub destructive_16: Hsla,
    /// Tailwind `destructive/18` (oklab alpha of the utility color)
    pub destructive_18: Hsla,
    /// Tailwind `destructive/20` (oklab alpha of the utility color)
    pub destructive_20: Hsla,
    /// Tailwind `destructive/24` (oklab alpha of the utility color)
    pub destructive_24: Hsla,
    /// Tailwind `destructive/30` (oklab alpha of the utility color)
    pub destructive_30: Hsla,
    /// Tailwind `destructive/32` (oklab alpha of the utility color)
    pub destructive_32: Hsla,
    /// Tailwind `destructive/35` (oklab alpha of the utility color)
    pub destructive_35: Hsla,
    /// Tailwind `destructive/36` (oklab alpha of the utility color)
    pub destructive_36: Hsla,
    /// Tailwind `destructive/4` (oklab alpha of the utility color)
    pub destructive_4: Hsla,
    /// Tailwind `destructive/40` (oklab alpha of the utility color)
    pub destructive_40: Hsla,
    /// Tailwind `destructive/48` (oklab alpha of the utility color)
    pub destructive_48: Hsla,
    /// Tailwind `destructive/5` (oklab alpha of the utility color)
    pub destructive_5: Hsla,
    /// Tailwind `destructive/6` (oklab alpha of the utility color)
    pub destructive_6: Hsla,
    /// Tailwind `destructive/64` (oklab alpha of the utility color)
    pub destructive_64: Hsla,
    /// Tailwind `destructive/8` (oklab alpha of the utility color)
    pub destructive_8: Hsla,
    /// Tailwind `destructive/80` (oklab alpha of the utility color)
    pub destructive_80: Hsla,
    /// Tailwind `destructive/90` (oklab alpha of the utility color)
    pub destructive_90: Hsla,
    /// Tailwind `emerald-300/90` (oklab alpha of the utility color)
    pub emerald_300_90: Hsla,
    /// Tailwind `emerald-500/70` (oklab alpha of the utility color)
    pub emerald_500_70: Hsla,
    /// Tailwind `error-foreground/80` (oklab alpha of the utility color)
    pub error_foreground_80: Hsla,
    /// Tailwind `error/32` (oklab alpha of the utility color)
    pub error_32: Hsla,
    /// Tailwind `error/80` (oklab alpha of the utility color)
    pub error_80: Hsla,
    /// Tailwind `foreground/10` (oklab alpha of the utility color)
    pub foreground_10: Hsla,
    /// Tailwind `foreground/15` (oklab alpha of the utility color)
    pub foreground_15: Hsla,
    /// Tailwind `foreground/18` (oklab alpha of the utility color)
    pub foreground_18: Hsla,
    /// Tailwind `foreground/20` (oklab alpha of the utility color)
    pub foreground_20: Hsla,
    /// Tailwind `foreground/25` (oklab alpha of the utility color)
    pub foreground_25: Hsla,
    /// Tailwind `foreground/28` (oklab alpha of the utility color)
    pub foreground_28: Hsla,
    /// Tailwind `foreground/30` (oklab alpha of the utility color)
    pub foreground_30: Hsla,
    /// Tailwind `foreground/4` (oklab alpha of the utility color)
    pub foreground_4: Hsla,
    /// Tailwind `foreground/5` (oklab alpha of the utility color)
    pub foreground_5: Hsla,
    /// Tailwind `foreground/60` (oklab alpha of the utility color)
    pub foreground_60: Hsla,
    /// Tailwind `foreground/64` (oklab alpha of the utility color)
    pub foreground_64: Hsla,
    /// Tailwind `foreground/65` (oklab alpha of the utility color)
    pub foreground_65: Hsla,
    /// Tailwind `foreground/70` (oklab alpha of the utility color)
    pub foreground_70: Hsla,
    /// Tailwind `foreground/75` (oklab alpha of the utility color)
    pub foreground_75: Hsla,
    /// Tailwind `foreground/8` (oklab alpha of the utility color)
    pub foreground_8: Hsla,
    /// Tailwind `foreground/80` (oklab alpha of the utility color)
    pub foreground_80: Hsla,
    /// Tailwind `foreground/85` (oklab alpha of the utility color)
    pub foreground_85: Hsla,
    /// Tailwind `foreground/90` (oklab alpha of the utility color)
    pub foreground_90: Hsla,
    /// Tailwind `foreground/95` (oklab alpha of the utility color)
    pub foreground_95: Hsla,
    /// Tailwind `indigo-300/90` (oklab alpha of the utility color)
    pub indigo_300_90: Hsla,
    /// Tailwind `info/10` (oklab alpha of the utility color)
    pub info_10: Hsla,
    /// Tailwind `info/16` (oklab alpha of the utility color)
    pub info_16: Hsla,
    /// Tailwind `info/20` (oklab alpha of the utility color)
    pub info_20: Hsla,
    /// Tailwind `info/32` (oklab alpha of the utility color)
    pub info_32: Hsla,
    /// Tailwind `info/4` (oklab alpha of the utility color)
    pub info_4: Hsla,
    /// Tailwind `info/40` (oklab alpha of the utility color)
    pub info_40: Hsla,
    /// Tailwind `info/70` (oklab alpha of the utility color)
    pub info_70: Hsla,
    /// Tailwind `info/8` (oklab alpha of the utility color)
    pub info_8: Hsla,
    /// Tailwind `info/80` (oklab alpha of the utility color)
    pub info_80: Hsla,
    /// Tailwind `input/32` (oklab alpha of the utility color)
    pub input_32: Hsla,
    /// Tailwind `input/40` (oklab alpha of the utility color)
    pub input_40: Hsla,
    /// Tailwind `input/64` (oklab alpha of the utility color)
    pub input_64: Hsla,
    /// Tailwind `input/72` (oklab alpha of the utility color)
    pub input_72: Hsla,
    /// Tailwind `message-action-foreground/20` (oklab alpha of the utility color)
    pub message_action_foreground_20: Hsla,
    /// Tailwind `message-foreground/80` (oklab alpha of the utility color)
    pub message_foreground_80: Hsla,
    /// Tailwind `muted-foreground/15` (oklab alpha of the utility color)
    pub muted_foreground_15: Hsla,
    /// Tailwind `muted-foreground/20` (oklab alpha of the utility color)
    pub muted_foreground_20: Hsla,
    /// Tailwind `muted-foreground/24` (oklab alpha of the utility color)
    pub muted_foreground_24: Hsla,
    /// Tailwind `muted-foreground/25` (oklab alpha of the utility color)
    pub muted_foreground_25: Hsla,
    /// Tailwind `muted-foreground/30` (oklab alpha of the utility color)
    pub muted_foreground_30: Hsla,
    /// Tailwind `muted-foreground/35` (oklab alpha of the utility color)
    pub muted_foreground_35: Hsla,
    /// Tailwind `muted-foreground/40` (oklab alpha of the utility color)
    pub muted_foreground_40: Hsla,
    /// Tailwind `muted-foreground/45` (oklab alpha of the utility color)
    pub muted_foreground_45: Hsla,
    /// Tailwind `muted-foreground/50` (oklab alpha of the utility color)
    pub muted_foreground_50: Hsla,
    /// Tailwind `muted-foreground/55` (oklab alpha of the utility color)
    pub muted_foreground_55: Hsla,
    /// Tailwind `muted-foreground/60` (oklab alpha of the utility color)
    pub muted_foreground_60: Hsla,
    /// Tailwind `muted-foreground/65` (oklab alpha of the utility color)
    pub muted_foreground_65: Hsla,
    /// Tailwind `muted-foreground/70` (oklab alpha of the utility color)
    pub muted_foreground_70: Hsla,
    /// Tailwind `muted-foreground/72` (oklab alpha of the utility color)
    pub muted_foreground_72: Hsla,
    /// Tailwind `muted-foreground/75` (oklab alpha of the utility color)
    pub muted_foreground_75: Hsla,
    /// Tailwind `muted-foreground/80` (oklab alpha of the utility color)
    pub muted_foreground_80: Hsla,
    /// Tailwind `muted-foreground/85` (oklab alpha of the utility color)
    pub muted_foreground_85: Hsla,
    /// Tailwind `muted-foreground/90` (oklab alpha of the utility color)
    pub muted_foreground_90: Hsla,
    /// Tailwind `muted/10` (oklab alpha of the utility color)
    pub muted_10: Hsla,
    /// Tailwind `muted/15` (oklab alpha of the utility color)
    pub muted_15: Hsla,
    /// Tailwind `muted/20` (oklab alpha of the utility color)
    pub muted_20: Hsla,
    /// Tailwind `muted/24` (oklab alpha of the utility color)
    pub muted_24: Hsla,
    /// Tailwind `muted/25` (oklab alpha of the utility color)
    pub muted_25: Hsla,
    /// Tailwind `muted/30` (oklab alpha of the utility color)
    pub muted_30: Hsla,
    /// Tailwind `muted/32` (oklab alpha of the utility color)
    pub muted_32: Hsla,
    /// Tailwind `muted/35` (oklab alpha of the utility color)
    pub muted_35: Hsla,
    /// Tailwind `muted/40` (oklab alpha of the utility color)
    pub muted_40: Hsla,
    /// Tailwind `muted/45` (oklab alpha of the utility color)
    pub muted_45: Hsla,
    /// Tailwind `muted/50` (oklab alpha of the utility color)
    pub muted_50: Hsla,
    /// Tailwind `muted/55` (oklab alpha of the utility color)
    pub muted_55: Hsla,
    /// Tailwind `muted/60` (oklab alpha of the utility color)
    pub muted_60: Hsla,
    /// Tailwind `muted/72` (oklab alpha of the utility color)
    pub muted_72: Hsla,
    /// Tailwind `muted/8` (oklab alpha of the utility color)
    pub muted_8: Hsla,
    /// Tailwind `placeholder/75` (oklab alpha of the utility color)
    pub placeholder_75: Hsla,
    /// Tailwind `popover-foreground/90` (oklab alpha of the utility color)
    pub popover_foreground_90: Hsla,
    /// Tailwind `popover/92` (oklab alpha of the utility color)
    pub popover_92: Hsla,
    /// Tailwind `popover/95` (oklab alpha of the utility color)
    pub popover_95: Hsla,
    /// Tailwind `primary/10` (oklab alpha of the utility color)
    pub primary_10: Hsla,
    /// Tailwind `primary/15` (oklab alpha of the utility color)
    pub primary_15: Hsla,
    /// Tailwind `primary/25` (oklab alpha of the utility color)
    pub primary_25: Hsla,
    /// Tailwind `primary/30` (oklab alpha of the utility color)
    pub primary_30: Hsla,
    /// Tailwind `primary/35` (oklab alpha of the utility color)
    pub primary_35: Hsla,
    /// Tailwind `primary/40` (oklab alpha of the utility color)
    pub primary_40: Hsla,
    /// Tailwind `primary/5` (oklab alpha of the utility color)
    pub primary_5: Hsla,
    /// Tailwind `primary/50` (oklab alpha of the utility color)
    pub primary_50: Hsla,
    /// Tailwind `primary/55` (oklab alpha of the utility color)
    pub primary_55: Hsla,
    /// Tailwind `primary/60` (oklab alpha of the utility color)
    pub primary_60: Hsla,
    /// Tailwind `primary/70` (oklab alpha of the utility color)
    pub primary_70: Hsla,
    /// Tailwind `primary/8` (oklab alpha of the utility color)
    pub primary_8: Hsla,
    /// Tailwind `primary/90` (oklab alpha of the utility color)
    pub primary_90: Hsla,
    /// Tailwind `purple-500/70` (oklab alpha of the utility color)
    pub purple_500_70: Hsla,
    /// Tailwind `red-300/90` (oklab alpha of the utility color)
    pub red_300_90: Hsla,
    /// Tailwind `red-500/70` (oklab alpha of the utility color)
    pub red_500_70: Hsla,
    /// Tailwind `ring/24` (oklab alpha of the utility color)
    pub ring_24: Hsla,
    /// Tailwind `ring/50` (oklab alpha of the utility color)
    pub ring_50: Hsla,
    /// Tailwind `ring/60` (oklab alpha of the utility color)
    pub ring_60: Hsla,
    /// Tailwind `ring/70` (oklab alpha of the utility color)
    pub ring_70: Hsla,
    /// Tailwind `secondary-label/70` (oklab alpha of the utility color)
    pub secondary_label_70: Hsla,
    /// Tailwind `secondary/80` (oklab alpha of the utility color)
    pub secondary_80: Hsla,
    /// Tailwind `secondary/90` (oklab alpha of the utility color)
    pub secondary_90: Hsla,
    /// Tailwind `sidebar-border/60` (oklab alpha of the utility color)
    pub sidebar_border_60: Hsla,
    /// Tailwind `sidebar-foreground/25` (oklab alpha of the utility color)
    pub sidebar_foreground_25: Hsla,
    /// Tailwind `sidebar-foreground/80` (oklab alpha of the utility color)
    pub sidebar_foreground_80: Hsla,
    /// Tailwind `sidebar-foreground/90` (oklab alpha of the utility color)
    pub sidebar_foreground_90: Hsla,
    /// Tailwind `sidebar-muted-foreground/55` (oklab alpha of the utility color)
    pub sidebar_muted_foreground_55: Hsla,
    /// Tailwind `sidebar-muted-foreground/60` (oklab alpha of the utility color)
    pub sidebar_muted_foreground_60: Hsla,
    /// Tailwind `sidebar-muted-foreground/70` (oklab alpha of the utility color)
    pub sidebar_muted_foreground_70: Hsla,
    /// Tailwind `sidebar-muted-foreground/75` (oklab alpha of the utility color)
    pub sidebar_muted_foreground_75: Hsla,
    /// Tailwind `sidebar-muted-foreground/80` (oklab alpha of the utility color)
    pub sidebar_muted_foreground_80: Hsla,
    /// Tailwind `sky-300/80` (oklab alpha of the utility color)
    pub sky_300_80: Hsla,
    /// Tailwind `success/10` (oklab alpha of the utility color)
    pub success_10: Hsla,
    /// Tailwind `success/15` (oklab alpha of the utility color)
    pub success_15: Hsla,
    /// Tailwind `success/16` (oklab alpha of the utility color)
    pub success_16: Hsla,
    /// Tailwind `success/25` (oklab alpha of the utility color)
    pub success_25: Hsla,
    /// Tailwind `success/30` (oklab alpha of the utility color)
    pub success_30: Hsla,
    /// Tailwind `success/32` (oklab alpha of the utility color)
    pub success_32: Hsla,
    /// Tailwind `success/4` (oklab alpha of the utility color)
    pub success_4: Hsla,
    /// Tailwind `success/60` (oklab alpha of the utility color)
    pub success_60: Hsla,
    /// Tailwind `success/8` (oklab alpha of the utility color)
    pub success_8: Hsla,
    /// Tailwind `success/80` (oklab alpha of the utility color)
    pub success_80: Hsla,
    /// Tailwind `teal-300/90` (oklab alpha of the utility color)
    pub teal_300_90: Hsla,
    /// Tailwind `thumb-border/78` (oklab alpha of the utility color)
    pub thumb_border_78: Hsla,
    /// Tailwind `thumb-foreground/18` (oklab alpha of the utility color)
    pub thumb_foreground_18: Hsla,
    /// Tailwind `tool-error-icon/40` (oklab alpha of the utility color)
    pub tool_error_icon_40: Hsla,
    /// Tailwind `violet-300/90` (oklab alpha of the utility color)
    pub violet_300_90: Hsla,
    /// Tailwind `warning-foreground/80` (oklab alpha of the utility color)
    pub warning_foreground_80: Hsla,
    /// Tailwind `warning/10` (oklab alpha of the utility color)
    pub warning_10: Hsla,
    /// Tailwind `warning/12` (oklab alpha of the utility color)
    pub warning_12: Hsla,
    /// Tailwind `warning/14` (oklab alpha of the utility color)
    pub warning_14: Hsla,
    /// Tailwind `warning/16` (oklab alpha of the utility color)
    pub warning_16: Hsla,
    /// Tailwind `warning/18` (oklab alpha of the utility color)
    pub warning_18: Hsla,
    /// Tailwind `warning/20` (oklab alpha of the utility color)
    pub warning_20: Hsla,
    /// Tailwind `warning/24` (oklab alpha of the utility color)
    pub warning_24: Hsla,
    /// Tailwind `warning/25` (oklab alpha of the utility color)
    pub warning_25: Hsla,
    /// Tailwind `warning/30` (oklab alpha of the utility color)
    pub warning_30: Hsla,
    /// Tailwind `warning/32` (oklab alpha of the utility color)
    pub warning_32: Hsla,
    /// Tailwind `warning/4` (oklab alpha of the utility color)
    pub warning_4: Hsla,
    /// Tailwind `warning/40` (oklab alpha of the utility color)
    pub warning_40: Hsla,
    /// Tailwind `warning/60` (oklab alpha of the utility color)
    pub warning_60: Hsla,
    /// Tailwind `warning/8` (oklab alpha of the utility color)
    pub warning_8: Hsla,
    /// Tailwind `warning/80` (oklab alpha of the utility color)
    pub warning_80: Hsla,
    /// Tailwind `warning/90` (oklab alpha of the utility color)
    pub warning_90: Hsla,
    /// Tailwind `white/10` (oklab alpha of the utility color)
    pub white_10: Hsla,
    /// Tailwind `white/2` (oklab alpha of the utility color)
    pub white_2: Hsla,
    /// Tailwind `white/20` (oklab alpha of the utility color)
    pub white_20: Hsla,
    /// Tailwind `white/3` (oklab alpha of the utility color)
    pub white_3: Hsla,
    /// Tailwind `white/4` (oklab alpha of the utility color)
    pub white_4: Hsla,
    /// Tailwind `white/5` (oklab alpha of the utility color)
    pub white_5: Hsla,
    /// Tailwind `white/65` (oklab alpha of the utility color)
    pub white_65: Hsla,
    /// Tailwind `white/7` (oklab alpha of the utility color)
    pub white_7: Hsla,
    /// Tailwind `white/70` (oklab alpha of the utility color)
    pub white_70: Hsla,
    /// Tailwind `white/80` (oklab alpha of the utility color)
    pub white_80: Hsla,
    /// Tailwind `white/90` (oklab alpha of the utility color)
    pub white_90: Hsla,
    /// Tailwind `zinc-400/80` (oklab alpha of the utility color)
    pub zinc_400_80: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub outline: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub border_mix_78: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub border_mix_60: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub foreground_mix_8: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub app_sidebar_glass: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub app_main_glass: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub composer_glass: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub codeblock_bg: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub diff_viewport: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub diff_file_surface: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub inset_highlight: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub inset_press: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub group_text_bevel: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub skeleton_highlight: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub bevel: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub bevel_pressed: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub scrollbar_thumb: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub scrollbar_thumb_hover: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub model_picker_thumb: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub model_picker_thumb_hover: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub code_scrollbar_thumb: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub scroll_area_thumb: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub input_48: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub primary_24: Hsla,
    /// Pre-refresh name kept for existing callers; prefer the token it maps to
    pub ring_45: Hsla,
    /// Sidebar thread status and PR pill colors.
    pub status: StatusColors,
    /// Terminal colors.
    pub terminal: TerminalColors,
}

/// The light appearance, `<html>` scope.
pub const LIGHT: Colors = Colors {
    is_dark: false,
    accent: hex(0xF4F4F5FF),
    accent_foreground: hex(0x18181BFF),
    app_chrome_background: hex(0xFCFCFCFF),
    app_scrollbar_thumb: hex(0xD9D9D9FF),
    app_scrollbar_thumb_hover: hex(0xBFBFBFFF),
    appearance_contrast_target: hex(0x000000FF),
    background: hex(0xFCFCFCFF),
    border: hex(0xE4E4E7FF),
    card: hex(0xFFFFFFFF),
    card_foreground: hex(0x27272AFF),
    code_background: hex(0xFFFFFFFF),
    code_foreground: hex(0x27272AFF),
    contrast_accent_foreground: hex(0x18181BFF),
    contrast_border: hex(0xE4E4E7FF),
    contrast_card_foreground: hex(0x27272AFF),
    contrast_foreground: hex(0x27272AFF),
    contrast_icon_muted: hex(0x71717BFF),
    contrast_input: hex(0xD4D4D8FF),
    contrast_message_foreground: hex(0x27272AFF),
    contrast_muted_foreground: hex(0x71717BFF),
    contrast_placeholder: hex(0x71717BFF),
    contrast_popover_foreground: hex(0x27272AFF),
    contrast_secondary_foreground: hex(0x27272AFF),
    contrast_secondary_label: hex(0x71717BFF),
    contrast_sidebar_border: hex(0xE4E4E7FF),
    contrast_sidebar_foreground: hex(0x27272AFF),
    contrast_sidebar_muted_foreground: hex(0x71717BFF),
    contrast_toolbar_border: hex(0xE4E4E7FF),
    contrast_toolbar_control_foreground: hex(0x27272AFF),
    contrast_toolbar_foreground: hex(0x27272AFF),
    destructive: hex(0xFB2C36FF),
    destructive_foreground: hex(0xC10007FF),
    diff_addition: hex(0x00BC7DFF),
    diff_deletion: hex(0xFB2C36FF),
    error: hex(0xFB2C36FF),
    error_foreground: hex(0xC10007FF),
    error_surface: hex(0xFB2C3614),
    font_weight_bold: hex(0x770000FF),
    font_weight_medium: hex(0x550000FF),
    font_weight_normal: hex(0x440000FF),
    font_weight_semibold: hex(0x660000FF),
    foreground: hex(0x27272AFF),
    icon_muted: hex(0x71717BFF),
    info: hex(0x2B7FFFFF),
    info_foreground: hex(0x1447E6FF),
    input: hex(0xD4D4D8FF),
    message_action: hex(0x1B4ED8FF),
    message_action_foreground: hex(0xFFFFFFFF),
    message_action_hover: hex(0x3160DBFF),
    message_foreground: hex(0x27272AFF),
    message_surface: hex(0xF4F4F5FF),
    muted: hex(0xFAFAFAFF),
    muted_foreground: hex(0x71717BFF),
    placeholder: hex(0x71717BFF),
    popover: hex(0xFFFFFFFF),
    popover_foreground: hex(0x27272AFF),
    primary: hex(0x1B4ED8FF),
    primary_foreground: hex(0xFFFFFFFF),
    ring: hex(0x1B4ED8FF),
    secondary: hex(0xFAFAFAFF),
    secondary_foreground: hex(0x27272AFF),
    secondary_label: hex(0x71717BFF),
    sidebar: hex(0xFAFAFAFF),
    sidebar_border: hex(0xE4E4E7FF),
    sidebar_control_surface: hex(0xF4F4F5FF),
    sidebar_foreground: hex(0x27272AFF),
    sidebar_icon_color: hex(0xA8A8AEFF),
    sidebar_muted_foreground: hex(0x71717BFF),
    sidebar_row_active: hex(0xFFFFFFFF),
    sidebar_row_hover: hex(0xFCFCFCFF),
    sidebar_row_selected: hex(0xFFFFFFFF),
    sidebar_stage_fade: hex(0xFAFAFAFF),
    stage_art_bottom: hex(0x1538D0FF),
    stage_art_celeste_highlight: hex(0xD2FFFFFF),
    stage_art_celeste_secondary: hex(0x48DCF5FF),
    stage_art_grid_line: hex(0xEAF6FFFF),
    stage_art_highlight: hex(0xD4F6FFFF),
    stage_art_line: hex(0xDDF7FFFF),
    stage_art_mid: hex(0x347FF8FF),
    stage_art_secondary: hex(0x65C8FFFF),
    stage_art_tertiary: hex(0x7C8BFFFF),
    stage_art_top: hex(0x67C2FFFF),
    stage_art_violet_highlight: hex(0xD9D8FFFF),
    stage_night_base_bottom: hex(0x07152FFF),
    stage_night_base_mid: hex(0x151443FF),
    stage_night_base_top: hex(0x32155BFF),
    stage_night_bottom: hex(0x07152FFF),
    stage_night_glow_highlight: hex(0x5165D8FF),
    stage_night_glow_secondary: hex(0x283075FF),
    stage_night_highlight: hex(0x4EA4FFFF),
    stage_night_line: hex(0xE4EAFFFF),
    stage_night_mid: hex(0x151443FF),
    stage_night_secondary: hex(0x696FEAFF),
    stage_night_sparkle: hex(0xC8D7FFFF),
    stage_night_tertiary: hex(0xA85BEAFF),
    stage_night_top: hex(0x32155BFF),
    success: hex(0x00BC7DFF),
    success_foreground: hex(0x007A55FF),
    surface_raised: hex(0xFFFFFF33),
    terminal_background: hex(0xFCFCFCFF),
    terminal_cursor: hex(0x26384EFF),
    terminal_foreground: hex(0x27272AFF),
    terminal_selection_background: hex(0x253F6333),
    tool_error_icon: hex(0xFB2C36FF),
    toolbar_background: hex(0xFCFCFCFF),
    toolbar_border: hex(0xE4E4E7FF),
    toolbar_control: hex(0xFFFFFFFF),
    toolbar_control_foreground: hex(0x27272AFF),
    toolbar_control_hover: hex(0xF4F4F5FF),
    toolbar_foreground: hex(0x27272AFF),
    update: hex(0x1B4ED8FF),
    update_foreground: hex(0x1B4ED8FF),
    update_surface: hex(0x1B4ED81F),
    warning: hex(0xFE9A00FF),
    warning_foreground: hex(0xBB4D00FF),
    warning_surface: hex(0xFE9A0014),
    accent_10: hex(0xF4F4F51A),
    accent_20: hex(0xF4F4F533),
    accent_30: hex(0xF4F4F54D),
    accent_40: hex(0xF4F4F566),
    accent_45: hex(0xF4F4F573),
    accent_50: hex(0xF4F4F580),
    accent_60: hex(0xF4F4F599),
    accent_70: hex(0xF4F4F5B3),
    accent_80: hex(0xF4F4F5CC),
    amber_300_90: hex(0xFFD230E6),
    amber_400_80: hex(0xFFB900CC),
    amber_400_90: hex(0xFFB900E6),
    amber_500_70: hex(0xFE9A00B3),
    amber_600_90: hex(0xE17100E6),
    background_40: hex(0xFCFCFC66),
    background_50: hex(0xFCFCFC80),
    background_55: hex(0xFCFCFC8C),
    background_60: hex(0xFCFCFC99),
    background_70: hex(0xFCFCFCB3),
    background_75: hex(0xFCFCFCBF),
    background_80: hex(0xFCFCFCCC),
    background_85: hex(0xFCFCFCD9),
    background_90: hex(0xFCFCFCE6),
    background_95: hex(0xFCFCFCF2),
    black_10: hex(0x0000001A),
    black_5: hex(0x0000000D),
    black_50: hex(0x00000080),
    black_55: hex(0x0000008C),
    black_65: hex(0x000000A6),
    black_70: hex(0x000000B3),
    black_75: hex(0x000000BF),
    black_80: hex(0x000000CC),
    black_85: hex(0x000000D9),
    black_90: hex(0x000000E6),
    blue_500_70: hex(0x2B7FFFB3),
    border_15: hex(0xE4E4E726),
    border_30: hex(0xE4E4E74D),
    border_40: hex(0xE4E4E766),
    border_45: hex(0xE4E4E773),
    border_50: hex(0xE4E4E780),
    border_55: hex(0xE4E4E78C),
    border_60: hex(0xE4E4E799),
    border_70: hex(0xE4E4E7B3),
    border_78: hex(0xE4E4E7C7),
    border_80: hex(0xE4E4E7CC),
    card_20: hex(0xFFFFFF33),
    card_40: hex(0xFFFFFF66),
    card_60: hex(0xFFFFFF99),
    card_70: hex(0xFFFFFFB3),
    card_80: hex(0xFFFFFFCC),
    card_90: hex(0xFFFFFFE6),
    card_94: hex(0xFFFFFFF0),
    card_95: hex(0xFFFFFFF2),
    destructive_10: hex(0xFB2C361A),
    destructive_12: hex(0xFB2C361F),
    destructive_14: hex(0xFB2C3624),
    destructive_16: hex(0xFB2C3629),
    destructive_18: hex(0xFB2C362E),
    destructive_20: hex(0xFB2C3633),
    destructive_24: hex(0xFB2C363D),
    destructive_30: hex(0xFB2C364D),
    destructive_32: hex(0xFB2C3652),
    destructive_35: hex(0xFB2C3659),
    destructive_36: hex(0xFB2C365C),
    destructive_4: hex(0xFB2C360A),
    destructive_40: hex(0xFB2C3666),
    destructive_48: hex(0xFB2C367A),
    destructive_5: hex(0xFB2C360D),
    destructive_6: hex(0xFB2C360F),
    destructive_64: hex(0xFB2C36A3),
    destructive_8: hex(0xFB2C3614),
    destructive_80: hex(0xFB2C36CC),
    destructive_90: hex(0xFB2C36E6),
    emerald_300_90: hex(0x5EE9B5E6),
    emerald_500_70: hex(0x00BC7DB3),
    error_foreground_80: hex(0xC10007CC),
    error_32: hex(0xFB2C3652),
    error_80: hex(0xFB2C36CC),
    foreground_10: hex(0x27272A1A),
    foreground_15: hex(0x27272A26),
    foreground_18: hex(0x27272A2E),
    foreground_20: hex(0x27272A33),
    foreground_25: hex(0x27272A40),
    foreground_28: hex(0x27272A47),
    foreground_30: hex(0x27272A4D),
    foreground_4: hex(0x27272A0A),
    foreground_5: hex(0x27272A0D),
    foreground_60: hex(0x27272A99),
    foreground_64: hex(0x27272AA3),
    foreground_65: hex(0x27272AA6),
    foreground_70: hex(0x27272AB3),
    foreground_75: hex(0x27272ABF),
    foreground_8: hex(0x27272A14),
    foreground_80: hex(0x27272ACC),
    foreground_85: hex(0x27272AD9),
    foreground_90: hex(0x27272AE6),
    foreground_95: hex(0x27272AF2),
    indigo_300_90: hex(0xA3B3FFE6),
    info_10: hex(0x2B7FFF1A),
    info_16: hex(0x2B7FFF29),
    info_20: hex(0x2B7FFF33),
    info_32: hex(0x2B7FFF52),
    info_4: hex(0x2B7FFF0A),
    info_40: hex(0x2B7FFF66),
    info_70: hex(0x2B7FFFB3),
    info_8: hex(0x2B7FFF14),
    info_80: hex(0x2B7FFFCC),
    input_32: hex(0xD4D4D852),
    input_40: hex(0xD4D4D866),
    input_64: hex(0xD4D4D8A3),
    input_72: hex(0xD4D4D8B8),
    message_action_foreground_20: hex(0xFFFFFF33),
    message_foreground_80: hex(0x27272ACC),
    muted_foreground_15: hex(0x71717B26),
    muted_foreground_20: hex(0x71717B33),
    muted_foreground_24: hex(0x71717B3D),
    muted_foreground_25: hex(0x71717B40),
    muted_foreground_30: hex(0x71717B4D),
    muted_foreground_35: hex(0x71717B59),
    muted_foreground_40: hex(0x71717B66),
    muted_foreground_45: hex(0x71717B73),
    muted_foreground_50: hex(0x71717B80),
    muted_foreground_55: hex(0x71717B8C),
    muted_foreground_60: hex(0x71717B99),
    muted_foreground_65: hex(0x71717BA6),
    muted_foreground_70: hex(0x71717BB3),
    muted_foreground_72: hex(0x71717BB8),
    muted_foreground_75: hex(0x71717BBF),
    muted_foreground_80: hex(0x71717BCC),
    muted_foreground_85: hex(0x71717BD9),
    muted_foreground_90: hex(0x71717BE6),
    muted_10: hex(0xFAFAFA1A),
    muted_15: hex(0xFAFAFA26),
    muted_20: hex(0xFAFAFA33),
    muted_24: hex(0xFAFAFA3D),
    muted_25: hex(0xFAFAFA40),
    muted_30: hex(0xFAFAFA4D),
    muted_32: hex(0xFAFAFA52),
    muted_35: hex(0xFAFAFA59),
    muted_40: hex(0xFAFAFA66),
    muted_45: hex(0xFAFAFA73),
    muted_50: hex(0xFAFAFA80),
    muted_55: hex(0xFAFAFA8C),
    muted_60: hex(0xFAFAFA99),
    muted_72: hex(0xFAFAFAB8),
    muted_8: hex(0xFAFAFA14),
    placeholder_75: hex(0x71717BBF),
    popover_foreground_90: hex(0x27272AE6),
    popover_92: hex(0xFFFFFFEB),
    popover_95: hex(0xFFFFFFF2),
    primary_10: hex(0x1B4ED81A),
    primary_15: hex(0x1B4ED826),
    primary_25: hex(0x1B4ED840),
    primary_30: hex(0x1B4ED84D),
    primary_35: hex(0x1B4ED859),
    primary_40: hex(0x1B4ED866),
    primary_5: hex(0x1B4ED80D),
    primary_50: hex(0x1B4ED880),
    primary_55: hex(0x1B4ED88C),
    primary_60: hex(0x1B4ED899),
    primary_70: hex(0x1B4ED8B3),
    primary_8: hex(0x1B4ED814),
    primary_90: hex(0x1B4ED8E6),
    purple_500_70: hex(0xAD46FFB3),
    red_300_90: hex(0xFFA2A2E6),
    red_500_70: hex(0xFB2C36B3),
    ring_24: hex(0x1B4ED83D),
    ring_50: hex(0x1B4ED880),
    ring_60: hex(0x1B4ED899),
    ring_70: hex(0x1B4ED8B3),
    secondary_label_70: hex(0x71717BB3),
    secondary_80: hex(0xFAFAFACC),
    secondary_90: hex(0xFAFAFAE6),
    sidebar_border_60: hex(0xE4E4E799),
    sidebar_foreground_25: hex(0x27272A40),
    sidebar_foreground_80: hex(0x27272ACC),
    sidebar_foreground_90: hex(0x27272AE6),
    sidebar_muted_foreground_55: hex(0x71717B8C),
    sidebar_muted_foreground_60: hex(0x71717B99),
    sidebar_muted_foreground_70: hex(0x71717BB3),
    sidebar_muted_foreground_75: hex(0x71717BBF),
    sidebar_muted_foreground_80: hex(0x71717BCC),
    sky_300_80: hex(0x74D4FFCC),
    success_10: hex(0x00BC7D1A),
    success_15: hex(0x00BC7D26),
    success_16: hex(0x00BC7D29),
    success_25: hex(0x00BC7D40),
    success_30: hex(0x00BC7D4D),
    success_32: hex(0x00BC7D52),
    success_4: hex(0x00BC7D0A),
    success_60: hex(0x00BC7D99),
    success_8: hex(0x00BC7D14),
    success_80: hex(0x00BC7DCC),
    teal_300_90: hex(0x46ECD5E6),
    thumb_border_78: hex(0xE4E4E7C7),
    thumb_foreground_18: hex(0x27272A2E),
    tool_error_icon_40: hex(0xFB2C3666),
    violet_300_90: hex(0xC4B4FFE6),
    warning_foreground_80: hex(0xBB4D00CC),
    warning_10: hex(0xFE9A001A),
    warning_12: hex(0xFE9A001F),
    warning_14: hex(0xFE9A0024),
    warning_16: hex(0xFE9A0029),
    warning_18: hex(0xFE9A002E),
    warning_20: hex(0xFE9A0033),
    warning_24: hex(0xFE9A003D),
    warning_25: hex(0xFE9A0040),
    warning_30: hex(0xFE9A004D),
    warning_32: hex(0xFE9A0052),
    warning_4: hex(0xFE9A000A),
    warning_40: hex(0xFE9A0066),
    warning_60: hex(0xFE9A0099),
    warning_8: hex(0xFE9A0014),
    warning_80: hex(0xFE9A00CC),
    warning_90: hex(0xFE9A00E6),
    white_10: hex(0xFFFFFF1A),
    white_2: hex(0xFFFFFF05),
    white_20: hex(0xFFFFFF33),
    white_3: hex(0xFFFFFF08),
    white_4: hex(0xFFFFFF0A),
    white_5: hex(0xFFFFFF0D),
    white_65: hex(0xFFFFFFA6),
    white_7: hex(0xFFFFFF12),
    white_70: hex(0xFFFFFFB3),
    white_80: hex(0xFFFFFFCC),
    white_90: hex(0xFFFFFFE6),
    zinc_400_80: hex(0x9F9FA9CC),
    outline: hex(0x1B4ED880),
    border_mix_78: hex(0xE4E4E7C7),
    border_mix_60: hex(0xE4E4E799),
    foreground_mix_8: hex(0x27272A14),
    app_sidebar_glass: hex(0xFAFAFAFF),
    app_main_glass: hex(0xFCFCFCFF),
    composer_glass: hex(0xFFFFFFFF),
    codeblock_bg: hex(0xFFFFFFFF),
    diff_viewport: hex(0xFCFCFCFF),
    diff_file_surface: hex(0xFFFFFFFF),
    inset_highlight: hex(0xFFFFFF29),
    inset_press: hex(0x00000014),
    group_text_bevel: hex(0x0000000F),
    skeleton_highlight: hex(0xFFFFFFA3),
    bevel: hex(0x0000000A),
    bevel_pressed: hex(0x00000000),
    scrollbar_thumb: hex(0xD9D9D9FF),
    scrollbar_thumb_hover: hex(0xBFBFBFFF),
    model_picker_thumb: hex(0x0000001A),
    model_picker_thumb_hover: hex(0x00000033),
    code_scrollbar_thumb: hex(0xE4E4E7C7),
    scroll_area_thumb: hex(0x27272A33),
    input_48: hex(0xD4D4D87A),
    primary_24: hex(0x1B4ED83D),
    ring_45: hex(0x1B4ED873),
    status: LIGHT_STATUS,
    terminal: LIGHT_TERMINAL,
};

/// The dark appearance, `<html>` scope.
pub const DARK: Colors = Colors {
    is_dark: true,
    accent: hex(0x3E3E3EFF),
    accent_foreground: hex(0xFAFAF9FF),
    app_chrome_background: hex(0x1C1C1CFF),
    app_scrollbar_thumb: hex(0xFFFFFF14),
    app_scrollbar_thumb_hover: hex(0xFFFFFF1F),
    appearance_contrast_target: hex(0xFFFFFFFF),
    background: hex(0x1C1C1CFF),
    border: hex(0x3E3E3EFF),
    card: hex(0x2D2D2CFF),
    card_foreground: hex(0xFAFAF9FF),
    code_background: hex(0x222222FF),
    code_foreground: hex(0xFAFAF9FF),
    contrast_accent_foreground: hex(0xFAFAF9FF),
    contrast_border: hex(0x3E3E3EFF),
    contrast_card_foreground: hex(0xFAFAF9FF),
    contrast_foreground: hex(0xFAFAF9FF),
    contrast_icon_muted: hex(0x9E9E9EFF),
    contrast_input: hex(0x3E3E3EFF),
    contrast_message_foreground: hex(0xFAFAF9FF),
    contrast_muted_foreground: hex(0x9E9E9EFF),
    contrast_placeholder: hex(0x9E9E9EFF),
    contrast_popover_foreground: hex(0xFAFAF9FF),
    contrast_secondary_foreground: hex(0xFAFAF9FF),
    contrast_secondary_label: hex(0x9E9E9EFF),
    contrast_sidebar_border: hex(0x333333FF),
    contrast_sidebar_foreground: hex(0xE1E1E0FF),
    contrast_sidebar_muted_foreground: hex(0x9E9E9EFF),
    contrast_toolbar_border: hex(0x3E3E3EFF),
    contrast_toolbar_control_foreground: hex(0xFAFAF9FF),
    contrast_toolbar_foreground: hex(0xFAFAF9FF),
    destructive: hex(0xFB414AFF),
    destructive_foreground: hex(0xFF6467FF),
    diff_addition: hex(0x00BC7DFF),
    diff_deletion: hex(0xFB414AFF),
    error: hex(0xFB414AFF),
    error_foreground: hex(0xFF6467FF),
    error_surface: hex(0xFB414A29),
    font_weight_bold: hex(0x770000FF),
    font_weight_medium: hex(0x550000FF),
    font_weight_normal: hex(0x440000FF),
    font_weight_semibold: hex(0x660000FF),
    foreground: hex(0xFAFAF9FF),
    icon_muted: hex(0x9E9E9EFF),
    info: hex(0x2B7FFFFF),
    info_foreground: hex(0x51A2FFFF),
    input: hex(0x3E3E3EFF),
    message_action: hex(0xFAFAF9FF),
    message_action_foreground: hex(0x1C1C1CFF),
    message_action_hover: hex(0xE1E1E0FF),
    message_foreground: hex(0xFAFAF9FF),
    message_surface: hex(0x272727FF),
    muted: hex(0x343434FF),
    muted_foreground: hex(0x9E9E9EFF),
    placeholder: hex(0x9E9E9EFF),
    popover: hex(0x343434FF),
    popover_foreground: hex(0xFAFAF9FF),
    primary: hex(0xFAFAF9FF),
    primary_foreground: hex(0x1C1C1CFF),
    ring: hex(0x9E9E9EFF),
    secondary: hex(0x2D2D2CFF),
    secondary_foreground: hex(0xFAFAF9FF),
    secondary_label: hex(0x9E9E9EFF),
    sidebar: hex(0x222222FF),
    sidebar_border: hex(0x333333FF),
    sidebar_control_surface: hex(0x1C1C1CFF),
    sidebar_foreground: hex(0xE1E1E0FF),
    sidebar_icon_color: hex(0x6C6C6CFF),
    sidebar_muted_foreground: hex(0x9E9E9EFF),
    sidebar_row_active: hex(0x2B2B2BFF),
    sidebar_row_hover: hex(0x292929FF),
    sidebar_row_selected: hex(0x2B2B2BFF),
    sidebar_stage_fade: hex(0x222222FF),
    stage_art_bottom: hex(0x101F6EFF),
    stage_art_celeste_highlight: hex(0xD2FFFFFF),
    stage_art_celeste_secondary: hex(0x48DCF5FF),
    stage_art_grid_line: hex(0xEAF6FFFF),
    stage_art_highlight: hex(0xD4F6FFFF),
    stage_art_line: hex(0xDDF7FFFF),
    stage_art_mid: hex(0x2050AEFF),
    stage_art_secondary: hex(0x65C8FFFF),
    stage_art_tertiary: hex(0x7C8BFFFF),
    stage_art_top: hex(0x3A7AD1FF),
    stage_art_violet_highlight: hex(0xD9D8FFFF),
    stage_night_base_bottom: hex(0x07152FFF),
    stage_night_base_mid: hex(0x151443FF),
    stage_night_base_top: hex(0x32155BFF),
    stage_night_bottom: hex(0x07152FFF),
    stage_night_glow_highlight: hex(0x5165D8FF),
    stage_night_glow_secondary: hex(0x283075FF),
    stage_night_highlight: hex(0x4EA4FFFF),
    stage_night_line: hex(0xE4EAFFFF),
    stage_night_mid: hex(0x151443FF),
    stage_night_secondary: hex(0x696FEAFF),
    stage_night_sparkle: hex(0xC8D7FFFF),
    stage_night_tertiary: hex(0xA85BEAFF),
    stage_night_top: hex(0x32155BFF),
    success: hex(0x00BC7DFF),
    success_foreground: hex(0x00D492FF),
    surface_raised: hex(0x2D2D2CFF),
    terminal_background: hex(0x1C1C1CFF),
    terminal_cursor: hex(0xB4CBFFFF),
    terminal_foreground: hex(0xFAFAF9FF),
    terminal_selection_background: hex(0xB4CBFF40),
    tool_error_icon: hex(0xFCA5A5FF),
    toolbar_background: hex(0x1C1C1CFF),
    toolbar_border: hex(0x3E3E3EFF),
    toolbar_control: hex(0x343434FF),
    toolbar_control_foreground: hex(0xFAFAF9FF),
    toolbar_control_hover: hex(0x3E3E3EFF),
    toolbar_foreground: hex(0xFAFAF9FF),
    update: hex(0xFAFAF9FF),
    update_foreground: hex(0x51A2FFFF),
    update_surface: hex(0xFAFAF92E),
    warning: hex(0xFE9A00FF),
    warning_foreground: hex(0xFFB900FF),
    warning_surface: hex(0xFE9A0029),
    accent_10: hex(0x3E3E3E1A),
    accent_20: hex(0x3E3E3E33),
    accent_30: hex(0x3E3E3E4D),
    accent_40: hex(0x3E3E3E66),
    accent_45: hex(0x3E3E3E73),
    accent_50: hex(0x3E3E3E80),
    accent_60: hex(0x3E3E3E99),
    accent_70: hex(0x3E3E3EB3),
    accent_80: hex(0x3E3E3ECC),
    amber_300_90: hex(0xFFD230E6),
    amber_400_80: hex(0xFFB900CC),
    amber_400_90: hex(0xFFB900E6),
    amber_500_70: hex(0xFE9A00B3),
    amber_600_90: hex(0xE17100E6),
    background_40: hex(0x1C1C1C66),
    background_50: hex(0x1C1C1C80),
    background_55: hex(0x1C1C1C8C),
    background_60: hex(0x1C1C1C99),
    background_70: hex(0x1C1C1CB3),
    background_75: hex(0x1C1C1CBF),
    background_80: hex(0x1C1C1CCC),
    background_85: hex(0x1C1C1CD9),
    background_90: hex(0x1C1C1CE6),
    background_95: hex(0x1C1C1CF2),
    black_10: hex(0x0000001A),
    black_5: hex(0x0000000D),
    black_50: hex(0x00000080),
    black_55: hex(0x0000008C),
    black_65: hex(0x000000A6),
    black_70: hex(0x000000B3),
    black_75: hex(0x000000BF),
    black_80: hex(0x000000CC),
    black_85: hex(0x000000D9),
    black_90: hex(0x000000E6),
    blue_500_70: hex(0x2B7FFFB3),
    border_15: hex(0x3E3E3E26),
    border_30: hex(0x3E3E3E4D),
    border_40: hex(0x3E3E3E66),
    border_45: hex(0x3E3E3E73),
    border_50: hex(0x3E3E3E80),
    border_55: hex(0x3E3E3E8C),
    border_60: hex(0x3E3E3E99),
    border_70: hex(0x3E3E3EB3),
    border_78: hex(0x3E3E3EC7),
    border_80: hex(0x3E3E3ECC),
    card_20: hex(0x2D2D2C33),
    card_40: hex(0x2D2D2C66),
    card_60: hex(0x2D2D2C99),
    card_70: hex(0x2D2D2CB3),
    card_80: hex(0x2D2D2CCC),
    card_90: hex(0x2D2D2CE6),
    card_94: hex(0x2D2D2CF0),
    card_95: hex(0x2D2D2CF2),
    destructive_10: hex(0xFB414A1A),
    destructive_12: hex(0xFB414A1F),
    destructive_14: hex(0xFB414A24),
    destructive_16: hex(0xFB414A29),
    destructive_18: hex(0xFB414A2E),
    destructive_20: hex(0xFB414A33),
    destructive_24: hex(0xFB414A3D),
    destructive_30: hex(0xFB414A4D),
    destructive_32: hex(0xFB414A52),
    destructive_35: hex(0xFB414A59),
    destructive_36: hex(0xFB414A5C),
    destructive_4: hex(0xFB414A0A),
    destructive_40: hex(0xFB414A66),
    destructive_48: hex(0xFB414A7A),
    destructive_5: hex(0xFB414A0D),
    destructive_6: hex(0xFB414A0F),
    destructive_64: hex(0xFB414AA3),
    destructive_8: hex(0xFB414A14),
    destructive_80: hex(0xFB414ACC),
    destructive_90: hex(0xFB414AE6),
    emerald_300_90: hex(0x5EE9B5E6),
    emerald_500_70: hex(0x00BC7DB3),
    error_foreground_80: hex(0xFF6467CC),
    error_32: hex(0xFB414A52),
    error_80: hex(0xFB414ACC),
    foreground_10: hex(0xFAFAF91A),
    foreground_15: hex(0xFAFAF926),
    foreground_18: hex(0xFAFAF92E),
    foreground_20: hex(0xFAFAF933),
    foreground_25: hex(0xFAFAF940),
    foreground_28: hex(0xFAFAF947),
    foreground_30: hex(0xFAFAF94D),
    foreground_4: hex(0xFAFAF90A),
    foreground_5: hex(0xFAFAF90D),
    foreground_60: hex(0xFAFAF999),
    foreground_64: hex(0xFAFAF9A3),
    foreground_65: hex(0xFAFAF9A6),
    foreground_70: hex(0xFAFAF9B3),
    foreground_75: hex(0xFAFAF9BF),
    foreground_8: hex(0xFAFAF914),
    foreground_80: hex(0xFAFAF9CC),
    foreground_85: hex(0xFAFAF9D9),
    foreground_90: hex(0xFAFAF9E6),
    foreground_95: hex(0xFAFAF9F2),
    indigo_300_90: hex(0xA3B3FFE6),
    info_10: hex(0x2B7FFF1A),
    info_16: hex(0x2B7FFF29),
    info_20: hex(0x2B7FFF33),
    info_32: hex(0x2B7FFF52),
    info_4: hex(0x2B7FFF0A),
    info_40: hex(0x2B7FFF66),
    info_70: hex(0x2B7FFFB3),
    info_8: hex(0x2B7FFF14),
    info_80: hex(0x2B7FFFCC),
    input_32: hex(0x3E3E3E52),
    input_40: hex(0x3E3E3E66),
    input_64: hex(0x3E3E3EA3),
    input_72: hex(0x3E3E3EB8),
    message_action_foreground_20: hex(0x1C1C1C33),
    message_foreground_80: hex(0xFAFAF9CC),
    muted_foreground_15: hex(0x9E9E9E26),
    muted_foreground_20: hex(0x9E9E9E33),
    muted_foreground_24: hex(0x9E9E9E3D),
    muted_foreground_25: hex(0x9E9E9E40),
    muted_foreground_30: hex(0x9E9E9E4D),
    muted_foreground_35: hex(0x9E9E9E59),
    muted_foreground_40: hex(0x9E9E9E66),
    muted_foreground_45: hex(0x9E9E9E73),
    muted_foreground_50: hex(0x9E9E9E80),
    muted_foreground_55: hex(0x9E9E9E8C),
    muted_foreground_60: hex(0x9E9E9E99),
    muted_foreground_65: hex(0x9E9E9EA6),
    muted_foreground_70: hex(0x9E9E9EB3),
    muted_foreground_72: hex(0x9E9E9EB8),
    muted_foreground_75: hex(0x9E9E9EBF),
    muted_foreground_80: hex(0x9E9E9ECC),
    muted_foreground_85: hex(0x9E9E9ED9),
    muted_foreground_90: hex(0x9E9E9EE6),
    muted_10: hex(0x3434341A),
    muted_15: hex(0x34343426),
    muted_20: hex(0x34343433),
    muted_24: hex(0x3434343D),
    muted_25: hex(0x34343440),
    muted_30: hex(0x3434344D),
    muted_32: hex(0x34343452),
    muted_35: hex(0x34343459),
    muted_40: hex(0x34343466),
    muted_45: hex(0x34343473),
    muted_50: hex(0x34343480),
    muted_55: hex(0x3434348C),
    muted_60: hex(0x34343499),
    muted_72: hex(0x343434B8),
    muted_8: hex(0x34343414),
    placeholder_75: hex(0x9E9E9EBF),
    popover_foreground_90: hex(0xFAFAF9E6),
    popover_92: hex(0x343434EB),
    popover_95: hex(0x343434F2),
    primary_10: hex(0xFAFAF91A),
    primary_15: hex(0xFAFAF926),
    primary_25: hex(0xFAFAF940),
    primary_30: hex(0xFAFAF94D),
    primary_35: hex(0xFAFAF959),
    primary_40: hex(0xFAFAF966),
    primary_5: hex(0xFAFAF90D),
    primary_50: hex(0xFAFAF980),
    primary_55: hex(0xFAFAF98C),
    primary_60: hex(0xFAFAF999),
    primary_70: hex(0xFAFAF9B3),
    primary_8: hex(0xFAFAF914),
    primary_90: hex(0xFAFAF9E6),
    purple_500_70: hex(0xAD46FFB3),
    red_300_90: hex(0xFFA2A2E6),
    red_500_70: hex(0xFB2C36B3),
    ring_24: hex(0x9E9E9E3D),
    ring_50: hex(0x9E9E9E80),
    ring_60: hex(0x9E9E9E99),
    ring_70: hex(0x9E9E9EB3),
    secondary_label_70: hex(0x9E9E9EB3),
    secondary_80: hex(0x2D2D2CCC),
    secondary_90: hex(0x2D2D2CE6),
    sidebar_border_60: hex(0x33333399),
    sidebar_foreground_25: hex(0xE1E1E040),
    sidebar_foreground_80: hex(0xE1E1E0CC),
    sidebar_foreground_90: hex(0xE1E1E0E6),
    sidebar_muted_foreground_55: hex(0x9E9E9E8C),
    sidebar_muted_foreground_60: hex(0x9E9E9E99),
    sidebar_muted_foreground_70: hex(0x9E9E9EB3),
    sidebar_muted_foreground_75: hex(0x9E9E9EBF),
    sidebar_muted_foreground_80: hex(0x9E9E9ECC),
    sky_300_80: hex(0x74D4FFCC),
    success_10: hex(0x00BC7D1A),
    success_15: hex(0x00BC7D26),
    success_16: hex(0x00BC7D29),
    success_25: hex(0x00BC7D40),
    success_30: hex(0x00BC7D4D),
    success_32: hex(0x00BC7D52),
    success_4: hex(0x00BC7D0A),
    success_60: hex(0x00BC7D99),
    success_8: hex(0x00BC7D14),
    success_80: hex(0x00BC7DCC),
    teal_300_90: hex(0x46ECD5E6),
    thumb_border_78: hex(0x3E3E3EC7),
    thumb_foreground_18: hex(0xFAFAF92E),
    tool_error_icon_40: hex(0xFCA5A566),
    violet_300_90: hex(0xC4B4FFE6),
    warning_foreground_80: hex(0xFFB900CC),
    warning_10: hex(0xFE9A001A),
    warning_12: hex(0xFE9A001F),
    warning_14: hex(0xFE9A0024),
    warning_16: hex(0xFE9A0029),
    warning_18: hex(0xFE9A002E),
    warning_20: hex(0xFE9A0033),
    warning_24: hex(0xFE9A003D),
    warning_25: hex(0xFE9A0040),
    warning_30: hex(0xFE9A004D),
    warning_32: hex(0xFE9A0052),
    warning_4: hex(0xFE9A000A),
    warning_40: hex(0xFE9A0066),
    warning_60: hex(0xFE9A0099),
    warning_8: hex(0xFE9A0014),
    warning_80: hex(0xFE9A00CC),
    warning_90: hex(0xFE9A00E6),
    white_10: hex(0xFFFFFF1A),
    white_2: hex(0xFFFFFF05),
    white_20: hex(0xFFFFFF33),
    white_3: hex(0xFFFFFF08),
    white_4: hex(0xFFFFFF0A),
    white_5: hex(0xFFFFFF0D),
    white_65: hex(0xFFFFFFA6),
    white_7: hex(0xFFFFFF12),
    white_70: hex(0xFFFFFFB3),
    white_80: hex(0xFFFFFFCC),
    white_90: hex(0xFFFFFFE6),
    zinc_400_80: hex(0x9F9FA9CC),
    outline: hex(0x9E9E9E80),
    border_mix_78: hex(0x3E3E3EC7),
    border_mix_60: hex(0x3E3E3E99),
    foreground_mix_8: hex(0xFAFAF914),
    app_sidebar_glass: hex(0x222222FF),
    app_main_glass: hex(0x1C1C1CFF),
    composer_glass: hex(0x2D2D2CFF),
    codeblock_bg: hex(0x222222FF),
    diff_viewport: hex(0x1C1C1CFF),
    diff_file_surface: hex(0x2D2D2CFF),
    inset_highlight: hex(0xFFFFFF29),
    inset_press: hex(0x00000014),
    group_text_bevel: hex(0x0000000F),
    skeleton_highlight: hex(0xFFFFFF0A),
    bevel: hex(0xFFFFFF0F),
    bevel_pressed: hex(0xFFFFFF05),
    scrollbar_thumb: hex(0xFFFFFF14),
    scrollbar_thumb_hover: hex(0xFFFFFF1F),
    model_picker_thumb: hex(0xFFFFFF14),
    model_picker_thumb_hover: hex(0xFFFFFF26),
    code_scrollbar_thumb: hex(0x3E3E3EC7),
    scroll_area_thumb: hex(0xFAFAF933),
    input_48: hex(0x3E3E3E7A),
    primary_24: hex(0xFAFAF93D),
    ring_45: hex(0x9E9E9E73),
    status: DARK_STATUS,
    terminal: DARK_TERMINAL,
};

/// The light appearance inside `[data-app-sidebar]`, which re-declares some tokens.
pub const SIDEBAR_LIGHT: Colors = Colors { ..LIGHT };

/// The dark appearance inside `[data-app-sidebar]`, which re-declares some tokens.
pub const SIDEBAR_DARK: Colors = Colors {
    contrast_sidebar_border: hex(0x3E3E3EFF),
    sidebar_border: hex(0x3E3E3EFF),
    sidebar_control_surface: hex(0x343434FF),
    sidebar_row_active: hex(0xFAFAF91C),
    sidebar_row_hover: hex(0xFAFAF914),
    sidebar_row_selected: hex(0xFAFAF912),
    sidebar_stage_fade: hex(0x2D2D2CFF),
    sidebar_border_60: hex(0x3E3E3E99),
    ..DARK
};

/// Text and dot color of one sidebar status.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct StatusColor {
    pub text: Hsla,
    pub dot: Hsla,
}

/// Sidebar thread status and PR pill palette (`Sidebar.logic.ts`, `ThreadStatusIndicators.tsx`).
#[derive(Clone, Copy, Debug, PartialEq)]
#[non_exhaustive]
pub struct StatusColors {
    /// working (sky)
    pub working: StatusColor,
    /// pending-approval (amber)
    pub pending_approval: StatusColor,
    /// awaiting-input (indigo)
    pub awaiting_input: StatusColor,
    /// error (rose)
    pub error: StatusColor,
    /// plan-ready (violet)
    pub plan_ready: StatusColor,
    /// completed / pr-open (emerald)
    pub completed: StatusColor,
    /// pr-closed (zinc)
    pub pr_closed: StatusColor,
    /// pr-merged (violet)
    pub pr_merged: StatusColor,
    /// terminal-running (teal)
    pub terminal_running: StatusColor,
}

const LIGHT_STATUS: StatusColors = StatusColors {
    working: StatusColor {
        text: hex(0x0084D1FF),
        dot: hex(0x00A6F4FF),
    },
    pending_approval: StatusColor {
        text: hex(0xE17100FF),
        dot: hex(0xFE9A00FF),
    },
    awaiting_input: StatusColor {
        text: hex(0x4F39F6FF),
        dot: hex(0x615FFFFF),
    },
    error: StatusColor {
        text: hex(0xEC003FFF),
        dot: hex(0xFF2056FF),
    },
    plan_ready: StatusColor {
        text: hex(0x7F22FEFF),
        dot: hex(0x8E51FFFF),
    },
    completed: StatusColor {
        text: hex(0x009966FF),
        dot: hex(0x00BC7DFF),
    },
    pr_closed: StatusColor {
        text: hex(0x71717BFF),
        dot: hex(0x71717BFF),
    },
    pr_merged: StatusColor {
        text: hex(0x7F22FEFF),
        dot: hex(0x7F22FEFF),
    },
    terminal_running: StatusColor {
        text: hex(0x009689FF),
        dot: hex(0x009689FF),
    },
};

const DARK_STATUS: StatusColors = StatusColors {
    working: StatusColor {
        text: hex(0x74D4FFCC),
        dot: hex(0x74D4FFCC),
    },
    pending_approval: StatusColor {
        text: hex(0xFFD230E6),
        dot: hex(0xFFD230E6),
    },
    awaiting_input: StatusColor {
        text: hex(0xA3B3FFE6),
        dot: hex(0xA3B3FFE6),
    },
    error: StatusColor {
        text: hex(0xFFA1ADE6),
        dot: hex(0xFFA1ADE6),
    },
    plan_ready: StatusColor {
        text: hex(0xC4B4FFE6),
        dot: hex(0xC4B4FFE6),
    },
    completed: StatusColor {
        text: hex(0x5EE9B5E6),
        dot: hex(0x5EE9B5E6),
    },
    pr_closed: StatusColor {
        text: hex(0x9F9FA9CC),
        dot: hex(0x9F9FA9CC),
    },
    pr_merged: StatusColor {
        text: hex(0xC4B4FFE6),
        dot: hex(0xC4B4FFE6),
    },
    terminal_running: StatusColor {
        text: hex(0x46ECD5E6),
        dot: hex(0x46ECD5E6),
    },
};

/// Terminal colors. Background and foreground follow `terminal_background` /
/// `terminal_foreground`; cursor and selection come from `--terminal-*`.
#[derive(Clone, Copy, Debug, PartialEq)]
#[non_exhaustive]
pub struct TerminalColors {
    pub cursor: Hsla,
    pub selection_background: Hsla,
    pub scrollbar_slider_background: Hsla,
    pub scrollbar_slider_hover_background: Hsla,
    pub scrollbar_slider_active_background: Hsla,
    pub black: Hsla,
    pub red: Hsla,
    pub green: Hsla,
    pub yellow: Hsla,
    pub blue: Hsla,
    pub magenta: Hsla,
    pub cyan: Hsla,
    pub white: Hsla,
    pub bright_black: Hsla,
    pub bright_red: Hsla,
    pub bright_green: Hsla,
    pub bright_yellow: Hsla,
    pub bright_blue: Hsla,
    pub bright_magenta: Hsla,
    pub bright_cyan: Hsla,
    pub bright_white: Hsla,
}

const LIGHT_TERMINAL: TerminalColors = TerminalColors {
    cursor: hex(0x26384EFF),
    selection_background: hex(0x253F6333),
    scrollbar_slider_background: hex(0x00000026),
    scrollbar_slider_hover_background: hex(0x00000040),
    scrollbar_slider_active_background: hex(0x0000004D),
    black: hex(0x2C3542FF),
    red: hex(0xBF4657FF),
    green: hex(0x3C7E56FF),
    yellow: hex(0x927023FF),
    blue: hex(0x4866A3FF),
    magenta: hex(0x845695FF),
    cyan: hex(0x357F8DFF),
    white: hex(0xD2D7DFFF),
    bright_black: hex(0x707B8CFF),
    bright_red: hex(0xD45F70FF),
    bright_green: hex(0x55946FFF),
    bright_yellow: hex(0xAD852DFF),
    bright_blue: hex(0x5B7CC2FF),
    bright_magenta: hex(0x996BACFF),
    bright_cyan: hex(0x4695A4FF),
    bright_white: hex(0xECF0F6FF),
};

const DARK_TERMINAL: TerminalColors = TerminalColors {
    cursor: hex(0xB4CBFFFF),
    selection_background: hex(0xB4CBFF40),
    scrollbar_slider_background: hex(0xFFFFFF1A),
    scrollbar_slider_hover_background: hex(0xFFFFFF2E),
    scrollbar_slider_active_background: hex(0xFFFFFF38),
    black: hex(0x181E26FF),
    red: hex(0xFF7A8EFF),
    green: hex(0x86E795FF),
    yellow: hex(0xF4CD72FF),
    blue: hex(0x89BEFFFF),
    magenta: hex(0xD0B0FFFF),
    cyan: hex(0x7CE8EDFF),
    white: hex(0xD2DAE6FF),
    bright_black: hex(0x6E7888FF),
    bright_red: hex(0xFFA8B4FF),
    bright_green: hex(0xB0F5BAFF),
    bright_yellow: hex(0xFFE095FF),
    bright_blue: hex(0xAED2FFFF),
    bright_magenta: hex(0xE5CBFFFF),
    bright_cyan: hex(0xA7F4F7FF),
    bright_white: hex(0xF4F7FCFF),
};

/// The Tailwind v4 default palette (oklch, converted to sRGB) plus the fork's additions,
/// for components that use palette tones directly: `palette::AMBER.s600`,
/// `palette::SKY.s300.opacity(0.8)` (Tailwind `sky-300/80`).
pub mod palette {
    use super::{Hsla, hex};

    /// One hue's shades, 50 (lightest) to 950 (darkest).
    #[derive(Clone, Copy, Debug, PartialEq)]
    pub struct Shades {
        pub s50: Hsla,
        pub s100: Hsla,
        pub s200: Hsla,
        pub s300: Hsla,
        pub s400: Hsla,
        pub s500: Hsla,
        pub s600: Hsla,
        pub s700: Hsla,
        pub s800: Hsla,
        pub s900: Hsla,
        pub s950: Hsla,
    }

    /// Tailwind `red-*`.
    pub const RED: Shades = Shades {
        s50: hex(0xFEF2F2FF),
        s100: hex(0xFFE2E2FF),
        s200: hex(0xFFC9C9FF),
        s300: hex(0xFFA2A2FF),
        s400: hex(0xFF6467FF),
        s500: hex(0xFB2C36FF),
        s600: hex(0xE7000BFF),
        s700: hex(0xC10007FF),
        s800: hex(0x9F0712FF),
        s900: hex(0x82181AFF),
        s950: hex(0x460809FF),
    };
    /// Tailwind `orange-*`.
    pub const ORANGE: Shades = Shades {
        s50: hex(0xFFF7EDFF),
        s100: hex(0xFFEDD4FF),
        s200: hex(0xFFD6A7FF),
        s300: hex(0xFFB86AFF),
        s400: hex(0xFF8904FF),
        s500: hex(0xFF6900FF),
        s600: hex(0xF54900FF),
        s700: hex(0xCA3500FF),
        s800: hex(0x9F2D00FF),
        s900: hex(0x7E2A0CFF),
        s950: hex(0x441306FF),
    };
    /// Tailwind `amber-*`.
    pub const AMBER: Shades = Shades {
        s50: hex(0xFFFBEBFF),
        s100: hex(0xFEF3C6FF),
        s200: hex(0xFEE685FF),
        s300: hex(0xFFD230FF),
        s400: hex(0xFFB900FF),
        s500: hex(0xFE9A00FF),
        s600: hex(0xE17100FF),
        s700: hex(0xBB4D00FF),
        s800: hex(0x973C00FF),
        s900: hex(0x7B3306FF),
        s950: hex(0x461901FF),
    };
    /// Tailwind `yellow-*`.
    pub const YELLOW: Shades = Shades {
        s50: hex(0xFEFCE8FF),
        s100: hex(0xFEF9C2FF),
        s200: hex(0xFFF085FF),
        s300: hex(0xFFDF20FF),
        s400: hex(0xFDC700FF),
        s500: hex(0xF0B100FF),
        s600: hex(0xD08700FF),
        s700: hex(0xA65F00FF),
        s800: hex(0x894B00FF),
        s900: hex(0x733E0AFF),
        s950: hex(0x432004FF),
    };
    /// Tailwind `lime-*`.
    pub const LIME: Shades = Shades {
        s50: hex(0xF7FEE7FF),
        s100: hex(0xECFCCAFF),
        s200: hex(0xD8F999FF),
        s300: hex(0xBBF451FF),
        s400: hex(0x9AE600FF),
        s500: hex(0x7CCF00FF),
        s600: hex(0x5EA500FF),
        s700: hex(0x497D00FF),
        s800: hex(0x3C6300FF),
        s900: hex(0x35530EFF),
        s950: hex(0x192E03FF),
    };
    /// Tailwind `green-*`.
    pub const GREEN: Shades = Shades {
        s50: hex(0xF0FDF4FF),
        s100: hex(0xDCFCE7FF),
        s200: hex(0xB9F8CFFF),
        s300: hex(0x7BF1A8FF),
        s400: hex(0x05DF72FF),
        s500: hex(0x00C950FF),
        s600: hex(0x00A63EFF),
        s700: hex(0x008236FF),
        s800: hex(0x016630FF),
        s900: hex(0x0D542BFF),
        s950: hex(0x032E15FF),
    };
    /// Tailwind `emerald-*`.
    pub const EMERALD: Shades = Shades {
        s50: hex(0xECFDF5FF),
        s100: hex(0xD0FAE5FF),
        s200: hex(0xA4F4CFFF),
        s300: hex(0x5EE9B5FF),
        s400: hex(0x00D492FF),
        s500: hex(0x00BC7DFF),
        s600: hex(0x009966FF),
        s700: hex(0x007A55FF),
        s800: hex(0x006045FF),
        s900: hex(0x004F3BFF),
        s950: hex(0x002C22FF),
    };
    /// Tailwind `teal-*`.
    pub const TEAL: Shades = Shades {
        s50: hex(0xF0FDFAFF),
        s100: hex(0xCBFBF1FF),
        s200: hex(0x96F7E4FF),
        s300: hex(0x46ECD5FF),
        s400: hex(0x00D5BEFF),
        s500: hex(0x00BBA7FF),
        s600: hex(0x009689FF),
        s700: hex(0x00786FFF),
        s800: hex(0x005F5AFF),
        s900: hex(0x0B4F4AFF),
        s950: hex(0x022F2EFF),
    };
    /// Tailwind `cyan-*`.
    pub const CYAN: Shades = Shades {
        s50: hex(0xECFEFFFF),
        s100: hex(0xCEFAFEFF),
        s200: hex(0xA2F4FDFF),
        s300: hex(0x53EAFDFF),
        s400: hex(0x00D3F2FF),
        s500: hex(0x00B8DBFF),
        s600: hex(0x0092B8FF),
        s700: hex(0x007595FF),
        s800: hex(0x005F78FF),
        s900: hex(0x104E64FF),
        s950: hex(0x053345FF),
    };
    /// Tailwind `sky-*`.
    pub const SKY: Shades = Shades {
        s50: hex(0xF0F9FFFF),
        s100: hex(0xDFF2FEFF),
        s200: hex(0xB8E6FEFF),
        s300: hex(0x74D4FFFF),
        s400: hex(0x00BCFFFF),
        s500: hex(0x00A6F4FF),
        s600: hex(0x0084D1FF),
        s700: hex(0x0069A8FF),
        s800: hex(0x00598AFF),
        s900: hex(0x024A70FF),
        s950: hex(0x052F4AFF),
    };
    /// Tailwind `blue-*`.
    pub const BLUE: Shades = Shades {
        s50: hex(0xEFF6FFFF),
        s100: hex(0xDBEAFEFF),
        s200: hex(0xBEDBFFFF),
        s300: hex(0x8EC5FFFF),
        s400: hex(0x51A2FFFF),
        s500: hex(0x2B7FFFFF),
        s600: hex(0x155DFCFF),
        s700: hex(0x1447E6FF),
        s800: hex(0x193CB8FF),
        s900: hex(0x1C398EFF),
        s950: hex(0x162456FF),
    };
    /// Tailwind `indigo-*`.
    pub const INDIGO: Shades = Shades {
        s50: hex(0xEEF2FFFF),
        s100: hex(0xE0E7FFFF),
        s200: hex(0xC6D2FFFF),
        s300: hex(0xA3B3FFFF),
        s400: hex(0x7C86FFFF),
        s500: hex(0x615FFFFF),
        s600: hex(0x4F39F6FF),
        s700: hex(0x432DD7FF),
        s800: hex(0x372AACFF),
        s900: hex(0x312C85FF),
        s950: hex(0x1E1A4DFF),
    };
    /// Tailwind `violet-*`.
    pub const VIOLET: Shades = Shades {
        s50: hex(0xF5F3FFFF),
        s100: hex(0xEDE9FEFF),
        s200: hex(0xDDD6FFFF),
        s300: hex(0xC4B4FFFF),
        s400: hex(0xA684FFFF),
        s500: hex(0x8E51FFFF),
        s600: hex(0x7F22FEFF),
        s700: hex(0x7008E7FF),
        s800: hex(0x5D0EC0FF),
        s900: hex(0x4D179AFF),
        s950: hex(0x2F0D68FF),
    };
    /// Tailwind `purple-*`.
    pub const PURPLE: Shades = Shades {
        s50: hex(0xFAF5FFFF),
        s100: hex(0xF3E8FFFF),
        s200: hex(0xE9D4FFFF),
        s300: hex(0xDAB2FFFF),
        s400: hex(0xC27AFFFF),
        s500: hex(0xAD46FFFF),
        s600: hex(0x9810FAFF),
        s700: hex(0x8200DBFF),
        s800: hex(0x6E11B0FF),
        s900: hex(0x59168BFF),
        s950: hex(0x3C0366FF),
    };
    /// Tailwind `fuchsia-*`.
    pub const FUCHSIA: Shades = Shades {
        s50: hex(0xFDF4FFFF),
        s100: hex(0xFAE8FFFF),
        s200: hex(0xF6CFFFFF),
        s300: hex(0xF4A8FFFF),
        s400: hex(0xED6AFFFF),
        s500: hex(0xE12AFBFF),
        s600: hex(0xC800DEFF),
        s700: hex(0xA800B7FF),
        s800: hex(0x8A0194FF),
        s900: hex(0x721378FF),
        s950: hex(0x4B004FFF),
    };
    /// Tailwind `pink-*`.
    pub const PINK: Shades = Shades {
        s50: hex(0xFDF2F8FF),
        s100: hex(0xFCE7F3FF),
        s200: hex(0xFCCEE8FF),
        s300: hex(0xFDA5D5FF),
        s400: hex(0xFB64B6FF),
        s500: hex(0xF6339AFF),
        s600: hex(0xE60076FF),
        s700: hex(0xC6005CFF),
        s800: hex(0xA3004CFF),
        s900: hex(0x861043FF),
        s950: hex(0x510424FF),
    };
    /// Tailwind `rose-*`.
    pub const ROSE: Shades = Shades {
        s50: hex(0xFFF1F2FF),
        s100: hex(0xFFE4E6FF),
        s200: hex(0xFFCCD3FF),
        s300: hex(0xFFA1ADFF),
        s400: hex(0xFF637EFF),
        s500: hex(0xFF2056FF),
        s600: hex(0xEC003FFF),
        s700: hex(0xC70036FF),
        s800: hex(0xA50036FF),
        s900: hex(0x8B0836FF),
        s950: hex(0x4D0218FF),
    };
    /// Tailwind `slate-*`.
    pub const SLATE: Shades = Shades {
        s50: hex(0xF8FAFCFF),
        s100: hex(0xF1F5F9FF),
        s200: hex(0xE2E8F0FF),
        s300: hex(0xCAD5E2FF),
        s400: hex(0x90A1B9FF),
        s500: hex(0x62748EFF),
        s600: hex(0x45556CFF),
        s700: hex(0x314158FF),
        s800: hex(0x1D293DFF),
        s900: hex(0x0F172BFF),
        s950: hex(0x020618FF),
    };
    /// Tailwind `gray-*`.
    pub const GRAY: Shades = Shades {
        s50: hex(0xF9FAFBFF),
        s100: hex(0xF3F4F6FF),
        s200: hex(0xE5E7EBFF),
        s300: hex(0xD1D5DCFF),
        s400: hex(0x99A1AFFF),
        s500: hex(0x6A7282FF),
        s600: hex(0x4A5565FF),
        s700: hex(0x364153FF),
        s800: hex(0x1E2939FF),
        s900: hex(0x101828FF),
        s950: hex(0x030712FF),
    };
    /// Tailwind `zinc-*`.
    pub const ZINC: Shades = Shades {
        s50: hex(0xFAFAFAFF),
        s100: hex(0xF4F4F5FF),
        s200: hex(0xE4E4E7FF),
        s300: hex(0xD4D4D8FF),
        s400: hex(0x9F9FA9FF),
        s500: hex(0x71717BFF),
        s600: hex(0x52525CFF),
        s700: hex(0x3F3F46FF),
        s800: hex(0x27272AFF),
        s900: hex(0x18181BFF),
        s950: hex(0x09090BFF),
    };
    /// `zinc-25` (fork addition).
    pub const ZINC_25: Hsla = hex(0xFCFCFCFF);
    /// Tailwind `neutral-*`.
    pub const NEUTRAL: Shades = Shades {
        s50: hex(0xFAFAFAFF),
        s100: hex(0xF5F5F5FF),
        s200: hex(0xE5E5E5FF),
        s300: hex(0xD4D4D4FF),
        s400: hex(0xA1A1A1FF),
        s500: hex(0x737373FF),
        s600: hex(0x525252FF),
        s700: hex(0x404040FF),
        s800: hex(0x262626FF),
        s900: hex(0x171717FF),
        s950: hex(0x0A0A0AFF),
    };
    /// Tailwind `stone-*`.
    pub const STONE: Shades = Shades {
        s50: hex(0xFAFAF9FF),
        s100: hex(0xF5F5F4FF),
        s200: hex(0xE7E5E4FF),
        s300: hex(0xD6D3D1FF),
        s400: hex(0xA6A09BFF),
        s500: hex(0x79716BFF),
        s600: hex(0x57534DFF),
        s700: hex(0x44403BFF),
        s800: hex(0x292524FF),
        s900: hex(0x1C1917FF),
        s950: hex(0x0C0A09FF),
    };
    /// Tailwind `mauve-*`.
    pub const MAUVE: Shades = Shades {
        s50: hex(0xFAFAFAFF),
        s100: hex(0xF3F1F3FF),
        s200: hex(0xE7E4E7FF),
        s300: hex(0xD7D0D7FF),
        s400: hex(0xA89EA9FF),
        s500: hex(0x79697BFF),
        s600: hex(0x594C5BFF),
        s700: hex(0x463947FF),
        s800: hex(0x2A212CFF),
        s900: hex(0x1D161EFF),
        s950: hex(0x0C090CFF),
    };
    /// Tailwind `olive-*`.
    pub const OLIVE: Shades = Shades {
        s50: hex(0xFBFBF9FF),
        s100: hex(0xF4F4F0FF),
        s200: hex(0xE8E8E3FF),
        s300: hex(0xD8D8D0FF),
        s400: hex(0xABAB9CFF),
        s500: hex(0x7C7C67FF),
        s600: hex(0x5B5B4BFF),
        s700: hex(0x474739FF),
        s800: hex(0x2B2B22FF),
        s900: hex(0x1D1D16FF),
        s950: hex(0x0C0C09FF),
    };
    /// Tailwind `mist-*`.
    pub const MIST: Shades = Shades {
        s50: hex(0xF9FBFBFF),
        s100: hex(0xF1F3F3FF),
        s200: hex(0xE3E7E8FF),
        s300: hex(0xD0D6D8FF),
        s400: hex(0x9CA8ABFF),
        s500: hex(0x67787CFF),
        s600: hex(0x4B585BFF),
        s700: hex(0x394447FF),
        s800: hex(0x22292BFF),
        s900: hex(0x161B1DFF),
        s950: hex(0x090B0CFF),
    };
    /// Tailwind `taupe-*`.
    pub const TAUPE: Shades = Shades {
        s50: hex(0xFBFAF9FF),
        s100: hex(0xF3F1F1FF),
        s200: hex(0xE8E4E3FF),
        s300: hex(0xD8D2D0FF),
        s400: hex(0xABA09CFF),
        s500: hex(0x7C6D67FF),
        s600: hex(0x5B4F4BFF),
        s700: hex(0x473C39FF),
        s800: hex(0x2B2422FF),
        s900: hex(0x1D1816FF),
        s950: hex(0x0C0A09FF),
    };
}

/// Corner radii. `--radius` is 10px; controls (buttons, inputs, toggles) use
/// `--control-radius`, 8px.
pub mod radius {
    use super::{Pixels, px};

    /// `base`
    pub const BASE: Pixels = px(10.0);
    /// `control`
    pub const CONTROL: Pixels = px(8.0);
    /// `xs`
    pub const XS: Pixels = px(2.0);
    /// `sm`
    pub const SM: Pixels = px(6.0);
    /// `md`
    pub const MD: Pixels = px(8.0);
    /// `lg`
    pub const LG: Pixels = px(10.0);
    /// `xl`
    pub const XL: Pixels = px(14.0);
    /// `2xl`
    pub const XL2: Pixels = px(18.0);
    /// `3xl`
    pub const XL3: Pixels = px(22.0);
    /// `rounded`
    pub const ROUNDED: Pixels = px(4.0);
    /// `full`
    pub const FULL: Pixels = px(9999.0);
}

/// Box shadows, exact compiled values. Pass with `.shadow(X.to_vec())`.
pub mod shadow {
    use super::{BoxShadow, hex, point, px};

    /// `shadow-xs/5`
    pub const XS_5: [BoxShadow; 1] = [BoxShadow {
        color: hex(0x0000000D),
        offset: point(px(0.0), px(1.0)),
        blur_radius: px(2.0),
        spread_radius: px(0.0),
        inset: false,
    }];
    /// `shadow-sm/5`
    pub const SM_5: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(1.0)),
            blur_radius: px(3.0),
            spread_radius: px(0.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(1.0)),
            blur_radius: px(2.0),
            spread_radius: px(-1.0),
            inset: false,
        },
    ];
    /// `shadow-md/5`
    pub const MD_5: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(6.0),
            spread_radius: px(-1.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(2.0)),
            blur_radius: px(4.0),
            spread_radius: px(-2.0),
            inset: false,
        },
    ];
    /// `shadow-lg/5`
    pub const LG_5: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(10.0)),
            blur_radius: px(15.0),
            spread_radius: px(-3.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(6.0),
            spread_radius: px(-4.0),
            inset: false,
        },
    ];
    /// `shadow-sm`
    pub const SM: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(1.0)),
            blur_radius: px(3.0),
            spread_radius: px(0.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(1.0)),
            blur_radius: px(2.0),
            spread_radius: px(-1.0),
            inset: false,
        },
    ];
    /// `shadow-md`
    pub const MD: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(6.0),
            spread_radius: px(-1.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(2.0)),
            blur_radius: px(4.0),
            spread_radius: px(-2.0),
            inset: false,
        },
    ];
    /// `shadow-lg`
    pub const LG: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(10.0)),
            blur_radius: px(15.0),
            spread_radius: px(-3.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(6.0),
            spread_radius: px(-4.0),
            inset: false,
        },
    ];
    /// Solid button outer shadow, light (`shadow-xs` in `primary/24`).
    pub const BUTTON_PRIMARY_LIGHT: [BoxShadow; 1] = [BoxShadow {
        color: hex(0x0A0A0A3D),
        offset: point(px(0.0), px(1.0)),
        blur_radius: px(2.0),
        spread_radius: px(0.0),
        inset: false,
    }];
    /// `--shadow-composer`.
    pub const COMPOSER_LIGHT: [BoxShadow; 1] = [BoxShadow {
        color: hex(0x00000066),
        offset: point(px(0.0), px(12.0)),
        blur_radius: px(28.0),
        spread_radius: px(-18.0),
        inset: false,
    }];
    /// `dialog-glass` outer shadow, light.
    pub const DIALOG_GLASS_LIGHT: [BoxShadow; 1] = [BoxShadow {
        color: hex(0x000000A6),
        offset: point(px(0.0), px(24.0)),
        blur_radius: px(64.0),
        spread_radius: px(-24.0),
        inset: false,
    }];
    /// Solid button outer shadow, dark (`shadow-xs` in `primary/24`).
    pub const BUTTON_PRIMARY_DARK: [BoxShadow; 1] = [BoxShadow {
        color: hex(0xFFFFFF3D),
        offset: point(px(0.0), px(1.0)),
        blur_radius: px(2.0),
        spread_radius: px(0.0),
        inset: false,
    }];
    /// `--shadow-composer-dark`.
    pub const COMPOSER_DARK: [BoxShadow; 1] = [BoxShadow {
        color: hex(0x000000BF),
        offset: point(px(0.0), px(14.0)),
        blur_radius: px(32.0),
        spread_radius: px(-18.0),
        inset: false,
    }];
    /// `dialog-glass` outer shadow, dark.
    pub const DIALOG_GLASS_DARK: [BoxShadow; 1] = [BoxShadow {
        color: hex(0x000000E6),
        offset: point(px(0.0), px(24.0)),
        blur_radius: px(72.0),
        spread_radius: px(-20.0),
        inset: false,
    }];
}

/// Type scale: `(font size, line height)` in px for each Tailwind `text-*` class.
pub mod text {
    use super::{Pixels, px};

    /// `text-5xs`: 7/7
    pub const XS5: (Pixels, Pixels) = (px(7.0), px(7.0));
    /// `text-4xs`: 8/8
    pub const XS4: (Pixels, Pixels) = (px(8.0), px(8.0));
    /// `text-3xs`: 10/14
    pub const XS3: (Pixels, Pixels) = (px(10.0), px(14.0));
    /// `text-2xs`: 11/16
    pub const XS2: (Pixels, Pixels) = (px(11.0), px(16.0));
    /// `text-xs`: 12/16
    pub const XS: (Pixels, Pixels) = (px(12.0), px(16.0));
    /// `text-sm`: 14/20
    pub const SM: (Pixels, Pixels) = (px(14.0), px(20.0));
    /// `text-base`: 16/24
    pub const BASE: (Pixels, Pixels) = (px(16.0), px(24.0));
    /// `text-lg`: 18/28
    pub const LG: (Pixels, Pixels) = (px(18.0), px(28.0));
    /// `text-xl`: 20/28
    pub const XL: (Pixels, Pixels) = (px(20.0), px(28.0));
    /// `text-2xl`: 24/32
    pub const XL2: (Pixels, Pixels) = (px(24.0), px(32.0));
    /// `text-3xl`: 30/36
    pub const XL3: (Pixels, Pixels) = (px(30.0), px(36.0));
}
