// @generated by crates/t3-ui/tools/gen_tokens.py from docs/spec/tokens.json. Do not edit.
// Regenerate: python3 crates/t3-ui/tools/gen_tokens.py

use gpui_kit::{BoxShadow, Hsla, Pixels, point, px};

use super::hex;

/// Every color the UI paints, for one appearance. Read the active set with
/// `cx.colors()` ([`crate::ActiveColors`]); [`LIGHT`] and [`DARK`] are the two sets.
///
/// Alpha colors are not pre-composited: paint them over whatever surface is below.
/// `name_NN` is `name` with its alpha multiplied by NN% (Tailwind `name/NN`).
#[derive(Clone, Copy, Debug, PartialEq)]
#[non_exhaustive]
pub struct Colors {
    /// `true` for [`DARK`].
    pub is_dark: bool,
    /// `--background`
    pub background: Hsla,
    /// `--app-chrome-background`
    pub app_chrome_background: Hsla,
    /// `--foreground`
    pub foreground: Hsla,
    /// `--card`
    pub card: Hsla,
    /// `--card-foreground`
    pub card_foreground: Hsla,
    /// `--popover`
    pub popover: Hsla,
    /// `--popover-foreground`
    pub popover_foreground: Hsla,
    /// `--primary`
    pub primary: Hsla,
    /// `--primary-foreground`
    pub primary_foreground: Hsla,
    /// `--secondary`
    pub secondary: Hsla,
    /// `--secondary-foreground`
    pub secondary_foreground: Hsla,
    /// `--muted`
    pub muted: Hsla,
    /// `--muted-foreground`
    pub muted_foreground: Hsla,
    /// `--accent`
    pub accent: Hsla,
    /// `--accent-foreground`
    pub accent_foreground: Hsla,
    /// `--destructive`
    pub destructive: Hsla,
    /// `--destructive-foreground`
    pub destructive_foreground: Hsla,
    /// `--border`
    pub border: Hsla,
    /// `--input`
    pub input: Hsla,
    /// `--ring`
    pub ring: Hsla,
    /// `--info`
    pub info: Hsla,
    /// `--info-foreground`
    pub info_foreground: Hsla,
    /// `--success`
    pub success: Hsla,
    /// `--success-foreground`
    pub success_foreground: Hsla,
    /// `--warning`
    pub warning: Hsla,
    /// `--warning-foreground`
    pub warning_foreground: Hsla,
    /// `--app-sidebar-glass`
    pub app_sidebar_glass: Hsla,
    /// `--app-main-glass`
    pub app_main_glass: Hsla,
    /// `outline (ring/50, every element)`
    pub outline: Hsla,
    /// `ring/24 (input focus ring 3px)`
    pub ring_24: Hsla,
    /// `ring/70`
    pub ring_70: Hsla,
    /// `border-ring/45 (composer focus border)`
    pub ring_45: Hsla,
    /// `border/60`
    pub border_60: Hsla,
    /// `border/80`
    pub border_80: Hsla,
    /// `border@78% (code scrollbar thumb, color-mix srgb)`
    pub border_mix_78: Hsla,
    /// `border@60% (markdown table rule, color-mix srgb)`
    pub border_mix_60: Hsla,
    /// `input/32 (dark control fill)`
    pub input_32: Hsla,
    /// `input/48`
    pub input_48: Hsla,
    /// `input/64 (dark hover / toggle pressed)`
    pub input_64: Hsla,
    /// `accent/45`
    pub accent_45: Hsla,
    /// `accent/50`
    pub accent_50: Hsla,
    /// `accent/60`
    pub accent_60: Hsla,
    /// `primary/90 (button hover)`
    pub primary_90: Hsla,
    /// `primary/70 (composer drag border)`
    pub primary_70: Hsla,
    /// `primary/60 (resize handle active)`
    pub primary_60: Hsla,
    /// `primary/40`
    pub primary_40: Hsla,
    /// `primary/24 (default button shadow color)`
    pub primary_24: Hsla,
    /// `secondary/90`
    pub secondary_90: Hsla,
    /// `secondary/80`
    pub secondary_80: Hsla,
    /// `destructive/90`
    pub destructive_90: Hsla,
    /// `destructive/4`
    pub destructive_4: Hsla,
    /// `destructive/8`
    pub destructive_8: Hsla,
    /// `destructive/16`
    pub destructive_16: Hsla,
    /// `destructive/24`
    pub destructive_24: Hsla,
    /// `destructive/32`
    pub destructive_32: Hsla,
    /// `destructive/36`
    pub destructive_36: Hsla,
    /// `destructive/48`
    pub destructive_48: Hsla,
    /// `destructive/64`
    pub destructive_64: Hsla,
    /// `info/4`
    pub info_4: Hsla,
    /// `info/8`
    pub info_8: Hsla,
    /// `info/16`
    pub info_16: Hsla,
    /// `info/32`
    pub info_32: Hsla,
    /// `success/4`
    pub success_4: Hsla,
    /// `success/8`
    pub success_8: Hsla,
    /// `success/16`
    pub success_16: Hsla,
    /// `success/32`
    pub success_32: Hsla,
    /// `warning/4`
    pub warning_4: Hsla,
    /// `warning/8`
    pub warning_8: Hsla,
    /// `warning/16`
    pub warning_16: Hsla,
    /// `warning/32`
    pub warning_32: Hsla,
    /// `muted/40`
    pub muted_40: Hsla,
    /// `muted/50`
    pub muted_50: Hsla,
    /// `muted/60`
    pub muted_60: Hsla,
    /// `muted/72 (dialog footer, command bg)`
    pub muted_72: Hsla,
    /// `muted-foreground/50`
    pub muted_foreground_50: Hsla,
    /// `muted-foreground/60`
    pub muted_foreground_60: Hsla,
    /// `muted-foreground/70`
    pub muted_foreground_70: Hsla,
    /// `muted-foreground/72 (placeholder, shortcuts)`
    pub muted_foreground_72: Hsla,
    /// `muted-foreground/80`
    pub muted_foreground_80: Hsla,
    /// `foreground/4 (autofill light)`
    pub foreground_4: Hsla,
    /// `foreground/8`
    pub foreground_8: Hsla,
    /// `foreground/20 (ScrollArea thumb)`
    pub foreground_20: Hsla,
    /// `foreground@8% (code chrome pressed, color-mix srgb)`
    pub foreground_mix_8: Hsla,
    /// `background/60 (dialog backdrop)`
    pub background_60: Hsla,
    /// `background/95`
    pub background_95: Hsla,
    /// `popover/92 (toast close orb)`
    pub popover_92: Hsla,
    /// `composer glass bg (card 20% light / 45% dark, srgb)`
    pub composer_glass: Hsla,
    /// `codeblock bg (muted 78% + background, srgb)`
    pub codeblock_bg: Hsla,
    /// `diff panel viewport (background 94% + card)`
    pub diff_viewport: Hsla,
    /// `diff file surface (card 92% + background)`
    pub diff_file_surface: Hsla,
    /// `inset highlight white/16 (solid buttons)`
    pub inset_highlight: Hsla,
    /// `inset press black/8`
    pub inset_press: Hsla,
    /// `group-text before black/6`
    pub group_text_bevel: Hsla,
    /// `skeleton highlight (white/64 light, white/4 dark)`
    pub skeleton_highlight: Hsla,
    /// Edge bevel line (`::before` box-shadow): drawn below in light, above in dark.
    pub bevel: Hsla,
    /// Edge bevel of a pressed outline control (light hides it).
    pub bevel_pressed: Hsla,
    /// Native scrollbar thumb (6px, radius 3).
    pub scrollbar_thumb: Hsla,
    /// Native scrollbar thumb while hovered.
    pub scrollbar_thumb_hover: Hsla,
    /// Model picker scrollbar thumb (4px, radius 2).
    pub model_picker_thumb: Hsla,
    /// Model picker scrollbar thumb while hovered.
    pub model_picker_thumb_hover: Hsla,
    /// Code block horizontal scrollbar thumb (7px, rounded).
    pub code_scrollbar_thumb: Hsla,
    /// Base UI ScrollArea overlay thumb (`foreground/20`).
    pub scroll_area_thumb: Hsla,
    /// Sidebar thread status and PR pill colors.
    pub status: StatusColors,
    /// xterm palette for the terminal drawer.
    pub terminal: TerminalColors,
}

/// The light appearance.
pub const LIGHT: Colors = Colors {
    is_dark: false,
    background: hex(0xFFFFFFFF),
    app_chrome_background: hex(0xFFFFFFFF),
    foreground: hex(0x262626FF),
    card: hex(0xFFFFFFFF),
    card_foreground: hex(0x262626FF),
    popover: hex(0xFFFFFFFF),
    popover_foreground: hex(0x262626FF),
    primary: hex(0x0A0A0AFF),
    primary_foreground: hex(0xFFFFFFFF),
    secondary: hex(0x0000000A),
    secondary_foreground: hex(0x262626FF),
    muted: hex(0x0000000A),
    muted_foreground: hex(0x686868FF),
    accent: hex(0x0000000A),
    accent_foreground: hex(0x262626FF),
    destructive: hex(0xFB2C36FF),
    destructive_foreground: hex(0xC10007FF),
    border: hex(0x00000014),
    input: hex(0x0000001A),
    ring: hex(0x0A0A0AFF),
    info: hex(0x2B7FFFFF),
    info_foreground: hex(0x1447E6FF),
    success: hex(0x00BC7DFF),
    success_foreground: hex(0x007A55FF),
    warning: hex(0xFE9A00FF),
    warning_foreground: hex(0xBB4D00FF),
    app_sidebar_glass: hex(0xFFFFFF94),
    app_main_glass: hex(0xFFFFFFE0),
    outline: hex(0x0A0A0A80),
    ring_24: hex(0x0A0A0A3D),
    ring_70: hex(0x0A0A0AB3),
    ring_45: hex(0x0A0A0A73),
    border_60: hex(0x0000000C),
    border_80: hex(0x00000010),
    border_mix_78: hex(0x00000010),
    border_mix_60: hex(0x0000000C),
    input_32: hex(0x00000008),
    input_48: hex(0x0000000C),
    input_64: hex(0x00000010),
    accent_45: hex(0x00000005),
    accent_50: hex(0x00000005),
    accent_60: hex(0x00000006),
    primary_90: hex(0x0A0A0AE6),
    primary_70: hex(0x0A0A0AB3),
    primary_60: hex(0x0A0A0A99),
    primary_40: hex(0x0A0A0A66),
    primary_24: hex(0x0A0A0A3D),
    secondary_90: hex(0x00000009),
    secondary_80: hex(0x00000008),
    destructive_90: hex(0xFB2C36E6),
    destructive_4: hex(0xFB2C360A),
    destructive_8: hex(0xFB2C3614),
    destructive_16: hex(0xFB2C3629),
    destructive_24: hex(0xFB2C363D),
    destructive_32: hex(0xFB2C3652),
    destructive_36: hex(0xFB2C365C),
    destructive_48: hex(0xFB2C367A),
    destructive_64: hex(0xFB2C36A3),
    info_4: hex(0x2B7FFF0A),
    info_8: hex(0x2B7FFF14),
    info_16: hex(0x2B7FFF29),
    info_32: hex(0x2B7FFF52),
    success_4: hex(0x00BC7D0A),
    success_8: hex(0x00BC7D14),
    success_16: hex(0x00BC7D29),
    success_32: hex(0x00BC7D52),
    warning_4: hex(0xFE9A000A),
    warning_8: hex(0xFE9A0014),
    warning_16: hex(0xFE9A0029),
    warning_32: hex(0xFE9A0052),
    muted_40: hex(0x00000004),
    muted_50: hex(0x00000005),
    muted_60: hex(0x00000006),
    muted_72: hex(0x00000007),
    muted_foreground_50: hex(0x68686880),
    muted_foreground_60: hex(0x68686899),
    muted_foreground_70: hex(0x686868B3),
    muted_foreground_72: hex(0x686868B8),
    muted_foreground_80: hex(0x686868CC),
    foreground_4: hex(0x2626260A),
    foreground_8: hex(0x26262614),
    foreground_20: hex(0x26262633),
    foreground_mix_8: hex(0x26262614),
    background_60: hex(0xFFFFFF99),
    background_95: hex(0xFFFFFFF2),
    popover_92: hex(0xFFFFFFEB),
    composer_glass: hex(0xFFFFFF33),
    codeblock_bg: hex(0xDFDFDF40),
    diff_viewport: hex(0xFFFFFFFF),
    diff_file_surface: hex(0xFFFFFFFF),
    inset_highlight: hex(0xFFFFFF29),
    inset_press: hex(0x00000014),
    group_text_bevel: hex(0x0000000F),
    skeleton_highlight: hex(0xFFFFFFA3),
    bevel: hex(0x0000000A),
    bevel_pressed: hex(0x00000000),
    scrollbar_thumb: hex(0x00000026),
    scrollbar_thumb_hover: hex(0x00000040),
    model_picker_thumb: hex(0x0000001A),
    model_picker_thumb_hover: hex(0x00000033),
    code_scrollbar_thumb: hex(0x00000010),
    scroll_area_thumb: hex(0x26262633),
    status: LIGHT_STATUS,
    terminal: LIGHT_TERMINAL,
};

/// The dark appearance.
pub const DARK: Colors = Colors {
    is_dark: true,
    background: hex(0x161616FF),
    app_chrome_background: hex(0x161616FF),
    foreground: hex(0xF5F5F5FF),
    card: hex(0x1B1B1BFF),
    card_foreground: hex(0xF5F5F5FF),
    popover: hex(0x1B1B1BFF),
    popover_foreground: hex(0xF5F5F5FF),
    primary: hex(0xFFFFFFFF),
    primary_foreground: hex(0x0A0A0AFF),
    secondary: hex(0xFFFFFF0A),
    secondary_foreground: hex(0xF5F5F5FF),
    muted: hex(0xFFFFFF0A),
    muted_foreground: hex(0x818181FF),
    accent: hex(0xFFFFFF0A),
    accent_foreground: hex(0xF5F5F5FF),
    destructive: hex(0xFB414AFF),
    destructive_foreground: hex(0xFF6467FF),
    border: hex(0xFFFFFF0F),
    input: hex(0xFFFFFF14),
    ring: hex(0xFFFFFFFF),
    info: hex(0x2B7FFFFF),
    info_foreground: hex(0x51A2FFFF),
    success: hex(0x00BC7DFF),
    success_foreground: hex(0x00D492FF),
    warning: hex(0xFE9A00FF),
    warning_foreground: hex(0xFFB900FF),
    app_sidebar_glass: hex(0x1B1B1B85),
    app_main_glass: hex(0x161616D6),
    outline: hex(0xFFFFFF80),
    ring_24: hex(0xFFFFFF3D),
    ring_70: hex(0xFFFFFFB3),
    ring_45: hex(0xFFFFFF73),
    border_60: hex(0xFFFFFF09),
    border_80: hex(0xFFFFFF0C),
    border_mix_78: hex(0xFFFFFF0C),
    border_mix_60: hex(0xFFFFFF09),
    input_32: hex(0xFFFFFF07),
    input_48: hex(0xFFFFFF0A),
    input_64: hex(0xFFFFFF0D),
    accent_45: hex(0xFFFFFF05),
    accent_50: hex(0xFFFFFF05),
    accent_60: hex(0xFFFFFF06),
    primary_90: hex(0xFFFFFFE6),
    primary_70: hex(0xFFFFFFB3),
    primary_60: hex(0xFFFFFF99),
    primary_40: hex(0xFFFFFF66),
    primary_24: hex(0xFFFFFF3D),
    secondary_90: hex(0xFFFFFF09),
    secondary_80: hex(0xFFFFFF08),
    destructive_90: hex(0xFB414AE6),
    destructive_4: hex(0xFB414A0A),
    destructive_8: hex(0xFB414A14),
    destructive_16: hex(0xFB414A29),
    destructive_24: hex(0xFB414A3D),
    destructive_32: hex(0xFB414A52),
    destructive_36: hex(0xFB414A5C),
    destructive_48: hex(0xFB414A7A),
    destructive_64: hex(0xFB414AA3),
    info_4: hex(0x2B7FFF0A),
    info_8: hex(0x2B7FFF14),
    info_16: hex(0x2B7FFF29),
    info_32: hex(0x2B7FFF52),
    success_4: hex(0x00BC7D0A),
    success_8: hex(0x00BC7D14),
    success_16: hex(0x00BC7D29),
    success_32: hex(0x00BC7D52),
    warning_4: hex(0xFE9A000A),
    warning_8: hex(0xFE9A0014),
    warning_16: hex(0xFE9A0029),
    warning_32: hex(0xFE9A0052),
    muted_40: hex(0xFFFFFF04),
    muted_50: hex(0xFFFFFF05),
    muted_60: hex(0xFFFFFF06),
    muted_72: hex(0xFFFFFF07),
    muted_foreground_50: hex(0x81818180),
    muted_foreground_60: hex(0x81818199),
    muted_foreground_70: hex(0x818181B3),
    muted_foreground_72: hex(0x818181B8),
    muted_foreground_80: hex(0x818181CC),
    foreground_4: hex(0xF5F5F50A),
    foreground_8: hex(0xF5F5F514),
    foreground_20: hex(0xF5F5F533),
    foreground_mix_8: hex(0xF5F5F514),
    background_60: hex(0x16161699),
    background_95: hex(0x161616F2),
    popover_92: hex(0x1B1B1BEB),
    composer_glass: hex(0x1B1B1B73),
    codeblock_bg: hex(0x33333340),
    diff_viewport: hex(0x171717FF),
    diff_file_surface: hex(0x1B1B1BFF),
    inset_highlight: hex(0xFFFFFF29),
    inset_press: hex(0x00000014),
    group_text_bevel: hex(0x0000000F),
    skeleton_highlight: hex(0xFFFFFF0A),
    bevel: hex(0xFFFFFF0F),
    bevel_pressed: hex(0xFFFFFF05),
    scrollbar_thumb: hex(0xFFFFFF1A),
    scrollbar_thumb_hover: hex(0xFFFFFF2E),
    model_picker_thumb: hex(0xFFFFFF14),
    model_picker_thumb_hover: hex(0xFFFFFF26),
    code_scrollbar_thumb: hex(0xFFFFFF0C),
    scroll_area_thumb: hex(0xF5F5F533),
    status: DARK_STATUS,
    terminal: DARK_TERMINAL,
};

/// Text and dot color of one sidebar status.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct StatusColor {
    pub text: Hsla,
    pub dot: Hsla,
}

/// Sidebar thread status and PR pill palette (`Sidebar.logic.ts`, `ThreadStatusIndicators.tsx`).
#[derive(Clone, Copy, Debug, PartialEq)]
#[non_exhaustive]
pub struct StatusColors {
    /// working (sky)
    pub working: StatusColor,
    /// pending-approval (amber)
    pub pending_approval: StatusColor,
    /// awaiting-input (indigo)
    pub awaiting_input: StatusColor,
    /// error (rose)
    pub error: StatusColor,
    /// plan-ready (violet)
    pub plan_ready: StatusColor,
    /// completed / pr-open (emerald)
    pub completed: StatusColor,
    /// pr-closed (zinc)
    pub pr_closed: StatusColor,
    /// pr-merged (violet)
    pub pr_merged: StatusColor,
    /// terminal-running (teal)
    pub terminal_running: StatusColor,
}

const LIGHT_STATUS: StatusColors = StatusColors {
    working: StatusColor {
        text: hex(0x0084D1FF),
        dot: hex(0x00A6F4FF),
    },
    pending_approval: StatusColor {
        text: hex(0xE17100FF),
        dot: hex(0xFE9A00FF),
    },
    awaiting_input: StatusColor {
        text: hex(0x4F39F6FF),
        dot: hex(0x615FFFFF),
    },
    error: StatusColor {
        text: hex(0xEC003FFF),
        dot: hex(0xFF2056FF),
    },
    plan_ready: StatusColor {
        text: hex(0x7F22FEFF),
        dot: hex(0x8E51FFFF),
    },
    completed: StatusColor {
        text: hex(0x009966FF),
        dot: hex(0x00BC7DFF),
    },
    pr_closed: StatusColor {
        text: hex(0x71717BFF),
        dot: hex(0x71717BFF),
    },
    pr_merged: StatusColor {
        text: hex(0x7F22FEFF),
        dot: hex(0x7F22FEFF),
    },
    terminal_running: StatusColor {
        text: hex(0x009689FF),
        dot: hex(0x009689FF),
    },
};

const DARK_STATUS: StatusColors = StatusColors {
    working: StatusColor {
        text: hex(0x74D4FFCC),
        dot: hex(0x74D4FFCC),
    },
    pending_approval: StatusColor {
        text: hex(0xFFD230E6),
        dot: hex(0xFFD230E6),
    },
    awaiting_input: StatusColor {
        text: hex(0xA3B3FFE6),
        dot: hex(0xA3B3FFE6),
    },
    error: StatusColor {
        text: hex(0xFFA1ADE6),
        dot: hex(0xFFA1ADE6),
    },
    plan_ready: StatusColor {
        text: hex(0xC4B4FFE6),
        dot: hex(0xC4B4FFE6),
    },
    completed: StatusColor {
        text: hex(0x5EE9B5E6),
        dot: hex(0x5EE9B5E6),
    },
    pr_closed: StatusColor {
        text: hex(0x9F9FA9CC),
        dot: hex(0x9F9FA9CC),
    },
    pr_merged: StatusColor {
        text: hex(0xC4B4FFE6),
        dot: hex(0xC4B4FFE6),
    },
    terminal_running: StatusColor {
        text: hex(0x46ECD5E6),
        dot: hex(0x46ECD5E6),
    },
};

/// xterm colors (`ThreadTerminalDrawer.tsx`). Background and foreground follow the
/// drawer's `background` / `foreground`.
#[derive(Clone, Copy, Debug, PartialEq)]
#[non_exhaustive]
pub struct TerminalColors {
    pub cursor: Hsla,
    pub selection_background: Hsla,
    pub scrollbar_slider_background: Hsla,
    pub scrollbar_slider_hover_background: Hsla,
    pub scrollbar_slider_active_background: Hsla,
    pub black: Hsla,
    pub red: Hsla,
    pub green: Hsla,
    pub yellow: Hsla,
    pub blue: Hsla,
    pub magenta: Hsla,
    pub cyan: Hsla,
    pub white: Hsla,
    pub bright_black: Hsla,
    pub bright_red: Hsla,
    pub bright_green: Hsla,
    pub bright_yellow: Hsla,
    pub bright_blue: Hsla,
    pub bright_magenta: Hsla,
    pub bright_cyan: Hsla,
    pub bright_white: Hsla,
}

const LIGHT_TERMINAL: TerminalColors = TerminalColors {
    cursor: hex(0x26384EFF),
    selection_background: hex(0x253F6333),
    scrollbar_slider_background: hex(0x00000026),
    scrollbar_slider_hover_background: hex(0x00000040),
    scrollbar_slider_active_background: hex(0x0000004D),
    black: hex(0x2C3542FF),
    red: hex(0xBF4657FF),
    green: hex(0x3C7E56FF),
    yellow: hex(0x927023FF),
    blue: hex(0x4866A3FF),
    magenta: hex(0x845695FF),
    cyan: hex(0x357F8DFF),
    white: hex(0xD2D7DFFF),
    bright_black: hex(0x707B8CFF),
    bright_red: hex(0xD45F70FF),
    bright_green: hex(0x55946FFF),
    bright_yellow: hex(0xAD852DFF),
    bright_blue: hex(0x5B7CC2FF),
    bright_magenta: hex(0x996BACFF),
    bright_cyan: hex(0x4695A4FF),
    bright_white: hex(0xECF0F6FF),
};

const DARK_TERMINAL: TerminalColors = TerminalColors {
    cursor: hex(0xB4CBFFFF),
    selection_background: hex(0xB4CBFF40),
    scrollbar_slider_background: hex(0xFFFFFF1A),
    scrollbar_slider_hover_background: hex(0xFFFFFF2E),
    scrollbar_slider_active_background: hex(0xFFFFFF38),
    black: hex(0x181E26FF),
    red: hex(0xFF7A8EFF),
    green: hex(0x86E795FF),
    yellow: hex(0xF4CD72FF),
    blue: hex(0x89BEFFFF),
    magenta: hex(0xD0B0FFFF),
    cyan: hex(0x7CE8EDFF),
    white: hex(0xD2DAE6FF),
    bright_black: hex(0x6E7888FF),
    bright_red: hex(0xFFA8B4FF),
    bright_green: hex(0xB0F5BAFF),
    bright_yellow: hex(0xFFE095FF),
    bright_blue: hex(0xAED2FFFF),
    bright_magenta: hex(0xE5CBFFFF),
    bright_cyan: hex(0xA7F4F7FF),
    bright_white: hex(0xF4F7FCFF),
};

/// User-pickable provider accent swatches (`ProviderAccentColorPicker.tsx`).
pub const PROVIDER_ACCENTS: [Hsla; 6] = [
    hex(0x2563EBFF),
    hex(0x16A34AFF),
    hex(0xEA580CFF),
    hex(0xDC2626FF),
    hex(0x7C3AEDFF),
    hex(0x0891B2FF),
];

/// Corner radii (`index.css:83-89`). `rounded-lg` (10px) is the control default.
pub mod radius {
    use super::{Pixels, px};

    /// `base`
    pub const BASE: Pixels = px(10.0);
    /// `sm`
    pub const SM: Pixels = px(6.0);
    /// `md`
    pub const MD: Pixels = px(8.0);
    /// `lg`
    pub const LG: Pixels = px(10.0);
    /// `xl`
    pub const XL: Pixels = px(14.0);
    /// `2xl`
    pub const XL2: Pixels = px(18.0);
    /// `3xl`
    pub const XL3: Pixels = px(22.0);
    /// `4xl`
    pub const XL4: Pixels = px(26.0);
    /// `rounded`
    pub const ROUNDED: Pixels = px(4.0);
    /// `full`
    pub const FULL: Pixels = px(9999.0);
    /// `composerOuter`
    pub const COMPOSER_OUTER: Pixels = px(22.0);
    /// `composerSurface`
    pub const COMPOSER_SURFACE: Pixels = px(20.0);
}

/// Box shadows, exact compiled values (spec section 4.4). Pass with `.shadow(X.to_vec())`.
pub mod shadow {
    use super::{BoxShadow, hex, point, px};

    /// `shadow-xs/5`
    pub const XS_5: [BoxShadow; 1] = [BoxShadow {
        color: hex(0x0000000D),
        offset: point(px(0.0), px(1.0)),
        blur_radius: px(2.0),
        spread_radius: px(0.0),
        inset: false,
    }];
    /// `shadow-sm/5`
    pub const SM_5: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(1.0)),
            blur_radius: px(3.0),
            spread_radius: px(0.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(1.0)),
            blur_radius: px(2.0),
            spread_radius: px(-1.0),
            inset: false,
        },
    ];
    /// `shadow-md/5`
    pub const MD_5: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(6.0),
            spread_radius: px(-1.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(2.0)),
            blur_radius: px(4.0),
            spread_radius: px(-2.0),
            inset: false,
        },
    ];
    /// `shadow-lg/5`
    pub const LG_5: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(10.0)),
            blur_radius: px(15.0),
            spread_radius: px(-3.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000000D),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(6.0),
            spread_radius: px(-4.0),
            inset: false,
        },
    ];
    /// `shadow-sm`
    pub const SM: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(1.0)),
            blur_radius: px(3.0),
            spread_radius: px(0.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(1.0)),
            blur_radius: px(2.0),
            spread_radius: px(-1.0),
            inset: false,
        },
    ];
    /// `shadow-md`
    pub const MD: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(6.0),
            spread_radius: px(-1.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(2.0)),
            blur_radius: px(4.0),
            spread_radius: px(-2.0),
            inset: false,
        },
    ];
    /// `shadow-lg`
    pub const LG: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(10.0)),
            blur_radius: px(15.0),
            spread_radius: px(-3.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x0000001A),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(6.0),
            spread_radius: px(-4.0),
            inset: false,
        },
    ];
    /// Solid button outer shadow, light (`shadow-xs` in `primary/24`).
    pub const BUTTON_PRIMARY_LIGHT: [BoxShadow; 1] = [BoxShadow {
        color: hex(0x0A0A0A3D),
        offset: point(px(0.0), px(1.0)),
        blur_radius: px(2.0),
        spread_radius: px(0.0),
        inset: false,
    }];
    /// Solid button outer shadow, dark (`shadow-xs` in `primary/24`).
    pub const BUTTON_PRIMARY_DARK: [BoxShadow; 1] = [BoxShadow {
        color: hex(0xFFFFFF3D),
        offset: point(px(0.0), px(1.0)),
        blur_radius: px(2.0),
        spread_radius: px(0.0),
        inset: false,
    }];
    /// Composer glass surface shadow, light.
    pub const COMPOSER_LIGHT: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x00000047),
            offset: point(px(0.0), px(18.0)),
            blur_radius: px(48.0),
            spread_radius: px(-20.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x00000038),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(14.0),
            spread_radius: px(-7.0),
            inset: false,
        },
    ];
    /// Composer glass surface shadow, dark.
    pub const COMPOSER_DARK: [BoxShadow; 2] = [
        BoxShadow {
            color: hex(0x00000099),
            offset: point(px(0.0), px(18.0)),
            blur_radius: px(48.0),
            spread_radius: px(-20.0),
            inset: false,
        },
        BoxShadow {
            color: hex(0x00000066),
            offset: point(px(0.0), px(4.0)),
            blur_radius: px(14.0),
            spread_radius: px(-7.0),
            inset: false,
        },
    ];
}

/// Type scale: `(font size, line height)` in px for each Tailwind `text-*` class.
pub mod text {
    use super::{Pixels, px};

    /// `text-xs`: 12/16
    pub const XS: (Pixels, Pixels) = (px(12.0), px(16.0));
    /// `text-sm`: 14/20
    pub const SM: (Pixels, Pixels) = (px(14.0), px(20.0));
    /// `text-base`: 16/24
    pub const BASE: (Pixels, Pixels) = (px(16.0), px(24.0));
    /// `text-lg`: 18/28
    pub const LG: (Pixels, Pixels) = (px(18.0), px(28.0));
    /// `text-xl`: 20/28
    pub const XL: (Pixels, Pixels) = (px(20.0), px(28.0));
    /// `text-2xl`: 24/32
    pub const XL2: (Pixels, Pixels) = (px(24.0), px(32.0));
    /// `text-3xl`: 30/36
    pub const XL3: (Pixels, Pixels) = (px(30.0), px(36.0));
}
